// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/admin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminGetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetUsersRequest) Reset() {
	*x = AdminGetUsersRequest{}
	mi := &file_mage_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetUsersRequest) ProtoMessage() {}

func (x *AdminGetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetUsersRequest.ProtoReflect.Descriptor instead.
func (*AdminGetUsersRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminGetUsersRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AdminGetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserView            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetUsersResponse) Reset() {
	*x = AdminGetUsersResponse{}
	mi := &file_mage_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetUsersResponse) ProtoMessage() {}

func (x *AdminGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetUsersResponse.ProtoReflect.Descriptor instead.
func (*AdminGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminGetUsersResponse) GetUsers() []*UserView {
	if x != nil {
		return x.Users
	}
	return nil
}

type AdminDisconnectUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDisconnectUserRequest) Reset() {
	*x = AdminDisconnectUserRequest{}
	mi := &file_mage_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDisconnectUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDisconnectUserRequest) ProtoMessage() {}

func (x *AdminDisconnectUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDisconnectUserRequest.ProtoReflect.Descriptor instead.
func (*AdminDisconnectUserRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminDisconnectUserRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminDisconnectUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type AdminDisconnectUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDisconnectUserResponse) Reset() {
	*x = AdminDisconnectUserResponse{}
	mi := &file_mage_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDisconnectUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDisconnectUserResponse) ProtoMessage() {}

func (x *AdminDisconnectUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDisconnectUserResponse.ProtoReflect.Descriptor instead.
func (*AdminDisconnectUserResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminDisconnectUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminDisconnectUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminMuteUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserName        string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	DurationMinutes int64                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminMuteUserRequest) Reset() {
	*x = AdminMuteUserRequest{}
	mi := &file_mage_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminMuteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMuteUserRequest) ProtoMessage() {}

func (x *AdminMuteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMuteUserRequest.ProtoReflect.Descriptor instead.
func (*AdminMuteUserRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminMuteUserRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminMuteUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AdminMuteUserRequest) GetDurationMinutes() int64 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type AdminMuteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminMuteUserResponse) Reset() {
	*x = AdminMuteUserResponse{}
	mi := &file_mage_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminMuteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMuteUserResponse) ProtoMessage() {}

func (x *AdminMuteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMuteUserResponse.ProtoReflect.Descriptor instead.
func (*AdminMuteUserResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminMuteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminMuteUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminLockUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserName        string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	DurationMinutes int64                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminLockUserRequest) Reset() {
	*x = AdminLockUserRequest{}
	mi := &file_mage_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLockUserRequest) ProtoMessage() {}

func (x *AdminLockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLockUserRequest.ProtoReflect.Descriptor instead.
func (*AdminLockUserRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminLockUserRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminLockUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AdminLockUserRequest) GetDurationMinutes() int64 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *AdminLockUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AdminLockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLockUserResponse) Reset() {
	*x = AdminLockUserResponse{}
	mi := &file_mage_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLockUserResponse) ProtoMessage() {}

func (x *AdminLockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLockUserResponse.ProtoReflect.Descriptor instead.
func (*AdminLockUserResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminLockUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminLockUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminActivateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminActivateUserRequest) Reset() {
	*x = AdminActivateUserRequest{}
	mi := &file_mage_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminActivateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminActivateUserRequest) ProtoMessage() {}

func (x *AdminActivateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminActivateUserRequest.ProtoReflect.Descriptor instead.
func (*AdminActivateUserRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminActivateUserRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminActivateUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type AdminActivateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminActivateUserResponse) Reset() {
	*x = AdminActivateUserResponse{}
	mi := &file_mage_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminActivateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminActivateUserResponse) ProtoMessage() {}

func (x *AdminActivateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminActivateUserResponse.ProtoReflect.Descriptor instead.
func (*AdminActivateUserResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminActivateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminActivateUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminToggleActivateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminToggleActivateUserRequest) Reset() {
	*x = AdminToggleActivateUserRequest{}
	mi := &file_mage_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminToggleActivateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminToggleActivateUserRequest) ProtoMessage() {}

func (x *AdminToggleActivateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminToggleActivateUserRequest.ProtoReflect.Descriptor instead.
func (*AdminToggleActivateUserRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AdminToggleActivateUserRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminToggleActivateUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type AdminToggleActivateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminToggleActivateUserResponse) Reset() {
	*x = AdminToggleActivateUserResponse{}
	mi := &file_mage_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminToggleActivateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminToggleActivateUserResponse) ProtoMessage() {}

func (x *AdminToggleActivateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminToggleActivateUserResponse.ProtoReflect.Descriptor instead.
func (*AdminToggleActivateUserResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AdminToggleActivateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminToggleActivateUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminEndUserSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminEndUserSessionRequest) Reset() {
	*x = AdminEndUserSessionRequest{}
	mi := &file_mage_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminEndUserSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminEndUserSessionRequest) ProtoMessage() {}

func (x *AdminEndUserSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminEndUserSessionRequest.ProtoReflect.Descriptor instead.
func (*AdminEndUserSessionRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminEndUserSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminEndUserSessionRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type AdminEndUserSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminEndUserSessionResponse) Reset() {
	*x = AdminEndUserSessionResponse{}
	mi := &file_mage_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminEndUserSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminEndUserSessionResponse) ProtoMessage() {}

func (x *AdminEndUserSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminEndUserSessionResponse.ProtoReflect.Descriptor instead.
func (*AdminEndUserSessionResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminEndUserSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminEndUserSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminTableRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TableId       string                 `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminTableRemoveRequest) Reset() {
	*x = AdminTableRemoveRequest{}
	mi := &file_mage_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminTableRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminTableRemoveRequest) ProtoMessage() {}

func (x *AdminTableRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminTableRemoveRequest.ProtoReflect.Descriptor instead.
func (*AdminTableRemoveRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AdminTableRemoveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminTableRemoveRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type AdminTableRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminTableRemoveResponse) Reset() {
	*x = AdminTableRemoveResponse{}
	mi := &file_mage_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminTableRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminTableRemoveResponse) ProtoMessage() {}

func (x *AdminTableRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminTableRemoveResponse.ProtoReflect.Descriptor instead.
func (*AdminTableRemoveResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AdminTableRemoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminTableRemoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminSendBroadcastMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSendBroadcastMessageRequest) Reset() {
	*x = AdminSendBroadcastMessageRequest{}
	mi := &file_mage_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSendBroadcastMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSendBroadcastMessageRequest) ProtoMessage() {}

func (x *AdminSendBroadcastMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSendBroadcastMessageRequest.ProtoReflect.Descriptor instead.
func (*AdminSendBroadcastMessageRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AdminSendBroadcastMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminSendBroadcastMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminSendBroadcastMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSendBroadcastMessageResponse) Reset() {
	*x = AdminSendBroadcastMessageResponse{}
	mi := &file_mage_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSendBroadcastMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSendBroadcastMessageResponse) ProtoMessage() {}

func (x *AdminSendBroadcastMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSendBroadcastMessageResponse.ProtoReflect.Descriptor instead.
func (*AdminSendBroadcastMessageResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *AdminSendBroadcastMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminSendBroadcastMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mage_v1_admin_proto protoreflect.FileDescriptor

const file_mage_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x13mage/v1/admin.proto\x12\amage.v1\x1a\x14mage/v1/models.proto\"5\n" +
	"\x14AdminGetUsersRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"@\n" +
	"\x15AdminGetUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.mage.v1.UserViewR\x05users\"X\n" +
	"\x1aAdminDisconnectUserRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"M\n" +
	"\x1bAdminDisconnectUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"}\n" +
	"\x14AdminMuteUserRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x03R\x0fdurationMinutes\"G\n" +
	"\x15AdminMuteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x95\x01\n" +
	"\x14AdminLockUserRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x03R\x0fdurationMinutes\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"G\n" +
	"\x15AdminLockUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x18AdminActivateUserRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"K\n" +
	"\x19AdminActivateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\\\n" +
	"\x1eAdminToggleActivateUserRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"Q\n" +
	"\x1fAdminToggleActivateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"X\n" +
	"\x1aAdminEndUserSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"M\n" +
	"\x1bAdminEndUserSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"S\n" +
	"\x17AdminTableRemoveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\tR\atableId\"J\n" +
	"\x18AdminTableRemoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"[\n" +
	" AdminSendBroadcastMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"!AdminSendBroadcastMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var (
	file_mage_v1_admin_proto_rawDescOnce sync.Once
	file_mage_v1_admin_proto_rawDescData []byte
)

func file_mage_v1_admin_proto_rawDescGZIP() []byte {
	file_mage_v1_admin_proto_rawDescOnce.Do(func() {
		file_mage_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_v1_admin_proto_rawDesc), len(file_mage_v1_admin_proto_rawDesc)))
	})
	return file_mage_v1_admin_proto_rawDescData
}

var file_mage_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_mage_v1_admin_proto_goTypes = []any{
	(*AdminGetUsersRequest)(nil),              // 0: mage.v1.AdminGetUsersRequest
	(*AdminGetUsersResponse)(nil),             // 1: mage.v1.AdminGetUsersResponse
	(*AdminDisconnectUserRequest)(nil),        // 2: mage.v1.AdminDisconnectUserRequest
	(*AdminDisconnectUserResponse)(nil),       // 3: mage.v1.AdminDisconnectUserResponse
	(*AdminMuteUserRequest)(nil),              // 4: mage.v1.AdminMuteUserRequest
	(*AdminMuteUserResponse)(nil),             // 5: mage.v1.AdminMuteUserResponse
	(*AdminLockUserRequest)(nil),              // 6: mage.v1.AdminLockUserRequest
	(*AdminLockUserResponse)(nil),             // 7: mage.v1.AdminLockUserResponse
	(*AdminActivateUserRequest)(nil),          // 8: mage.v1.AdminActivateUserRequest
	(*AdminActivateUserResponse)(nil),         // 9: mage.v1.AdminActivateUserResponse
	(*AdminToggleActivateUserRequest)(nil),    // 10: mage.v1.AdminToggleActivateUserRequest
	(*AdminToggleActivateUserResponse)(nil),   // 11: mage.v1.AdminToggleActivateUserResponse
	(*AdminEndUserSessionRequest)(nil),        // 12: mage.v1.AdminEndUserSessionRequest
	(*AdminEndUserSessionResponse)(nil),       // 13: mage.v1.AdminEndUserSessionResponse
	(*AdminTableRemoveRequest)(nil),           // 14: mage.v1.AdminTableRemoveRequest
	(*AdminTableRemoveResponse)(nil),          // 15: mage.v1.AdminTableRemoveResponse
	(*AdminSendBroadcastMessageRequest)(nil),  // 16: mage.v1.AdminSendBroadcastMessageRequest
	(*AdminSendBroadcastMessageResponse)(nil), // 17: mage.v1.AdminSendBroadcastMessageResponse
	(*UserView)(nil),                          // 18: mage.v1.UserView
}
var file_mage_v1_admin_proto_depIdxs = []int32{
	18, // 0: mage.v1.AdminGetUsersResponse.users:type_name -> mage.v1.UserView
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_mage_v1_admin_proto_init() }
func file_mage_v1_admin_proto_init() {
	if File_mage_v1_admin_proto != nil {
		return
	}
	file_mage_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_admin_proto_rawDesc), len(file_mage_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_v1_admin_proto_goTypes,
		DependencyIndexes: file_mage_v1_admin_proto_depIdxs,
		MessageInfos:      file_mage_v1_admin_proto_msgTypes,
	}.Build()
	File_mage_v1_admin_proto = out.File
	file_mage_v1_admin_proto_goTypes = nil
	file_mage_v1_admin_proto_depIdxs = nil
}
