// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectUserRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserName         string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SessionId        string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientVersion    string                 `protobuf:"bytes,4,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	UserIdStr        string                 `protobuf:"bytes,5,opt,name=user_id_str,json=userIdStr,proto3" json:"user_id_str,omitempty"`
	RestoreSessionId string                 `protobuf:"bytes,6,opt,name=restore_session_id,json=restoreSessionId,proto3" json:"restore_session_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectUserRequest) Reset() {
	*x = ConnectUserRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectUserRequest) ProtoMessage() {}

func (x *ConnectUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectUserRequest.ProtoReflect.Descriptor instead.
func (*ConnectUserRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ConnectUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConnectUserRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectUserRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ConnectUserRequest) GetUserIdStr() string {
	if x != nil {
		return x.UserIdStr
	}
	return ""
}

func (x *ConnectUserRequest) GetRestoreSessionId() string {
	if x != nil {
		return x.RestoreSessionId
	}
	return ""
}

type ConnectUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectUserResponse) Reset() {
	*x = ConnectUserResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectUserResponse) ProtoMessage() {}

func (x *ConnectUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectUserResponse.ProtoReflect.Descriptor instead.
func (*ConnectUserResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConnectUserResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ConnectAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAdminRequest) Reset() {
	*x = ConnectAdminRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAdminRequest) ProtoMessage() {}

func (x *ConnectAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAdminRequest.ProtoReflect.Descriptor instead.
func (*ConnectAdminRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConnectAdminRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ConnectAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAdminResponse) Reset() {
	*x = ConnectAdminResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAdminResponse) ProtoMessage() {}

func (x *ConnectAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAdminResponse.ProtoReflect.Descriptor instead.
func (*ConnectAdminResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectAdminResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectAdminResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConnectSetUserDataRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SessionId                string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AvatarId                 int32                  `protobuf:"varint,2,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	ShowAbsoluteAbilities    bool                   `protobuf:"varint,3,opt,name=show_absolute_abilities,json=showAbsoluteAbilities,proto3" json:"show_absolute_abilities,omitempty"`
	AllowRequestsFromFriends bool                   `protobuf:"varint,4,opt,name=allow_requests_from_friends,json=allowRequestsFromFriends,proto3" json:"allow_requests_from_friends,omitempty"`
	ConfirmEmptyManaPool     bool                   `protobuf:"varint,5,opt,name=confirm_empty_mana_pool,json=confirmEmptyManaPool,proto3" json:"confirm_empty_mana_pool,omitempty"`
	UserGroup                string                 `protobuf:"bytes,6,opt,name=user_group,json=userGroup,proto3" json:"user_group,omitempty"`
	UserSkipPrioritySteps    []string               `protobuf:"bytes,7,rep,name=user_skip_priority_steps,json=userSkipPrioritySteps,proto3" json:"user_skip_priority_steps,omitempty"`
	FlagsName                string                 `protobuf:"bytes,8,opt,name=flags_name,json=flagsName,proto3" json:"flags_name,omitempty"`
	AskMoveToGraveOrder      int32                  `protobuf:"varint,9,opt,name=ask_move_to_grave_order,json=askMoveToGraveOrder,proto3" json:"ask_move_to_grave_order,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ConnectSetUserDataRequest) Reset() {
	*x = ConnectSetUserDataRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSetUserDataRequest) ProtoMessage() {}

func (x *ConnectSetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSetUserDataRequest.ProtoReflect.Descriptor instead.
func (*ConnectSetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectSetUserDataRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectSetUserDataRequest) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *ConnectSetUserDataRequest) GetShowAbsoluteAbilities() bool {
	if x != nil {
		return x.ShowAbsoluteAbilities
	}
	return false
}

func (x *ConnectSetUserDataRequest) GetAllowRequestsFromFriends() bool {
	if x != nil {
		return x.AllowRequestsFromFriends
	}
	return false
}

func (x *ConnectSetUserDataRequest) GetConfirmEmptyManaPool() bool {
	if x != nil {
		return x.ConfirmEmptyManaPool
	}
	return false
}

func (x *ConnectSetUserDataRequest) GetUserGroup() string {
	if x != nil {
		return x.UserGroup
	}
	return ""
}

func (x *ConnectSetUserDataRequest) GetUserSkipPrioritySteps() []string {
	if x != nil {
		return x.UserSkipPrioritySteps
	}
	return nil
}

func (x *ConnectSetUserDataRequest) GetFlagsName() string {
	if x != nil {
		return x.FlagsName
	}
	return ""
}

func (x *ConnectSetUserDataRequest) GetAskMoveToGraveOrder() int32 {
	if x != nil {
		return x.AskMoveToGraveOrder
	}
	return 0
}

type ConnectSetUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSetUserDataResponse) Reset() {
	*x = ConnectSetUserDataResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSetUserDataResponse) ProtoMessage() {}

func (x *ConnectSetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSetUserDataResponse.ProtoReflect.Descriptor instead.
func (*ConnectSetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectSetUserDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectSetUserDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuthRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRegisterRequest) Reset() {
	*x = AuthRegisterRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegisterRequest) ProtoMessage() {}

func (x *AuthRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegisterRequest.ProtoReflect.Descriptor instead.
func (*AuthRegisterRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *AuthRegisterRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AuthRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthRegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AuthRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRegisterResponse) Reset() {
	*x = AuthRegisterResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegisterResponse) ProtoMessage() {}

func (x *AuthRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegisterResponse.ProtoReflect.Descriptor instead.
func (*AuthRegisterResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AuthRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthRegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuthSendTokenToEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSendTokenToEmailRequest) Reset() {
	*x = AuthSendTokenToEmailRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSendTokenToEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSendTokenToEmailRequest) ProtoMessage() {}

func (x *AuthSendTokenToEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSendTokenToEmailRequest.ProtoReflect.Descriptor instead.
func (*AuthSendTokenToEmailRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *AuthSendTokenToEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AuthSendTokenToEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSendTokenToEmailResponse) Reset() {
	*x = AuthSendTokenToEmailResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSendTokenToEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSendTokenToEmailResponse) ProtoMessage() {}

func (x *AuthSendTokenToEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSendTokenToEmailResponse.ProtoReflect.Descriptor instead.
func (*AuthSendTokenToEmailResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *AuthSendTokenToEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthSendTokenToEmailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuthResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResetPasswordRequest) Reset() {
	*x = AuthResetPasswordRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResetPasswordRequest) ProtoMessage() {}

func (x *AuthResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*AuthResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *AuthResetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type AuthResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResetPasswordResponse) Reset() {
	*x = AuthResetPasswordResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResetPasswordResponse) ProtoMessage() {}

func (x *AuthResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*AuthResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *AuthResetPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResetPasswordResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *PingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetServerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStateRequest) Reset() {
	*x = GetServerStateRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStateRequest) ProtoMessage() {}

func (x *GetServerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStateRequest.ProtoReflect.Descriptor instead.
func (*GetServerStateRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *GetServerStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetServerStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerState   *ServerState           `protobuf:"bytes,1,opt,name=server_state,json=serverState,proto3" json:"server_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStateResponse) Reset() {
	*x = GetServerStateResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStateResponse) ProtoMessage() {}

func (x *GetServerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStateResponse.ProtoReflect.Descriptor instead.
func (*GetServerStateResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *GetServerStateResponse) GetServerState() *ServerState {
	if x != nil {
		return x.ServerState
	}
	return nil
}

type ServerGetPromotionMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetPromotionMessagesRequest) Reset() {
	*x = ServerGetPromotionMessagesRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetPromotionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetPromotionMessagesRequest) ProtoMessage() {}

func (x *ServerGetPromotionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetPromotionMessagesRequest.ProtoReflect.Descriptor instead.
func (*ServerGetPromotionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ServerGetPromotionMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ServerGetPromotionMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetPromotionMessagesResponse) Reset() {
	*x = ServerGetPromotionMessagesResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetPromotionMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetPromotionMessagesResponse) ProtoMessage() {}

func (x *ServerGetPromotionMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetPromotionMessagesResponse.ProtoReflect.Descriptor instead.
func (*ServerGetPromotionMessagesResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *ServerGetPromotionMessagesResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ServerAddFeedbackMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	FeedbackType  string                 `protobuf:"bytes,5,opt,name=feedback_type,json=feedbackType,proto3" json:"feedback_type,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAddFeedbackMessageRequest) Reset() {
	*x = ServerAddFeedbackMessageRequest{}
	mi := &file_mage_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAddFeedbackMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAddFeedbackMessageRequest) ProtoMessage() {}

func (x *ServerAddFeedbackMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAddFeedbackMessageRequest.ProtoReflect.Descriptor instead.
func (*ServerAddFeedbackMessageRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *ServerAddFeedbackMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ServerAddFeedbackMessageRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ServerAddFeedbackMessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ServerAddFeedbackMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerAddFeedbackMessageRequest) GetFeedbackType() string {
	if x != nil {
		return x.FeedbackType
	}
	return ""
}

func (x *ServerAddFeedbackMessageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ServerAddFeedbackMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAddFeedbackMessageResponse) Reset() {
	*x = ServerAddFeedbackMessageResponse{}
	mi := &file_mage_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAddFeedbackMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAddFeedbackMessageResponse) ProtoMessage() {}

func (x *ServerAddFeedbackMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAddFeedbackMessageResponse.ProtoReflect.Descriptor instead.
func (*ServerAddFeedbackMessageResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *ServerAddFeedbackMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerAddFeedbackMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mage_v1_auth_proto protoreflect.FileDescriptor

const file_mage_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12mage/v1/auth.proto\x12\amage.v1\x1a\x14mage/v1/models.proto\"\xe1\x01\n" +
	"\x12ConnectUserRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12%\n" +
	"\x0eclient_version\x18\x04 \x01(\tR\rclientVersion\x12\x1e\n" +
	"\vuser_id_str\x18\x05 \x01(\tR\tuserIdStr\x12,\n" +
	"\x12restore_session_id\x18\x06 \x01(\tR\x10restoreSessionId\"}\n" +
	"\x13ConnectUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"P\n" +
	"\x13ConnectAdminRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"F\n" +
	"\x14ConnectAdminResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb2\x03\n" +
	"\x19ConnectSetUserDataRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tavatar_id\x18\x02 \x01(\x05R\bavatarId\x126\n" +
	"\x17show_absolute_abilities\x18\x03 \x01(\bR\x15showAbsoluteAbilities\x12=\n" +
	"\x1ballow_requests_from_friends\x18\x04 \x01(\bR\x18allowRequestsFromFriends\x125\n" +
	"\x17confirm_empty_mana_pool\x18\x05 \x01(\bR\x14confirmEmptyManaPool\x12\x1d\n" +
	"\n" +
	"user_group\x18\x06 \x01(\tR\tuserGroup\x127\n" +
	"\x18user_skip_priority_steps\x18\a \x03(\tR\x15userSkipPrioritySteps\x12\x1d\n" +
	"\n" +
	"flags_name\x18\b \x01(\tR\tflagsName\x124\n" +
	"\x17ask_move_to_grave_order\x18\t \x01(\x05R\x13askMoveToGraveOrder\"L\n" +
	"\x1aConnectSetUserDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"d\n" +
	"\x13AuthRegisterRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"F\n" +
	"\x14AuthRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"3\n" +
	"\x1bAuthSendTokenToEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"N\n" +
	"\x1cAuthSendTokenToEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"i\n" +
	"\x18AuthResetPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"K\n" +
	"\x19AuthResetPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\vPingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"6\n" +
	"\x15GetServerStateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"Q\n" +
	"\x16GetServerStateResponse\x127\n" +
	"\fserver_state\x18\x01 \x01(\v2\x14.mage.v1.ServerStateR\vserverState\"B\n" +
	"!ServerGetPromotionMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"@\n" +
	"\"ServerGetPromotionMessagesResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages\"\xc8\x01\n" +
	"\x1fServerAddFeedbackMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12#\n" +
	"\rfeedback_type\x18\x05 \x01(\tR\ffeedbackType\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\"R\n" +
	" ServerAddFeedbackMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var (
	file_mage_v1_auth_proto_rawDescOnce sync.Once
	file_mage_v1_auth_proto_rawDescData []byte
)

func file_mage_v1_auth_proto_rawDescGZIP() []byte {
	file_mage_v1_auth_proto_rawDescOnce.Do(func() {
		file_mage_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_v1_auth_proto_rawDesc), len(file_mage_v1_auth_proto_rawDesc)))
	})
	return file_mage_v1_auth_proto_rawDescData
}

var file_mage_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_mage_v1_auth_proto_goTypes = []any{
	(*ConnectUserRequest)(nil),                 // 0: mage.v1.ConnectUserRequest
	(*ConnectUserResponse)(nil),                // 1: mage.v1.ConnectUserResponse
	(*ConnectAdminRequest)(nil),                // 2: mage.v1.ConnectAdminRequest
	(*ConnectAdminResponse)(nil),               // 3: mage.v1.ConnectAdminResponse
	(*ConnectSetUserDataRequest)(nil),          // 4: mage.v1.ConnectSetUserDataRequest
	(*ConnectSetUserDataResponse)(nil),         // 5: mage.v1.ConnectSetUserDataResponse
	(*AuthRegisterRequest)(nil),                // 6: mage.v1.AuthRegisterRequest
	(*AuthRegisterResponse)(nil),               // 7: mage.v1.AuthRegisterResponse
	(*AuthSendTokenToEmailRequest)(nil),        // 8: mage.v1.AuthSendTokenToEmailRequest
	(*AuthSendTokenToEmailResponse)(nil),       // 9: mage.v1.AuthSendTokenToEmailResponse
	(*AuthResetPasswordRequest)(nil),           // 10: mage.v1.AuthResetPasswordRequest
	(*AuthResetPasswordResponse)(nil),          // 11: mage.v1.AuthResetPasswordResponse
	(*PingRequest)(nil),                        // 12: mage.v1.PingRequest
	(*PingResponse)(nil),                       // 13: mage.v1.PingResponse
	(*GetServerStateRequest)(nil),              // 14: mage.v1.GetServerStateRequest
	(*GetServerStateResponse)(nil),             // 15: mage.v1.GetServerStateResponse
	(*ServerGetPromotionMessagesRequest)(nil),  // 16: mage.v1.ServerGetPromotionMessagesRequest
	(*ServerGetPromotionMessagesResponse)(nil), // 17: mage.v1.ServerGetPromotionMessagesResponse
	(*ServerAddFeedbackMessageRequest)(nil),    // 18: mage.v1.ServerAddFeedbackMessageRequest
	(*ServerAddFeedbackMessageResponse)(nil),   // 19: mage.v1.ServerAddFeedbackMessageResponse
	(*ServerState)(nil),                        // 20: mage.v1.ServerState
}
var file_mage_v1_auth_proto_depIdxs = []int32{
	20, // 0: mage.v1.GetServerStateResponse.server_state:type_name -> mage.v1.ServerState
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_mage_v1_auth_proto_init() }
func file_mage_v1_auth_proto_init() {
	if File_mage_v1_auth_proto != nil {
		return
	}
	file_mage_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_auth_proto_rawDesc), len(file_mage_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_v1_auth_proto_goTypes,
		DependencyIndexes: file_mage_v1_auth_proto_depIdxs,
		MessageInfos:      file_mage_v1_auth_proto_msgTypes,
	}.Build()
	File_mage_v1_auth_proto = out.File
	file_mage_v1_auth_proto_goTypes = nil
	file_mage_v1_auth_proto_depIdxs = nil
}
