// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/draft.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DraftJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DraftId       string                 `protobuf:"bytes,2,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftJoinRequest) Reset() {
	*x = DraftJoinRequest{}
	mi := &file_mage_v1_draft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftJoinRequest) ProtoMessage() {}

func (x *DraftJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftJoinRequest.ProtoReflect.Descriptor instead.
func (*DraftJoinRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{0}
}

func (x *DraftJoinRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DraftJoinRequest) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

type DraftJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftJoinResponse) Reset() {
	*x = DraftJoinResponse{}
	mi := &file_mage_v1_draft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftJoinResponse) ProtoMessage() {}

func (x *DraftJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftJoinResponse.ProtoReflect.Descriptor instead.
func (*DraftJoinResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{1}
}

func (x *DraftJoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DraftJoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendDraftCardPickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DraftId       string                 `protobuf:"bytes,2,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	HiddenCards   []string               `protobuf:"bytes,4,rep,name=hidden_cards,json=hiddenCards,proto3" json:"hidden_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDraftCardPickRequest) Reset() {
	*x = SendDraftCardPickRequest{}
	mi := &file_mage_v1_draft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDraftCardPickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDraftCardPickRequest) ProtoMessage() {}

func (x *SendDraftCardPickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDraftCardPickRequest.ProtoReflect.Descriptor instead.
func (*SendDraftCardPickRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{2}
}

func (x *SendDraftCardPickRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendDraftCardPickRequest) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

func (x *SendDraftCardPickRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *SendDraftCardPickRequest) GetHiddenCards() []string {
	if x != nil {
		return x.HiddenCards
	}
	return nil
}

type SendDraftCardPickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDraftCardPickResponse) Reset() {
	*x = SendDraftCardPickResponse{}
	mi := &file_mage_v1_draft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDraftCardPickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDraftCardPickResponse) ProtoMessage() {}

func (x *SendDraftCardPickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDraftCardPickResponse.ProtoReflect.Descriptor instead.
func (*SendDraftCardPickResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{3}
}

func (x *SendDraftCardPickResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendDraftCardPickResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendDraftCardMarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DraftId       string                 `protobuf:"bytes,2,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDraftCardMarkRequest) Reset() {
	*x = SendDraftCardMarkRequest{}
	mi := &file_mage_v1_draft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDraftCardMarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDraftCardMarkRequest) ProtoMessage() {}

func (x *SendDraftCardMarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDraftCardMarkRequest.ProtoReflect.Descriptor instead.
func (*SendDraftCardMarkRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{4}
}

func (x *SendDraftCardMarkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendDraftCardMarkRequest) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

func (x *SendDraftCardMarkRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type SendDraftCardMarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDraftCardMarkResponse) Reset() {
	*x = SendDraftCardMarkResponse{}
	mi := &file_mage_v1_draft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDraftCardMarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDraftCardMarkResponse) ProtoMessage() {}

func (x *SendDraftCardMarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDraftCardMarkResponse.ProtoReflect.Descriptor instead.
func (*SendDraftCardMarkResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{5}
}

func (x *SendDraftCardMarkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendDraftCardMarkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DraftSetBoosterLoadedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DraftId       string                 `protobuf:"bytes,2,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftSetBoosterLoadedRequest) Reset() {
	*x = DraftSetBoosterLoadedRequest{}
	mi := &file_mage_v1_draft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftSetBoosterLoadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftSetBoosterLoadedRequest) ProtoMessage() {}

func (x *DraftSetBoosterLoadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftSetBoosterLoadedRequest.ProtoReflect.Descriptor instead.
func (*DraftSetBoosterLoadedRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{6}
}

func (x *DraftSetBoosterLoadedRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DraftSetBoosterLoadedRequest) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

type DraftSetBoosterLoadedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftSetBoosterLoadedResponse) Reset() {
	*x = DraftSetBoosterLoadedResponse{}
	mi := &file_mage_v1_draft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftSetBoosterLoadedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftSetBoosterLoadedResponse) ProtoMessage() {}

func (x *DraftSetBoosterLoadedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftSetBoosterLoadedResponse.ProtoReflect.Descriptor instead.
func (*DraftSetBoosterLoadedResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{7}
}

func (x *DraftSetBoosterLoadedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DraftSetBoosterLoadedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DraftQuitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DraftId       string                 `protobuf:"bytes,2,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftQuitRequest) Reset() {
	*x = DraftQuitRequest{}
	mi := &file_mage_v1_draft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftQuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftQuitRequest) ProtoMessage() {}

func (x *DraftQuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftQuitRequest.ProtoReflect.Descriptor instead.
func (*DraftQuitRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{8}
}

func (x *DraftQuitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DraftQuitRequest) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

type DraftQuitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftQuitResponse) Reset() {
	*x = DraftQuitResponse{}
	mi := &file_mage_v1_draft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftQuitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftQuitResponse) ProtoMessage() {}

func (x *DraftQuitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_draft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftQuitResponse.ProtoReflect.Descriptor instead.
func (*DraftQuitResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_draft_proto_rawDescGZIP(), []int{9}
}

func (x *DraftQuitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DraftQuitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mage_v1_draft_proto protoreflect.FileDescriptor

const file_mage_v1_draft_proto_rawDesc = "" +
	"\n" +
	"\x13mage/v1/draft.proto\x12\amage.v1\"L\n" +
	"\x10DraftJoinRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bdraft_id\x18\x02 \x01(\tR\adraftId\"C\n" +
	"\x11DraftJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x90\x01\n" +
	"\x18SendDraftCardPickRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bdraft_id\x18\x02 \x01(\tR\adraftId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12!\n" +
	"\fhidden_cards\x18\x04 \x03(\tR\vhiddenCards\"K\n" +
	"\x19SendDraftCardPickResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"m\n" +
	"\x18SendDraftCardMarkRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bdraft_id\x18\x02 \x01(\tR\adraftId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\"K\n" +
	"\x19SendDraftCardMarkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"X\n" +
	"\x1cDraftSetBoosterLoadedRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bdraft_id\x18\x02 \x01(\tR\adraftId\"O\n" +
	"\x1dDraftSetBoosterLoadedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"L\n" +
	"\x10DraftQuitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bdraft_id\x18\x02 \x01(\tR\adraftId\"C\n" +
	"\x11DraftQuitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var (
	file_mage_v1_draft_proto_rawDescOnce sync.Once
	file_mage_v1_draft_proto_rawDescData []byte
)

func file_mage_v1_draft_proto_rawDescGZIP() []byte {
	file_mage_v1_draft_proto_rawDescOnce.Do(func() {
		file_mage_v1_draft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_v1_draft_proto_rawDesc), len(file_mage_v1_draft_proto_rawDesc)))
	})
	return file_mage_v1_draft_proto_rawDescData
}

var file_mage_v1_draft_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mage_v1_draft_proto_goTypes = []any{
	(*DraftJoinRequest)(nil),              // 0: mage.v1.DraftJoinRequest
	(*DraftJoinResponse)(nil),             // 1: mage.v1.DraftJoinResponse
	(*SendDraftCardPickRequest)(nil),      // 2: mage.v1.SendDraftCardPickRequest
	(*SendDraftCardPickResponse)(nil),     // 3: mage.v1.SendDraftCardPickResponse
	(*SendDraftCardMarkRequest)(nil),      // 4: mage.v1.SendDraftCardMarkRequest
	(*SendDraftCardMarkResponse)(nil),     // 5: mage.v1.SendDraftCardMarkResponse
	(*DraftSetBoosterLoadedRequest)(nil),  // 6: mage.v1.DraftSetBoosterLoadedRequest
	(*DraftSetBoosterLoadedResponse)(nil), // 7: mage.v1.DraftSetBoosterLoadedResponse
	(*DraftQuitRequest)(nil),              // 8: mage.v1.DraftQuitRequest
	(*DraftQuitResponse)(nil),             // 9: mage.v1.DraftQuitResponse
}
var file_mage_v1_draft_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mage_v1_draft_proto_init() }
func file_mage_v1_draft_proto_init() {
	if File_mage_v1_draft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_draft_proto_rawDesc), len(file_mage_v1_draft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_v1_draft_proto_goTypes,
		DependencyIndexes: file_mage_v1_draft_proto_depIdxs,
		MessageInfos:      file_mage_v1_draft_proto_msgTypes,
	}.Build()
	File_mage_v1_draft_proto = out.File
	file_mage_v1_draft_proto_goTypes = nil
	file_mage_v1_draft_proto_depIdxs = nil
}
