// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/game.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerAction int32

const (
	PlayerAction_PLAYER_ACTION_UNSPECIFIED PlayerAction = 0
	PlayerAction_PASS                      PlayerAction = 1
	PlayerAction_PASS_TURN                 PlayerAction = 2
	PlayerAction_UNDO                      PlayerAction = 3
	PlayerAction_CONCEDE                   PlayerAction = 4
	PlayerAction_PASS_UNTIL_END_OF_TURN    PlayerAction = 5
	PlayerAction_PASS_UNTIL_NEXT_TURN      PlayerAction = 6
	PlayerAction_PASS_UNTIL_STACK_RESOLVED PlayerAction = 7
	PlayerAction_PASS_UNTIL_MY_NEXT_TURN   PlayerAction = 8
)

// Enum value maps for PlayerAction.
var (
	PlayerAction_name = map[int32]string{
		0: "PLAYER_ACTION_UNSPECIFIED",
		1: "PASS",
		2: "PASS_TURN",
		3: "UNDO",
		4: "CONCEDE",
		5: "PASS_UNTIL_END_OF_TURN",
		6: "PASS_UNTIL_NEXT_TURN",
		7: "PASS_UNTIL_STACK_RESOLVED",
		8: "PASS_UNTIL_MY_NEXT_TURN",
	}
	PlayerAction_value = map[string]int32{
		"PLAYER_ACTION_UNSPECIFIED": 0,
		"PASS":                      1,
		"PASS_TURN":                 2,
		"UNDO":                      3,
		"CONCEDE":                   4,
		"PASS_UNTIL_END_OF_TURN":    5,
		"PASS_UNTIL_NEXT_TURN":      6,
		"PASS_UNTIL_STACK_RESOLVED": 7,
		"PASS_UNTIL_MY_NEXT_TURN":   8,
	}
)

func (x PlayerAction) Enum() *PlayerAction {
	p := new(PlayerAction)
	*p = x
	return p
}

func (x PlayerAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerAction) Descriptor() protoreflect.EnumDescriptor {
	return file_mage_v1_game_proto_enumTypes[0].Descriptor()
}

func (PlayerAction) Type() protoreflect.EnumType {
	return &file_mage_v1_game_proto_enumTypes[0]
}

func (x PlayerAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerAction.Descriptor instead.
func (PlayerAction) EnumDescriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{0}
}

type GameJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameJoinRequest) Reset() {
	*x = GameJoinRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameJoinRequest) ProtoMessage() {}

func (x *GameJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameJoinRequest.ProtoReflect.Descriptor instead.
func (*GameJoinRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameJoinRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GameJoinRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GameJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameJoinResponse) Reset() {
	*x = GameJoinResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameJoinResponse) ProtoMessage() {}

func (x *GameJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameJoinResponse.ProtoReflect.Descriptor instead.
func (*GameJoinResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameJoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GameJoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GameWatchStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameWatchStartRequest) Reset() {
	*x = GameWatchStartRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameWatchStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameWatchStartRequest) ProtoMessage() {}

func (x *GameWatchStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameWatchStartRequest.ProtoReflect.Descriptor instead.
func (*GameWatchStartRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameWatchStartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GameWatchStartRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GameWatchStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameWatchStartResponse) Reset() {
	*x = GameWatchStartResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameWatchStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameWatchStartResponse) ProtoMessage() {}

func (x *GameWatchStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameWatchStartResponse.ProtoReflect.Descriptor instead.
func (*GameWatchStartResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameWatchStartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GameWatchStartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GameWatchStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameWatchStopRequest) Reset() {
	*x = GameWatchStopRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameWatchStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameWatchStopRequest) ProtoMessage() {}

func (x *GameWatchStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameWatchStopRequest.ProtoReflect.Descriptor instead.
func (*GameWatchStopRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameWatchStopRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GameWatchStopRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GameWatchStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameWatchStopResponse) Reset() {
	*x = GameWatchStopResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameWatchStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameWatchStopResponse) ProtoMessage() {}

func (x *GameWatchStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameWatchStopResponse.ProtoReflect.Descriptor instead.
func (*GameWatchStopResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameWatchStopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GameWatchStopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GameGetViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameGetViewRequest) Reset() {
	*x = GameGetViewRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameGetViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameGetViewRequest) ProtoMessage() {}

func (x *GameGetViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameGetViewRequest.ProtoReflect.Descriptor instead.
func (*GameGetViewRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameGetViewRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GameGetViewRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameGetViewRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GameGetViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *GameView              `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameGetViewResponse) Reset() {
	*x = GameGetViewResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameGetViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameGetViewResponse) ProtoMessage() {}

func (x *GameGetViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameGetViewResponse.ProtoReflect.Descriptor instead.
func (*GameGetViewResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameGetViewResponse) GetGame() *GameView {
	if x != nil {
		return x.Game
	}
	return nil
}

type SendPlayerUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerUUIDRequest) Reset() {
	*x = SendPlayerUUIDRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerUUIDRequest) ProtoMessage() {}

func (x *SendPlayerUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerUUIDRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerUUIDRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *SendPlayerUUIDRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendPlayerUUIDRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SendPlayerUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SendPlayerUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerUUIDResponse) Reset() {
	*x = SendPlayerUUIDResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerUUIDResponse) ProtoMessage() {}

func (x *SendPlayerUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerUUIDResponse.ProtoReflect.Descriptor instead.
func (*SendPlayerUUIDResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{9}
}

func (x *SendPlayerUUIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendPlayerUUIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendPlayerStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerStringRequest) Reset() {
	*x = SendPlayerStringRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerStringRequest) ProtoMessage() {}

func (x *SendPlayerStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerStringRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerStringRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{10}
}

func (x *SendPlayerStringRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendPlayerStringRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SendPlayerStringRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SendPlayerStringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerStringResponse) Reset() {
	*x = SendPlayerStringResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerStringResponse) ProtoMessage() {}

func (x *SendPlayerStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerStringResponse.ProtoReflect.Descriptor instead.
func (*SendPlayerStringResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{11}
}

func (x *SendPlayerStringResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendPlayerStringResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendPlayerBooleanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Data          bool                   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerBooleanRequest) Reset() {
	*x = SendPlayerBooleanRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerBooleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerBooleanRequest) ProtoMessage() {}

func (x *SendPlayerBooleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerBooleanRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerBooleanRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{12}
}

func (x *SendPlayerBooleanRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendPlayerBooleanRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SendPlayerBooleanRequest) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type SendPlayerBooleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerBooleanResponse) Reset() {
	*x = SendPlayerBooleanResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerBooleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerBooleanResponse) ProtoMessage() {}

func (x *SendPlayerBooleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerBooleanResponse.ProtoReflect.Descriptor instead.
func (*SendPlayerBooleanResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{13}
}

func (x *SendPlayerBooleanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendPlayerBooleanResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendPlayerIntegerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Data          int32                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerIntegerRequest) Reset() {
	*x = SendPlayerIntegerRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerIntegerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerIntegerRequest) ProtoMessage() {}

func (x *SendPlayerIntegerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerIntegerRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerIntegerRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{14}
}

func (x *SendPlayerIntegerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendPlayerIntegerRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SendPlayerIntegerRequest) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type SendPlayerIntegerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerIntegerResponse) Reset() {
	*x = SendPlayerIntegerResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerIntegerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerIntegerResponse) ProtoMessage() {}

func (x *SendPlayerIntegerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerIntegerResponse.ProtoReflect.Descriptor instead.
func (*SendPlayerIntegerResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{15}
}

func (x *SendPlayerIntegerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendPlayerIntegerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendPlayerManaTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ManaType      string                 `protobuf:"bytes,3,opt,name=mana_type,json=manaType,proto3" json:"mana_type,omitempty"`
	ManaTypeStr   string                 `protobuf:"bytes,4,opt,name=mana_type_str,json=manaTypeStr,proto3" json:"mana_type_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerManaTypeRequest) Reset() {
	*x = SendPlayerManaTypeRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerManaTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerManaTypeRequest) ProtoMessage() {}

func (x *SendPlayerManaTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerManaTypeRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerManaTypeRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{16}
}

func (x *SendPlayerManaTypeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendPlayerManaTypeRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SendPlayerManaTypeRequest) GetManaType() string {
	if x != nil {
		return x.ManaType
	}
	return ""
}

func (x *SendPlayerManaTypeRequest) GetManaTypeStr() string {
	if x != nil {
		return x.ManaTypeStr
	}
	return ""
}

type SendPlayerManaTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerManaTypeResponse) Reset() {
	*x = SendPlayerManaTypeResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerManaTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerManaTypeResponse) ProtoMessage() {}

func (x *SendPlayerManaTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerManaTypeResponse.ProtoReflect.Descriptor instead.
func (*SendPlayerManaTypeResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{17}
}

func (x *SendPlayerManaTypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendPlayerManaTypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendPlayerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Action        PlayerAction           `protobuf:"varint,3,opt,name=action,proto3,enum=mage.v1.PlayerAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerActionRequest) Reset() {
	*x = SendPlayerActionRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerActionRequest) ProtoMessage() {}

func (x *SendPlayerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerActionRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerActionRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{18}
}

func (x *SendPlayerActionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendPlayerActionRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SendPlayerActionRequest) GetAction() PlayerAction {
	if x != nil {
		return x.Action
	}
	return PlayerAction_PLAYER_ACTION_UNSPECIFIED
}

type SendPlayerActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerActionResponse) Reset() {
	*x = SendPlayerActionResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerActionResponse) ProtoMessage() {}

func (x *SendPlayerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerActionResponse.ProtoReflect.Descriptor instead.
func (*SendPlayerActionResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{19}
}

func (x *SendPlayerActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendPlayerActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MatchStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TableId       string                 `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStartRequest) Reset() {
	*x = MatchStartRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartRequest) ProtoMessage() {}

func (x *MatchStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartRequest.ProtoReflect.Descriptor instead.
func (*MatchStartRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{20}
}

func (x *MatchStartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MatchStartRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type MatchStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStartResponse) Reset() {
	*x = MatchStartResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartResponse) ProtoMessage() {}

func (x *MatchStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartResponse.ProtoReflect.Descriptor instead.
func (*MatchStartResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{21}
}

func (x *MatchStartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MatchStartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MatchQuitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchQuitRequest) Reset() {
	*x = MatchQuitRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchQuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQuitRequest) ProtoMessage() {}

func (x *MatchQuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQuitRequest.ProtoReflect.Descriptor instead.
func (*MatchQuitRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{22}
}

func (x *MatchQuitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MatchQuitRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type MatchQuitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchQuitResponse) Reset() {
	*x = MatchQuitResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchQuitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQuitResponse) ProtoMessage() {}

func (x *MatchQuitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQuitResponse.ProtoReflect.Descriptor instead.
func (*MatchQuitResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{23}
}

func (x *MatchQuitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MatchQuitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplayInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayInitRequest) Reset() {
	*x = ReplayInitRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayInitRequest) ProtoMessage() {}

func (x *ReplayInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayInitRequest.ProtoReflect.Descriptor instead.
func (*ReplayInitRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{24}
}

func (x *ReplayInitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayInitRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type ReplayInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayInitResponse) Reset() {
	*x = ReplayInitResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayInitResponse) ProtoMessage() {}

func (x *ReplayInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayInitResponse.ProtoReflect.Descriptor instead.
func (*ReplayInitResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{25}
}

func (x *ReplayInitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplayInitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplayStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayStartRequest) Reset() {
	*x = ReplayStartRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayStartRequest) ProtoMessage() {}

func (x *ReplayStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayStartRequest.ProtoReflect.Descriptor instead.
func (*ReplayStartRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{26}
}

func (x *ReplayStartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayStartRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type ReplayStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayStartResponse) Reset() {
	*x = ReplayStartResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayStartResponse) ProtoMessage() {}

func (x *ReplayStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayStartResponse.ProtoReflect.Descriptor instead.
func (*ReplayStartResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{27}
}

func (x *ReplayStartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplayStartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplayStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayStopRequest) Reset() {
	*x = ReplayStopRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayStopRequest) ProtoMessage() {}

func (x *ReplayStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayStopRequest.ProtoReflect.Descriptor instead.
func (*ReplayStopRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{28}
}

func (x *ReplayStopRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayStopRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type ReplayStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayStopResponse) Reset() {
	*x = ReplayStopResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayStopResponse) ProtoMessage() {}

func (x *ReplayStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayStopResponse.ProtoReflect.Descriptor instead.
func (*ReplayStopResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{29}
}

func (x *ReplayStopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplayStopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplayNextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayNextRequest) Reset() {
	*x = ReplayNextRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayNextRequest) ProtoMessage() {}

func (x *ReplayNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayNextRequest.ProtoReflect.Descriptor instead.
func (*ReplayNextRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{30}
}

func (x *ReplayNextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayNextRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type ReplayNextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayNextResponse) Reset() {
	*x = ReplayNextResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayNextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayNextResponse) ProtoMessage() {}

func (x *ReplayNextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayNextResponse.ProtoReflect.Descriptor instead.
func (*ReplayNextResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{31}
}

func (x *ReplayNextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplayNextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplayPreviousRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayPreviousRequest) Reset() {
	*x = ReplayPreviousRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayPreviousRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayPreviousRequest) ProtoMessage() {}

func (x *ReplayPreviousRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayPreviousRequest.ProtoReflect.Descriptor instead.
func (*ReplayPreviousRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{32}
}

func (x *ReplayPreviousRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayPreviousRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type ReplayPreviousResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayPreviousResponse) Reset() {
	*x = ReplayPreviousResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayPreviousResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayPreviousResponse) ProtoMessage() {}

func (x *ReplayPreviousResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayPreviousResponse.ProtoReflect.Descriptor instead.
func (*ReplayPreviousResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{33}
}

func (x *ReplayPreviousResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplayPreviousResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplaySkipForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Steps         int32                  `protobuf:"varint,3,opt,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaySkipForwardRequest) Reset() {
	*x = ReplaySkipForwardRequest{}
	mi := &file_mage_v1_game_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaySkipForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaySkipForwardRequest) ProtoMessage() {}

func (x *ReplaySkipForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaySkipForwardRequest.ProtoReflect.Descriptor instead.
func (*ReplaySkipForwardRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{34}
}

func (x *ReplaySkipForwardRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplaySkipForwardRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ReplaySkipForwardRequest) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

type ReplaySkipForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaySkipForwardResponse) Reset() {
	*x = ReplaySkipForwardResponse{}
	mi := &file_mage_v1_game_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaySkipForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaySkipForwardResponse) ProtoMessage() {}

func (x *ReplaySkipForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_game_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaySkipForwardResponse.ProtoReflect.Descriptor instead.
func (*ReplaySkipForwardResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_game_proto_rawDescGZIP(), []int{35}
}

func (x *ReplaySkipForwardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplaySkipForwardResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mage_v1_game_proto protoreflect.FileDescriptor

const file_mage_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x12mage/v1/game.proto\x12\amage.v1\x1a\x14mage/v1/models.proto\"I\n" +
	"\x0fGameJoinRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"B\n" +
	"\x10GameJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\x15GameWatchStartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"H\n" +
	"\x16GameWatchStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"N\n" +
	"\x14GameWatchStopRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"G\n" +
	"\x15GameWatchStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"i\n" +
	"\x12GameGetViewRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\"<\n" +
	"\x13GameGetViewResponse\x12%\n" +
	"\x04game\x18\x01 \x01(\v2\x11.mage.v1.GameViewR\x04game\"c\n" +
	"\x15SendPlayerUUIDRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\"H\n" +
	"\x16SendPlayerUUIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"e\n" +
	"\x17SendPlayerStringRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"J\n" +
	"\x18SendPlayerStringResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"f\n" +
	"\x18SendPlayerBooleanRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\bR\x04data\"K\n" +
	"\x19SendPlayerBooleanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"f\n" +
	"\x18SendPlayerIntegerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x05R\x04data\"K\n" +
	"\x19SendPlayerIntegerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x94\x01\n" +
	"\x19SendPlayerManaTypeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tmana_type\x18\x03 \x01(\tR\bmanaType\x12\"\n" +
	"\rmana_type_str\x18\x04 \x01(\tR\vmanaTypeStr\"L\n" +
	"\x1aSendPlayerManaTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x80\x01\n" +
	"\x17SendPlayerActionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12-\n" +
	"\x06action\x18\x03 \x01(\x0e2\x15.mage.v1.PlayerActionR\x06action\"J\n" +
	"\x18SendPlayerActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x11MatchStartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\tR\atableId\"D\n" +
	"\x12MatchStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"J\n" +
	"\x10MatchQuitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"C\n" +
	"\x11MatchQuitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\x11ReplayInitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"D\n" +
	"\x12ReplayInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"L\n" +
	"\x12ReplayStartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"E\n" +
	"\x13ReplayStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\x11ReplayStopRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"D\n" +
	"\x12ReplayStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\x11ReplayNextRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"D\n" +
	"\x12ReplayNextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\x15ReplayPreviousRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"H\n" +
	"\x16ReplayPreviousResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"h\n" +
	"\x18ReplaySkipForwardRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x14\n" +
	"\x05steps\x18\x03 \x01(\x05R\x05steps\"K\n" +
	"\x19ReplaySkipForwardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\xcf\x01\n" +
	"\fPlayerAction\x12\x1d\n" +
	"\x19PLAYER_ACTION_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04PASS\x10\x01\x12\r\n" +
	"\tPASS_TURN\x10\x02\x12\b\n" +
	"\x04UNDO\x10\x03\x12\v\n" +
	"\aCONCEDE\x10\x04\x12\x1a\n" +
	"\x16PASS_UNTIL_END_OF_TURN\x10\x05\x12\x18\n" +
	"\x14PASS_UNTIL_NEXT_TURN\x10\x06\x12\x1d\n" +
	"\x19PASS_UNTIL_STACK_RESOLVED\x10\a\x12\x1b\n" +
	"\x17PASS_UNTIL_MY_NEXT_TURN\x10\bB6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var (
	file_mage_v1_game_proto_rawDescOnce sync.Once
	file_mage_v1_game_proto_rawDescData []byte
)

func file_mage_v1_game_proto_rawDescGZIP() []byte {
	file_mage_v1_game_proto_rawDescOnce.Do(func() {
		file_mage_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_v1_game_proto_rawDesc), len(file_mage_v1_game_proto_rawDesc)))
	})
	return file_mage_v1_game_proto_rawDescData
}

var file_mage_v1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mage_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_mage_v1_game_proto_goTypes = []any{
	(PlayerAction)(0),                  // 0: mage.v1.PlayerAction
	(*GameJoinRequest)(nil),            // 1: mage.v1.GameJoinRequest
	(*GameJoinResponse)(nil),           // 2: mage.v1.GameJoinResponse
	(*GameWatchStartRequest)(nil),      // 3: mage.v1.GameWatchStartRequest
	(*GameWatchStartResponse)(nil),     // 4: mage.v1.GameWatchStartResponse
	(*GameWatchStopRequest)(nil),       // 5: mage.v1.GameWatchStopRequest
	(*GameWatchStopResponse)(nil),      // 6: mage.v1.GameWatchStopResponse
	(*GameGetViewRequest)(nil),         // 7: mage.v1.GameGetViewRequest
	(*GameGetViewResponse)(nil),        // 8: mage.v1.GameGetViewResponse
	(*SendPlayerUUIDRequest)(nil),      // 9: mage.v1.SendPlayerUUIDRequest
	(*SendPlayerUUIDResponse)(nil),     // 10: mage.v1.SendPlayerUUIDResponse
	(*SendPlayerStringRequest)(nil),    // 11: mage.v1.SendPlayerStringRequest
	(*SendPlayerStringResponse)(nil),   // 12: mage.v1.SendPlayerStringResponse
	(*SendPlayerBooleanRequest)(nil),   // 13: mage.v1.SendPlayerBooleanRequest
	(*SendPlayerBooleanResponse)(nil),  // 14: mage.v1.SendPlayerBooleanResponse
	(*SendPlayerIntegerRequest)(nil),   // 15: mage.v1.SendPlayerIntegerRequest
	(*SendPlayerIntegerResponse)(nil),  // 16: mage.v1.SendPlayerIntegerResponse
	(*SendPlayerManaTypeRequest)(nil),  // 17: mage.v1.SendPlayerManaTypeRequest
	(*SendPlayerManaTypeResponse)(nil), // 18: mage.v1.SendPlayerManaTypeResponse
	(*SendPlayerActionRequest)(nil),    // 19: mage.v1.SendPlayerActionRequest
	(*SendPlayerActionResponse)(nil),   // 20: mage.v1.SendPlayerActionResponse
	(*MatchStartRequest)(nil),          // 21: mage.v1.MatchStartRequest
	(*MatchStartResponse)(nil),         // 22: mage.v1.MatchStartResponse
	(*MatchQuitRequest)(nil),           // 23: mage.v1.MatchQuitRequest
	(*MatchQuitResponse)(nil),          // 24: mage.v1.MatchQuitResponse
	(*ReplayInitRequest)(nil),          // 25: mage.v1.ReplayInitRequest
	(*ReplayInitResponse)(nil),         // 26: mage.v1.ReplayInitResponse
	(*ReplayStartRequest)(nil),         // 27: mage.v1.ReplayStartRequest
	(*ReplayStartResponse)(nil),        // 28: mage.v1.ReplayStartResponse
	(*ReplayStopRequest)(nil),          // 29: mage.v1.ReplayStopRequest
	(*ReplayStopResponse)(nil),         // 30: mage.v1.ReplayStopResponse
	(*ReplayNextRequest)(nil),          // 31: mage.v1.ReplayNextRequest
	(*ReplayNextResponse)(nil),         // 32: mage.v1.ReplayNextResponse
	(*ReplayPreviousRequest)(nil),      // 33: mage.v1.ReplayPreviousRequest
	(*ReplayPreviousResponse)(nil),     // 34: mage.v1.ReplayPreviousResponse
	(*ReplaySkipForwardRequest)(nil),   // 35: mage.v1.ReplaySkipForwardRequest
	(*ReplaySkipForwardResponse)(nil),  // 36: mage.v1.ReplaySkipForwardResponse
	(*GameView)(nil),                   // 37: mage.v1.GameView
}
var file_mage_v1_game_proto_depIdxs = []int32{
	37, // 0: mage.v1.GameGetViewResponse.game:type_name -> mage.v1.GameView
	0,  // 1: mage.v1.SendPlayerActionRequest.action:type_name -> mage.v1.PlayerAction
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_mage_v1_game_proto_init() }
func file_mage_v1_game_proto_init() {
	if File_mage_v1_game_proto != nil {
		return
	}
	file_mage_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_game_proto_rawDesc), len(file_mage_v1_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_v1_game_proto_goTypes,
		DependencyIndexes: file_mage_v1_game_proto_depIdxs,
		EnumInfos:         file_mage_v1_game_proto_enumTypes,
		MessageInfos:      file_mage_v1_game_proto_msgTypes,
	}.Build()
	File_mage_v1_game_proto = out.File
	file_mage_v1_game_proto_goTypes = nil
	file_mage_v1_game_proto_depIdxs = nil
}
