// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/models.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageColor int32

const (
	MessageColor_MESSAGE_COLOR_UNSPECIFIED MessageColor = 0
	MessageColor_BLACK                     MessageColor = 1
	MessageColor_GREEN                     MessageColor = 2
	MessageColor_ORANGE                    MessageColor = 3
	MessageColor_BLUE                      MessageColor = 4
	MessageColor_RED                       MessageColor = 5
	MessageColor_YELLOW                    MessageColor = 6
)

// Enum value maps for MessageColor.
var (
	MessageColor_name = map[int32]string{
		0: "MESSAGE_COLOR_UNSPECIFIED",
		1: "BLACK",
		2: "GREEN",
		3: "ORANGE",
		4: "BLUE",
		5: "RED",
		6: "YELLOW",
	}
	MessageColor_value = map[string]int32{
		"MESSAGE_COLOR_UNSPECIFIED": 0,
		"BLACK":                     1,
		"GREEN":                     2,
		"ORANGE":                    3,
		"BLUE":                      4,
		"RED":                       5,
		"YELLOW":                    6,
	}
)

func (x MessageColor) Enum() *MessageColor {
	p := new(MessageColor)
	*p = x
	return p
}

func (x MessageColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageColor) Descriptor() protoreflect.EnumDescriptor {
	return file_mage_v1_models_proto_enumTypes[0].Descriptor()
}

func (MessageColor) Type() protoreflect.EnumType {
	return &file_mage_v1_models_proto_enumTypes[0]
}

func (x MessageColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageColor.Descriptor instead.
func (MessageColor) EnumDescriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_TALK                     MessageType = 1
	MessageType_WHISPER                  MessageType = 2
	MessageType_STATUS                   MessageType = 3
	MessageType_USER_INFO                MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "TALK",
		2: "WHISPER",
		3: "STATUS",
		4: "USER_INFO",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"TALK":                     1,
		"WHISPER":                  2,
		"STATUS":                   3,
		"USER_INFO":                4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_mage_v1_models_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_mage_v1_models_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{1}
}

// TableView represents a game table in the lobby
type TableView struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TableId              string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	GameType             string                 `protobuf:"bytes,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	TableName            string                 `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	ControllerName       string                 `protobuf:"bytes,4,opt,name=controller_name,json=controllerName,proto3" json:"controller_name,omitempty"`
	TableStateText       string                 `protobuf:"bytes,5,opt,name=table_state_text,json=tableStateText,proto3" json:"table_state_text,omitempty"`
	NumSeats             int32                  `protobuf:"varint,6,opt,name=num_seats,json=numSeats,proto3" json:"num_seats,omitempty"`
	Seats                []*SeatView            `protobuf:"bytes,7,rep,name=seats,proto3" json:"seats,omitempty"`
	MatchOptions         *MatchOptions          `protobuf:"bytes,8,opt,name=match_options,json=matchOptions,proto3" json:"match_options,omitempty"`
	CreateTime           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	IsTournament         bool                   `protobuf:"varint,10,opt,name=is_tournament,json=isTournament,proto3" json:"is_tournament,omitempty"`
	TournamentId         string                 `protobuf:"bytes,11,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	DeckValidator        *DeckValidator         `protobuf:"bytes,12,opt,name=deck_validator,json=deckValidator,proto3" json:"deck_validator,omitempty"`
	Password             string                 `protobuf:"bytes,13,opt,name=password,proto3" json:"password,omitempty"`
	SpecTatorshipAllowed bool                   `protobuf:"varint,14,opt,name=spec_tatorship_allowed,json=specTatorshipAllowed,proto3" json:"spec_tatorship_allowed,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TableView) Reset() {
	*x = TableView{}
	mi := &file_mage_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableView) ProtoMessage() {}

func (x *TableView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableView.ProtoReflect.Descriptor instead.
func (*TableView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *TableView) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *TableView) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *TableView) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableView) GetControllerName() string {
	if x != nil {
		return x.ControllerName
	}
	return ""
}

func (x *TableView) GetTableStateText() string {
	if x != nil {
		return x.TableStateText
	}
	return ""
}

func (x *TableView) GetNumSeats() int32 {
	if x != nil {
		return x.NumSeats
	}
	return 0
}

func (x *TableView) GetSeats() []*SeatView {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *TableView) GetMatchOptions() *MatchOptions {
	if x != nil {
		return x.MatchOptions
	}
	return nil
}

func (x *TableView) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *TableView) GetIsTournament() bool {
	if x != nil {
		return x.IsTournament
	}
	return false
}

func (x *TableView) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *TableView) GetDeckValidator() *DeckValidator {
	if x != nil {
		return x.DeckValidator
	}
	return nil
}

func (x *TableView) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *TableView) GetSpecTatorshipAllowed() bool {
	if x != nil {
		return x.SpecTatorshipAllowed
	}
	return false
}

// SeatView represents a player seat at a table
type SeatView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatNumber    int32                  `protobuf:"varint,1,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PlayerType    string                 `protobuf:"bytes,3,opt,name=player_type,json=playerType,proto3" json:"player_type,omitempty"`
	Locked        bool                   `protobuf:"varint,4,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatView) Reset() {
	*x = SeatView{}
	mi := &file_mage_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatView) ProtoMessage() {}

func (x *SeatView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatView.ProtoReflect.Descriptor instead.
func (*SeatView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *SeatView) GetSeatNumber() int32 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

func (x *SeatView) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *SeatView) GetPlayerType() string {
	if x != nil {
		return x.PlayerType
	}
	return ""
}

func (x *SeatView) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

// MatchOptions defines match configuration
type MatchOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GameType             string                 `protobuf:"bytes,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	DeckType             string                 `protobuf:"bytes,3,opt,name=deck_type,json=deckType,proto3" json:"deck_type,omitempty"`
	Limited              bool                   `protobuf:"varint,4,opt,name=limited,proto3" json:"limited,omitempty"`
	WinsNeeded           int32                  `protobuf:"varint,5,opt,name=wins_needed,json=winsNeeded,proto3" json:"wins_needed,omitempty"`
	FreeMulligans        int32                  `protobuf:"varint,6,opt,name=free_mulligans,json=freeMulligans,proto3" json:"free_mulligans,omitempty"`
	TimeLimit            *MatchTimeLimit        `protobuf:"bytes,7,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	PriorityTime         int32                  `protobuf:"varint,8,opt,name=priority_time,json=priorityTime,proto3" json:"priority_time,omitempty"`
	Rated                bool                   `protobuf:"varint,9,opt,name=rated,proto3" json:"rated,omitempty"`
	Banlist              []string               `protobuf:"bytes,10,rep,name=banlist,proto3" json:"banlist,omitempty"`
	SkillLevel           string                 `protobuf:"bytes,11,opt,name=skill_level,json=skillLevel,proto3" json:"skill_level,omitempty"`
	RangeOfInfluence     bool                   `protobuf:"varint,12,opt,name=range_of_influence,json=rangeOfInfluence,proto3" json:"range_of_influence,omitempty"`
	PlaneChase           bool                   `protobuf:"varint,13,opt,name=planeChase,proto3" json:"planeChase,omitempty"`
	RollbackTurnsAllowed bool                   `protobuf:"varint,14,opt,name=rollback_turns_allowed,json=rollbackTurnsAllowed,proto3" json:"rollback_turns_allowed,omitempty"`
	EmbedDeckInSavedGame int32                  `protobuf:"varint,15,opt,name=embed_deck_in_saved_game,json=embedDeckInSavedGame,proto3" json:"embed_deck_in_saved_game,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MatchOptions) Reset() {
	*x = MatchOptions{}
	mi := &file_mage_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchOptions) ProtoMessage() {}

func (x *MatchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchOptions.ProtoReflect.Descriptor instead.
func (*MatchOptions) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *MatchOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MatchOptions) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *MatchOptions) GetDeckType() string {
	if x != nil {
		return x.DeckType
	}
	return ""
}

func (x *MatchOptions) GetLimited() bool {
	if x != nil {
		return x.Limited
	}
	return false
}

func (x *MatchOptions) GetWinsNeeded() int32 {
	if x != nil {
		return x.WinsNeeded
	}
	return 0
}

func (x *MatchOptions) GetFreeMulligans() int32 {
	if x != nil {
		return x.FreeMulligans
	}
	return 0
}

func (x *MatchOptions) GetTimeLimit() *MatchTimeLimit {
	if x != nil {
		return x.TimeLimit
	}
	return nil
}

func (x *MatchOptions) GetPriorityTime() int32 {
	if x != nil {
		return x.PriorityTime
	}
	return 0
}

func (x *MatchOptions) GetRated() bool {
	if x != nil {
		return x.Rated
	}
	return false
}

func (x *MatchOptions) GetBanlist() []string {
	if x != nil {
		return x.Banlist
	}
	return nil
}

func (x *MatchOptions) GetSkillLevel() string {
	if x != nil {
		return x.SkillLevel
	}
	return ""
}

func (x *MatchOptions) GetRangeOfInfluence() bool {
	if x != nil {
		return x.RangeOfInfluence
	}
	return false
}

func (x *MatchOptions) GetPlaneChase() bool {
	if x != nil {
		return x.PlaneChase
	}
	return false
}

func (x *MatchOptions) GetRollbackTurnsAllowed() bool {
	if x != nil {
		return x.RollbackTurnsAllowed
	}
	return false
}

func (x *MatchOptions) GetEmbedDeckInSavedGame() int32 {
	if x != nil {
		return x.EmbedDeckInSavedGame
	}
	return 0
}

// MatchTimeLimit defines time limits for matches
type MatchTimeLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Minutes       int32                  `protobuf:"varint,1,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchTimeLimit) Reset() {
	*x = MatchTimeLimit{}
	mi := &file_mage_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTimeLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTimeLimit) ProtoMessage() {}

func (x *MatchTimeLimit) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTimeLimit.ProtoReflect.Descriptor instead.
func (*MatchTimeLimit) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *MatchTimeLimit) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

// DeckValidator specifies deck validation rules
type DeckValidator struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinDeckSize     int32                  `protobuf:"varint,2,opt,name=min_deck_size,json=minDeckSize,proto3" json:"min_deck_size,omitempty"`
	MaxDeckSize     int32                  `protobuf:"varint,3,opt,name=max_deck_size,json=maxDeckSize,proto3" json:"max_deck_size,omitempty"`
	Singleton       bool                   `protobuf:"varint,4,opt,name=singleton,proto3" json:"singleton,omitempty"`
	LegalSets       []string               `protobuf:"bytes,5,rep,name=legal_sets,json=legalSets,proto3" json:"legal_sets,omitempty"`
	BannedCards     []string               `protobuf:"bytes,6,rep,name=banned_cards,json=bannedCards,proto3" json:"banned_cards,omitempty"`
	RestrictedCards []string               `protobuf:"bytes,7,rep,name=restricted_cards,json=restrictedCards,proto3" json:"restricted_cards,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeckValidator) Reset() {
	*x = DeckValidator{}
	mi := &file_mage_v1_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckValidator) ProtoMessage() {}

func (x *DeckValidator) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckValidator.ProtoReflect.Descriptor instead.
func (*DeckValidator) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{4}
}

func (x *DeckValidator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeckValidator) GetMinDeckSize() int32 {
	if x != nil {
		return x.MinDeckSize
	}
	return 0
}

func (x *DeckValidator) GetMaxDeckSize() int32 {
	if x != nil {
		return x.MaxDeckSize
	}
	return 0
}

func (x *DeckValidator) GetSingleton() bool {
	if x != nil {
		return x.Singleton
	}
	return false
}

func (x *DeckValidator) GetLegalSets() []string {
	if x != nil {
		return x.LegalSets
	}
	return nil
}

func (x *DeckValidator) GetBannedCards() []string {
	if x != nil {
		return x.BannedCards
	}
	return nil
}

func (x *DeckValidator) GetRestrictedCards() []string {
	if x != nil {
		return x.RestrictedCards
	}
	return nil
}

// GameView represents the current game state
type GameView struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GameId           string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Players          []*PlayerView          `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	ActivePlayerId   string                 `protobuf:"bytes,4,opt,name=active_player_id,json=activePlayerId,proto3" json:"active_player_id,omitempty"`
	PriorityPlayerId string                 `protobuf:"bytes,5,opt,name=priority_player_id,json=priorityPlayerId,proto3" json:"priority_player_id,omitempty"`
	Turn             int32                  `protobuf:"varint,6,opt,name=turn,proto3" json:"turn,omitempty"`
	Phase            string                 `protobuf:"bytes,7,opt,name=phase,proto3" json:"phase,omitempty"`
	Step             string                 `protobuf:"bytes,8,opt,name=step,proto3" json:"step,omitempty"`
	Messages         []*GameMessage         `protobuf:"bytes,9,rep,name=messages,proto3" json:"messages,omitempty"`
	Battlefield      []*CardView            `protobuf:"bytes,10,rep,name=battlefield,proto3" json:"battlefield,omitempty"`
	Stack            []*CardView            `protobuf:"bytes,11,rep,name=stack,proto3" json:"stack,omitempty"`
	Exile            []*CardView            `protobuf:"bytes,12,rep,name=exile,proto3" json:"exile,omitempty"`
	Command          []*CardView            `protobuf:"bytes,13,rep,name=command,proto3" json:"command,omitempty"`
	Revealed         []*RevealedView        `protobuf:"bytes,14,rep,name=revealed,proto3" json:"revealed,omitempty"`
	LookedAt         []*LookedAtView        `protobuf:"bytes,15,rep,name=looked_at,json=lookedAt,proto3" json:"looked_at,omitempty"`
	Combat           *CombatView            `protobuf:"bytes,16,opt,name=combat,proto3" json:"combat,omitempty"`
	Special          bool                   `protobuf:"varint,17,opt,name=special,proto3" json:"special,omitempty"`
	StartTime        *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameView) Reset() {
	*x = GameView{}
	mi := &file_mage_v1_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameView) ProtoMessage() {}

func (x *GameView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameView.ProtoReflect.Descriptor instead.
func (*GameView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{5}
}

func (x *GameView) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameView) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GameView) GetPlayers() []*PlayerView {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameView) GetActivePlayerId() string {
	if x != nil {
		return x.ActivePlayerId
	}
	return ""
}

func (x *GameView) GetPriorityPlayerId() string {
	if x != nil {
		return x.PriorityPlayerId
	}
	return ""
}

func (x *GameView) GetTurn() int32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *GameView) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *GameView) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *GameView) GetMessages() []*GameMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GameView) GetBattlefield() []*CardView {
	if x != nil {
		return x.Battlefield
	}
	return nil
}

func (x *GameView) GetStack() []*CardView {
	if x != nil {
		return x.Stack
	}
	return nil
}

func (x *GameView) GetExile() []*CardView {
	if x != nil {
		return x.Exile
	}
	return nil
}

func (x *GameView) GetCommand() []*CardView {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *GameView) GetRevealed() []*RevealedView {
	if x != nil {
		return x.Revealed
	}
	return nil
}

func (x *GameView) GetLookedAt() []*LookedAtView {
	if x != nil {
		return x.LookedAt
	}
	return nil
}

func (x *GameView) GetCombat() *CombatView {
	if x != nil {
		return x.Combat
	}
	return nil
}

func (x *GameView) GetSpecial() bool {
	if x != nil {
		return x.Special
	}
	return false
}

func (x *GameView) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// PlayerView represents a player's state
type PlayerView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Life          int32                  `protobuf:"varint,3,opt,name=life,proto3" json:"life,omitempty"`
	Poison        int32                  `protobuf:"varint,4,opt,name=poison,proto3" json:"poison,omitempty"`
	Energy        int32                  `protobuf:"varint,5,opt,name=energy,proto3" json:"energy,omitempty"`
	LibraryCount  int32                  `protobuf:"varint,6,opt,name=library_count,json=libraryCount,proto3" json:"library_count,omitempty"`
	HandCount     int32                  `protobuf:"varint,7,opt,name=hand_count,json=handCount,proto3" json:"hand_count,omitempty"`
	Hand          []*CardView            `protobuf:"bytes,8,rep,name=hand,proto3" json:"hand,omitempty"`
	Graveyard     []*CardView            `protobuf:"bytes,9,rep,name=graveyard,proto3" json:"graveyard,omitempty"`
	ManaPool      *ManaPoolView          `protobuf:"bytes,10,opt,name=mana_pool,json=manaPool,proto3" json:"mana_pool,omitempty"`
	HasPriority   bool                   `protobuf:"varint,11,opt,name=has_priority,json=hasPriority,proto3" json:"has_priority,omitempty"`
	Passed        bool                   `protobuf:"varint,12,opt,name=passed,proto3" json:"passed,omitempty"`
	StateOrdinal  int32                  `protobuf:"varint,13,opt,name=state_ordinal,json=stateOrdinal,proto3" json:"state_ordinal,omitempty"`
	Lost          bool                   `protobuf:"varint,14,opt,name=lost,proto3" json:"lost,omitempty"`
	Left          bool                   `protobuf:"varint,15,opt,name=left,proto3" json:"left,omitempty"`
	Wins          int32                  `protobuf:"varint,16,opt,name=wins,proto3" json:"wins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerView) Reset() {
	*x = PlayerView{}
	mi := &file_mage_v1_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerView) ProtoMessage() {}

func (x *PlayerView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerView.ProtoReflect.Descriptor instead.
func (*PlayerView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerView) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerView) GetLife() int32 {
	if x != nil {
		return x.Life
	}
	return 0
}

func (x *PlayerView) GetPoison() int32 {
	if x != nil {
		return x.Poison
	}
	return 0
}

func (x *PlayerView) GetEnergy() int32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *PlayerView) GetLibraryCount() int32 {
	if x != nil {
		return x.LibraryCount
	}
	return 0
}

func (x *PlayerView) GetHandCount() int32 {
	if x != nil {
		return x.HandCount
	}
	return 0
}

func (x *PlayerView) GetHand() []*CardView {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *PlayerView) GetGraveyard() []*CardView {
	if x != nil {
		return x.Graveyard
	}
	return nil
}

func (x *PlayerView) GetManaPool() *ManaPoolView {
	if x != nil {
		return x.ManaPool
	}
	return nil
}

func (x *PlayerView) GetHasPriority() bool {
	if x != nil {
		return x.HasPriority
	}
	return false
}

func (x *PlayerView) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *PlayerView) GetStateOrdinal() int32 {
	if x != nil {
		return x.StateOrdinal
	}
	return 0
}

func (x *PlayerView) GetLost() bool {
	if x != nil {
		return x.Lost
	}
	return false
}

func (x *PlayerView) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *PlayerView) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

// CardView represents a card
type CardView struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName      string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ManaCost         string                 `protobuf:"bytes,4,opt,name=mana_cost,json=manaCost,proto3" json:"mana_cost,omitempty"`
	Type             string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	SubTypes         string                 `protobuf:"bytes,6,opt,name=sub_types,json=subTypes,proto3" json:"sub_types,omitempty"`
	SuperTypes       string                 `protobuf:"bytes,7,opt,name=super_types,json=superTypes,proto3" json:"super_types,omitempty"`
	Color            string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	Power            string                 `protobuf:"bytes,9,opt,name=power,proto3" json:"power,omitempty"`
	Toughness        string                 `protobuf:"bytes,10,opt,name=toughness,proto3" json:"toughness,omitempty"`
	Loyalty          string                 `protobuf:"bytes,11,opt,name=loyalty,proto3" json:"loyalty,omitempty"`
	CardNumber       int32                  `protobuf:"varint,12,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	ExpansionSetCode string                 `protobuf:"bytes,13,opt,name=expansion_set_code,json=expansionSetCode,proto3" json:"expansion_set_code,omitempty"`
	Rarity           string                 `protobuf:"bytes,14,opt,name=rarity,proto3" json:"rarity,omitempty"`
	RulesText        string                 `protobuf:"bytes,15,opt,name=rules_text,json=rulesText,proto3" json:"rules_text,omitempty"`
	Abilities        []*AbilityView         `protobuf:"bytes,16,rep,name=abilities,proto3" json:"abilities,omitempty"`
	Tapped           bool                   `protobuf:"varint,17,opt,name=tapped,proto3" json:"tapped,omitempty"`
	Flipped          bool                   `protobuf:"varint,18,opt,name=flipped,proto3" json:"flipped,omitempty"`
	Transformed      bool                   `protobuf:"varint,19,opt,name=transformed,proto3" json:"transformed,omitempty"`
	FaceDown         bool                   `protobuf:"varint,20,opt,name=face_down,json=faceDown,proto3" json:"face_down,omitempty"`
	Zone             int32                  `protobuf:"varint,21,opt,name=zone,proto3" json:"zone,omitempty"`
	ControllerId     string                 `protobuf:"bytes,22,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	OwnerId          string                 `protobuf:"bytes,23,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Counters         []*CounterView         `protobuf:"bytes,24,rep,name=counters,proto3" json:"counters,omitempty"`
	AttachedTo       []string               `protobuf:"bytes,25,rep,name=attached_to,json=attachedTo,proto3" json:"attached_to,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CardView) Reset() {
	*x = CardView{}
	mi := &file_mage_v1_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardView) ProtoMessage() {}

func (x *CardView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardView.ProtoReflect.Descriptor instead.
func (*CardView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{7}
}

func (x *CardView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardView) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CardView) GetManaCost() string {
	if x != nil {
		return x.ManaCost
	}
	return ""
}

func (x *CardView) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CardView) GetSubTypes() string {
	if x != nil {
		return x.SubTypes
	}
	return ""
}

func (x *CardView) GetSuperTypes() string {
	if x != nil {
		return x.SuperTypes
	}
	return ""
}

func (x *CardView) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CardView) GetPower() string {
	if x != nil {
		return x.Power
	}
	return ""
}

func (x *CardView) GetToughness() string {
	if x != nil {
		return x.Toughness
	}
	return ""
}

func (x *CardView) GetLoyalty() string {
	if x != nil {
		return x.Loyalty
	}
	return ""
}

func (x *CardView) GetCardNumber() int32 {
	if x != nil {
		return x.CardNumber
	}
	return 0
}

func (x *CardView) GetExpansionSetCode() string {
	if x != nil {
		return x.ExpansionSetCode
	}
	return ""
}

func (x *CardView) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *CardView) GetRulesText() string {
	if x != nil {
		return x.RulesText
	}
	return ""
}

func (x *CardView) GetAbilities() []*AbilityView {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *CardView) GetTapped() bool {
	if x != nil {
		return x.Tapped
	}
	return false
}

func (x *CardView) GetFlipped() bool {
	if x != nil {
		return x.Flipped
	}
	return false
}

func (x *CardView) GetTransformed() bool {
	if x != nil {
		return x.Transformed
	}
	return false
}

func (x *CardView) GetFaceDown() bool {
	if x != nil {
		return x.FaceDown
	}
	return false
}

func (x *CardView) GetZone() int32 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *CardView) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *CardView) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CardView) GetCounters() []*CounterView {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *CardView) GetAttachedTo() []string {
	if x != nil {
		return x.AttachedTo
	}
	return nil
}

// AbilityView represents a card ability
type AbilityView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Rule          string                 `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbilityView) Reset() {
	*x = AbilityView{}
	mi := &file_mage_v1_models_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbilityView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityView) ProtoMessage() {}

func (x *AbilityView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityView.ProtoReflect.Descriptor instead.
func (*AbilityView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{8}
}

func (x *AbilityView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AbilityView) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AbilityView) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

// CounterView represents a counter on a card
type CounterView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterView) Reset() {
	*x = CounterView{}
	mi := &file_mage_v1_models_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterView) ProtoMessage() {}

func (x *CounterView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterView.ProtoReflect.Descriptor instead.
func (*CounterView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{9}
}

func (x *CounterView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CounterView) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ManaPoolView represents a player's mana pool
type ManaPoolView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	White         int32                  `protobuf:"varint,1,opt,name=white,proto3" json:"white,omitempty"`
	Blue          int32                  `protobuf:"varint,2,opt,name=blue,proto3" json:"blue,omitempty"`
	Black         int32                  `protobuf:"varint,3,opt,name=black,proto3" json:"black,omitempty"`
	Red           int32                  `protobuf:"varint,4,opt,name=red,proto3" json:"red,omitempty"`
	Green         int32                  `protobuf:"varint,5,opt,name=green,proto3" json:"green,omitempty"`
	Colorless     int32                  `protobuf:"varint,6,opt,name=colorless,proto3" json:"colorless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManaPoolView) Reset() {
	*x = ManaPoolView{}
	mi := &file_mage_v1_models_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManaPoolView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManaPoolView) ProtoMessage() {}

func (x *ManaPoolView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManaPoolView.ProtoReflect.Descriptor instead.
func (*ManaPoolView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{10}
}

func (x *ManaPoolView) GetWhite() int32 {
	if x != nil {
		return x.White
	}
	return 0
}

func (x *ManaPoolView) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *ManaPoolView) GetBlack() int32 {
	if x != nil {
		return x.Black
	}
	return 0
}

func (x *ManaPoolView) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *ManaPoolView) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *ManaPoolView) GetColorless() int32 {
	if x != nil {
		return x.Colorless
	}
	return 0
}

// GameMessage represents a message in the game log
type GameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_mage_v1_models_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{11}
}

func (x *GameMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GameMessage) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *GameMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

// CombatView represents combat state
type CombatView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttackingPlayerId string                 `protobuf:"bytes,1,opt,name=attacking_player_id,json=attackingPlayerId,proto3" json:"attacking_player_id,omitempty"`
	Groups            []*CombatGroupView     `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CombatView) Reset() {
	*x = CombatView{}
	mi := &file_mage_v1_models_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatView) ProtoMessage() {}

func (x *CombatView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatView.ProtoReflect.Descriptor instead.
func (*CombatView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{12}
}

func (x *CombatView) GetAttackingPlayerId() string {
	if x != nil {
		return x.AttackingPlayerId
	}
	return ""
}

func (x *CombatView) GetGroups() []*CombatGroupView {
	if x != nil {
		return x.Groups
	}
	return nil
}

// CombatGroupView represents a combat group
type CombatGroupView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Attackers         []string               `protobuf:"bytes,1,rep,name=attackers,proto3" json:"attackers,omitempty"`
	Blockers          []string               `protobuf:"bytes,2,rep,name=blockers,proto3" json:"blockers,omitempty"`
	DefendingPlayerId string                 `protobuf:"bytes,3,opt,name=defending_player_id,json=defendingPlayerId,proto3" json:"defending_player_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CombatGroupView) Reset() {
	*x = CombatGroupView{}
	mi := &file_mage_v1_models_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatGroupView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatGroupView) ProtoMessage() {}

func (x *CombatGroupView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatGroupView.ProtoReflect.Descriptor instead.
func (*CombatGroupView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{13}
}

func (x *CombatGroupView) GetAttackers() []string {
	if x != nil {
		return x.Attackers
	}
	return nil
}

func (x *CombatGroupView) GetBlockers() []string {
	if x != nil {
		return x.Blockers
	}
	return nil
}

func (x *CombatGroupView) GetDefendingPlayerId() string {
	if x != nil {
		return x.DefendingPlayerId
	}
	return ""
}

// RevealedView represents revealed cards
type RevealedView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cards         []*CardView            `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealedView) Reset() {
	*x = RevealedView{}
	mi := &file_mage_v1_models_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealedView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealedView) ProtoMessage() {}

func (x *RevealedView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealedView.ProtoReflect.Descriptor instead.
func (*RevealedView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{14}
}

func (x *RevealedView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RevealedView) GetCards() []*CardView {
	if x != nil {
		return x.Cards
	}
	return nil
}

// LookedAtView represents looked at cards
type LookedAtView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cards         []*CardView            `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookedAtView) Reset() {
	*x = LookedAtView{}
	mi := &file_mage_v1_models_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookedAtView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookedAtView) ProtoMessage() {}

func (x *LookedAtView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookedAtView.ProtoReflect.Descriptor instead.
func (*LookedAtView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{15}
}

func (x *LookedAtView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LookedAtView) GetCards() []*CardView {
	if x != nil {
		return x.Cards
	}
	return nil
}

// TournamentView represents a tournament
type TournamentView struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	TournamentId   string                  `protobuf:"bytes,1,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	TournamentName string                  `protobuf:"bytes,2,opt,name=tournament_name,json=tournamentName,proto3" json:"tournament_name,omitempty"`
	TournamentType string                  `protobuf:"bytes,3,opt,name=tournament_type,json=tournamentType,proto3" json:"tournament_type,omitempty"`
	State          string                  `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	NumPlayers     int32                   `protobuf:"varint,5,opt,name=num_players,json=numPlayers,proto3" json:"num_players,omitempty"`
	NumRounds      int32                   `protobuf:"varint,6,opt,name=num_rounds,json=numRounds,proto3" json:"num_rounds,omitempty"`
	CurrentRound   int32                   `protobuf:"varint,7,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	Players        []*TournamentPlayerView `protobuf:"bytes,8,rep,name=players,proto3" json:"players,omitempty"`
	Rounds         []*RoundView            `protobuf:"bytes,9,rep,name=rounds,proto3" json:"rounds,omitempty"`
	StartTime      *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TournamentView) Reset() {
	*x = TournamentView{}
	mi := &file_mage_v1_models_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentView) ProtoMessage() {}

func (x *TournamentView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentView.ProtoReflect.Descriptor instead.
func (*TournamentView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{16}
}

func (x *TournamentView) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *TournamentView) GetTournamentName() string {
	if x != nil {
		return x.TournamentName
	}
	return ""
}

func (x *TournamentView) GetTournamentType() string {
	if x != nil {
		return x.TournamentType
	}
	return ""
}

func (x *TournamentView) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TournamentView) GetNumPlayers() int32 {
	if x != nil {
		return x.NumPlayers
	}
	return 0
}

func (x *TournamentView) GetNumRounds() int32 {
	if x != nil {
		return x.NumRounds
	}
	return 0
}

func (x *TournamentView) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *TournamentView) GetPlayers() []*TournamentPlayerView {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *TournamentView) GetRounds() []*RoundView {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *TournamentView) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TournamentView) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// TournamentPlayerView represents a tournament participant
type TournamentPlayerView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Points        int32                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	Wins          int32                  `protobuf:"varint,3,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses        int32                  `protobuf:"varint,4,opt,name=losses,proto3" json:"losses,omitempty"`
	Draws         int32                  `protobuf:"varint,5,opt,name=draws,proto3" json:"draws,omitempty"`
	Eliminated    bool                   `protobuf:"varint,6,opt,name=eliminated,proto3" json:"eliminated,omitempty"`
	Quit          bool                   `protobuf:"varint,7,opt,name=quit,proto3" json:"quit,omitempty"`
	State         string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentPlayerView) Reset() {
	*x = TournamentPlayerView{}
	mi := &file_mage_v1_models_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentPlayerView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentPlayerView) ProtoMessage() {}

func (x *TournamentPlayerView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentPlayerView.ProtoReflect.Descriptor instead.
func (*TournamentPlayerView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{17}
}

func (x *TournamentPlayerView) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *TournamentPlayerView) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *TournamentPlayerView) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *TournamentPlayerView) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *TournamentPlayerView) GetDraws() int32 {
	if x != nil {
		return x.Draws
	}
	return 0
}

func (x *TournamentPlayerView) GetEliminated() bool {
	if x != nil {
		return x.Eliminated
	}
	return false
}

func (x *TournamentPlayerView) GetQuit() bool {
	if x != nil {
		return x.Quit
	}
	return false
}

func (x *TournamentPlayerView) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// RoundView represents a tournament round
type RoundView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber   int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Pairings      []*PairingView         `protobuf:"bytes,2,rep,name=pairings,proto3" json:"pairings,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundView) Reset() {
	*x = RoundView{}
	mi := &file_mage_v1_models_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundView) ProtoMessage() {}

func (x *RoundView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundView.ProtoReflect.Descriptor instead.
func (*RoundView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{18}
}

func (x *RoundView) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *RoundView) GetPairings() []*PairingView {
	if x != nil {
		return x.Pairings
	}
	return nil
}

func (x *RoundView) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// PairingView represents a match pairing
type PairingView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player1       string                 `protobuf:"bytes,1,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2       string                 `protobuf:"bytes,2,opt,name=player2,proto3" json:"player2,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Player1Wins   int32                  `protobuf:"varint,4,opt,name=player1_wins,json=player1Wins,proto3" json:"player1_wins,omitempty"`
	Player2Wins   int32                  `protobuf:"varint,5,opt,name=player2_wins,json=player2Wins,proto3" json:"player2_wins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingView) Reset() {
	*x = PairingView{}
	mi := &file_mage_v1_models_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingView) ProtoMessage() {}

func (x *PairingView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingView.ProtoReflect.Descriptor instead.
func (*PairingView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{19}
}

func (x *PairingView) GetPlayer1() string {
	if x != nil {
		return x.Player1
	}
	return ""
}

func (x *PairingView) GetPlayer2() string {
	if x != nil {
		return x.Player2
	}
	return ""
}

func (x *PairingView) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *PairingView) GetPlayer1Wins() int32 {
	if x != nil {
		return x.Player1Wins
	}
	return 0
}

func (x *PairingView) GetPlayer2Wins() int32 {
	if x != nil {
		return x.Player2Wins
	}
	return 0
}

// DraftPickView represents a draft pick state
type DraftPickView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       string                 `protobuf:"bytes,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	Booster       []*CardView            `protobuf:"bytes,2,rep,name=booster,proto3" json:"booster,omitempty"`
	Picks         []*CardView            `protobuf:"bytes,3,rep,name=picks,proto3" json:"picks,omitempty"`
	PickNumber    int32                  `protobuf:"varint,4,opt,name=pick_number,json=pickNumber,proto3" json:"pick_number,omitempty"`
	BoosterNumber int32                  `protobuf:"varint,5,opt,name=booster_number,json=boosterNumber,proto3" json:"booster_number,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftPickView) Reset() {
	*x = DraftPickView{}
	mi := &file_mage_v1_models_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftPickView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftPickView) ProtoMessage() {}

func (x *DraftPickView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftPickView.ProtoReflect.Descriptor instead.
func (*DraftPickView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{20}
}

func (x *DraftPickView) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

func (x *DraftPickView) GetBooster() []*CardView {
	if x != nil {
		return x.Booster
	}
	return nil
}

func (x *DraftPickView) GetPicks() []*CardView {
	if x != nil {
		return x.Picks
	}
	return nil
}

func (x *DraftPickView) GetPickNumber() int32 {
	if x != nil {
		return x.PickNumber
	}
	return 0
}

func (x *DraftPickView) GetBoosterNumber() int32 {
	if x != nil {
		return x.BoosterNumber
	}
	return 0
}

func (x *DraftPickView) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UserView represents user information
type UserView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserName          string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	State             string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	MatchHistory      string                 `protobuf:"bytes,3,opt,name=match_history,json=matchHistory,proto3" json:"match_history,omitempty"`
	TournamentHistory string                 `protobuf:"bytes,4,opt,name=tournament_history,json=tournamentHistory,proto3" json:"tournament_history,omitempty"`
	Stats             *UserStatsView         `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	ConnectedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	Admin             bool                   `protobuf:"varint,7,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserView) Reset() {
	*x = UserView{}
	mi := &file_mage_v1_models_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserView) ProtoMessage() {}

func (x *UserView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserView.ProtoReflect.Descriptor instead.
func (*UserView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{21}
}

func (x *UserView) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserView) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UserView) GetMatchHistory() string {
	if x != nil {
		return x.MatchHistory
	}
	return ""
}

func (x *UserView) GetTournamentHistory() string {
	if x != nil {
		return x.TournamentHistory
	}
	return ""
}

func (x *UserView) GetStats() *UserStatsView {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *UserView) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *UserView) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

// UserStatsView represents user statistics
type UserStatsView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Matches        int32                  `protobuf:"varint,1,opt,name=matches,proto3" json:"matches,omitempty"`
	Tournaments    int32                  `protobuf:"varint,2,opt,name=tournaments,proto3" json:"tournaments,omitempty"`
	Wins           int32                  `protobuf:"varint,3,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses         int32                  `protobuf:"varint,4,opt,name=losses,proto3" json:"losses,omitempty"`
	Rating         float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	TourneysWon    int32                  `protobuf:"varint,6,opt,name=tourneys_won,json=tourneysWon,proto3" json:"tourneys_won,omitempty"`
	TourneysSecond int32                  `protobuf:"varint,7,opt,name=tourneys_second,json=tourneysSecond,proto3" json:"tourneys_second,omitempty"`
	QuitRatio      float64                `protobuf:"fixed64,8,opt,name=quit_ratio,json=quitRatio,proto3" json:"quit_ratio,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserStatsView) Reset() {
	*x = UserStatsView{}
	mi := &file_mage_v1_models_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsView) ProtoMessage() {}

func (x *UserStatsView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsView.ProtoReflect.Descriptor instead.
func (*UserStatsView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{22}
}

func (x *UserStatsView) GetMatches() int32 {
	if x != nil {
		return x.Matches
	}
	return 0
}

func (x *UserStatsView) GetTournaments() int32 {
	if x != nil {
		return x.Tournaments
	}
	return 0
}

func (x *UserStatsView) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *UserStatsView) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *UserStatsView) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UserStatsView) GetTourneysWon() int32 {
	if x != nil {
		return x.TourneysWon
	}
	return 0
}

func (x *UserStatsView) GetTourneysSecond() int32 {
	if x != nil {
		return x.TourneysSecond
	}
	return 0
}

func (x *UserStatsView) GetQuitRatio() float64 {
	if x != nil {
		return x.QuitRatio
	}
	return 0
}

// ChatMessage represents a chat message
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Color         MessageColor           `protobuf:"varint,4,opt,name=color,proto3,enum=mage.v1.MessageColor" json:"color,omitempty"`
	MessageType   MessageType            `protobuf:"varint,5,opt,name=message_type,json=messageType,proto3,enum=mage.v1.MessageType" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_mage_v1_models_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{23}
}

func (x *ChatMessage) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ChatMessage) GetColor() MessageColor {
	if x != nil {
		return x.Color
	}
	return MessageColor_MESSAGE_COLOR_UNSPECIFIED
}

func (x *ChatMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

// ServerState represents server information
type ServerState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActivePlayers     int32                  `protobuf:"varint,1,opt,name=active_players,json=activePlayers,proto3" json:"active_players,omitempty"`
	ActiveGames       int32                  `protobuf:"varint,2,opt,name=active_games,json=activeGames,proto3" json:"active_games,omitempty"`
	ActiveTournaments int32                  `protobuf:"varint,3,opt,name=active_tournaments,json=activeTournaments,proto3" json:"active_tournaments,omitempty"`
	ActiveTables      int32                  `protobuf:"varint,4,opt,name=active_tables,json=activeTables,proto3" json:"active_tables,omitempty"`
	NumberOfThreads   int32                  `protobuf:"varint,5,opt,name=number_of_threads,json=numberOfThreads,proto3" json:"number_of_threads,omitempty"`
	ServerVersion     string                 `protobuf:"bytes,6,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerTime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerState) Reset() {
	*x = ServerState{}
	mi := &file_mage_v1_models_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerState) ProtoMessage() {}

func (x *ServerState) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerState.ProtoReflect.Descriptor instead.
func (*ServerState) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{24}
}

func (x *ServerState) GetActivePlayers() int32 {
	if x != nil {
		return x.ActivePlayers
	}
	return 0
}

func (x *ServerState) GetActiveGames() int32 {
	if x != nil {
		return x.ActiveGames
	}
	return 0
}

func (x *ServerState) GetActiveTournaments() int32 {
	if x != nil {
		return x.ActiveTournaments
	}
	return 0
}

func (x *ServerState) GetActiveTables() int32 {
	if x != nil {
		return x.ActiveTables
	}
	return 0
}

func (x *ServerState) GetNumberOfThreads() int32 {
	if x != nil {
		return x.NumberOfThreads
	}
	return 0
}

func (x *ServerState) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *ServerState) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// MatchQueueView represents a match queue entry
type MatchQueueView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MatchName      string                 `protobuf:"bytes,1,opt,name=match_name,json=matchName,proto3" json:"match_name,omitempty"`
	MatchOptions   *MatchOptions          `protobuf:"bytes,2,opt,name=match_options,json=matchOptions,proto3" json:"match_options,omitempty"`
	PlayersWaiting int32                  `protobuf:"varint,3,opt,name=players_waiting,json=playersWaiting,proto3" json:"players_waiting,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchQueueView) Reset() {
	*x = MatchQueueView{}
	mi := &file_mage_v1_models_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchQueueView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQueueView) ProtoMessage() {}

func (x *MatchQueueView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_models_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQueueView.ProtoReflect.Descriptor instead.
func (*MatchQueueView) Descriptor() ([]byte, []int) {
	return file_mage_v1_models_proto_rawDescGZIP(), []int{25}
}

func (x *MatchQueueView) GetMatchName() string {
	if x != nil {
		return x.MatchName
	}
	return ""
}

func (x *MatchQueueView) GetMatchOptions() *MatchOptions {
	if x != nil {
		return x.MatchOptions
	}
	return nil
}

func (x *MatchQueueView) GetPlayersWaiting() int32 {
	if x != nil {
		return x.PlayersWaiting
	}
	return 0
}

var File_mage_v1_models_proto protoreflect.FileDescriptor

const file_mage_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x14mage/v1/models.proto\x12\amage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x04\n" +
	"\tTableView\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x1b\n" +
	"\tgame_type\x18\x02 \x01(\tR\bgameType\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\x12'\n" +
	"\x0fcontroller_name\x18\x04 \x01(\tR\x0econtrollerName\x12(\n" +
	"\x10table_state_text\x18\x05 \x01(\tR\x0etableStateText\x12\x1b\n" +
	"\tnum_seats\x18\x06 \x01(\x05R\bnumSeats\x12'\n" +
	"\x05seats\x18\a \x03(\v2\x11.mage.v1.SeatViewR\x05seats\x12:\n" +
	"\rmatch_options\x18\b \x01(\v2\x15.mage.v1.MatchOptionsR\fmatchOptions\x12;\n" +
	"\vcreate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12#\n" +
	"\ris_tournament\x18\n" +
	" \x01(\bR\fisTournament\x12#\n" +
	"\rtournament_id\x18\v \x01(\tR\ftournamentId\x12=\n" +
	"\x0edeck_validator\x18\f \x01(\v2\x16.mage.v1.DeckValidatorR\rdeckValidator\x12\x1a\n" +
	"\bpassword\x18\r \x01(\tR\bpassword\x124\n" +
	"\x16spec_tatorship_allowed\x18\x0e \x01(\bR\x14specTatorshipAllowed\"\x85\x01\n" +
	"\bSeatView\x12\x1f\n" +
	"\vseat_number\x18\x01 \x01(\x05R\n" +
	"seatNumber\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1f\n" +
	"\vplayer_type\x18\x03 \x01(\tR\n" +
	"playerType\x12\x16\n" +
	"\x06locked\x18\x04 \x01(\bR\x06locked\"\xa8\x04\n" +
	"\fMatchOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tgame_type\x18\x02 \x01(\tR\bgameType\x12\x1b\n" +
	"\tdeck_type\x18\x03 \x01(\tR\bdeckType\x12\x18\n" +
	"\alimited\x18\x04 \x01(\bR\alimited\x12\x1f\n" +
	"\vwins_needed\x18\x05 \x01(\x05R\n" +
	"winsNeeded\x12%\n" +
	"\x0efree_mulligans\x18\x06 \x01(\x05R\rfreeMulligans\x126\n" +
	"\n" +
	"time_limit\x18\a \x01(\v2\x17.mage.v1.MatchTimeLimitR\ttimeLimit\x12#\n" +
	"\rpriority_time\x18\b \x01(\x05R\fpriorityTime\x12\x14\n" +
	"\x05rated\x18\t \x01(\bR\x05rated\x12\x18\n" +
	"\abanlist\x18\n" +
	" \x03(\tR\abanlist\x12\x1f\n" +
	"\vskill_level\x18\v \x01(\tR\n" +
	"skillLevel\x12,\n" +
	"\x12range_of_influence\x18\f \x01(\bR\x10rangeOfInfluence\x12\x1e\n" +
	"\n" +
	"planeChase\x18\r \x01(\bR\n" +
	"planeChase\x124\n" +
	"\x16rollback_turns_allowed\x18\x0e \x01(\bR\x14rollbackTurnsAllowed\x126\n" +
	"\x18embed_deck_in_saved_game\x18\x0f \x01(\x05R\x14embedDeckInSavedGame\"*\n" +
	"\x0eMatchTimeLimit\x12\x18\n" +
	"\aminutes\x18\x01 \x01(\x05R\aminutes\"\xf6\x01\n" +
	"\rDeckValidator\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\rmin_deck_size\x18\x02 \x01(\x05R\vminDeckSize\x12\"\n" +
	"\rmax_deck_size\x18\x03 \x01(\x05R\vmaxDeckSize\x12\x1c\n" +
	"\tsingleton\x18\x04 \x01(\bR\tsingleton\x12\x1d\n" +
	"\n" +
	"legal_sets\x18\x05 \x03(\tR\tlegalSets\x12!\n" +
	"\fbanned_cards\x18\x06 \x03(\tR\vbannedCards\x12)\n" +
	"\x10restricted_cards\x18\a \x03(\tR\x0frestrictedCards\"\xcd\x05\n" +
	"\bGameView\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12-\n" +
	"\aplayers\x18\x03 \x03(\v2\x13.mage.v1.PlayerViewR\aplayers\x12(\n" +
	"\x10active_player_id\x18\x04 \x01(\tR\x0eactivePlayerId\x12,\n" +
	"\x12priority_player_id\x18\x05 \x01(\tR\x10priorityPlayerId\x12\x12\n" +
	"\x04turn\x18\x06 \x01(\x05R\x04turn\x12\x14\n" +
	"\x05phase\x18\a \x01(\tR\x05phase\x12\x12\n" +
	"\x04step\x18\b \x01(\tR\x04step\x120\n" +
	"\bmessages\x18\t \x03(\v2\x14.mage.v1.GameMessageR\bmessages\x123\n" +
	"\vbattlefield\x18\n" +
	" \x03(\v2\x11.mage.v1.CardViewR\vbattlefield\x12'\n" +
	"\x05stack\x18\v \x03(\v2\x11.mage.v1.CardViewR\x05stack\x12'\n" +
	"\x05exile\x18\f \x03(\v2\x11.mage.v1.CardViewR\x05exile\x12+\n" +
	"\acommand\x18\r \x03(\v2\x11.mage.v1.CardViewR\acommand\x121\n" +
	"\brevealed\x18\x0e \x03(\v2\x15.mage.v1.RevealedViewR\brevealed\x122\n" +
	"\tlooked_at\x18\x0f \x03(\v2\x15.mage.v1.LookedAtViewR\blookedAt\x12+\n" +
	"\x06combat\x18\x10 \x01(\v2\x13.mage.v1.CombatViewR\x06combat\x12\x18\n" +
	"\aspecial\x18\x11 \x01(\bR\aspecial\x129\n" +
	"\n" +
	"start_time\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"\xed\x03\n" +
	"\n" +
	"PlayerView\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04life\x18\x03 \x01(\x05R\x04life\x12\x16\n" +
	"\x06poison\x18\x04 \x01(\x05R\x06poison\x12\x16\n" +
	"\x06energy\x18\x05 \x01(\x05R\x06energy\x12#\n" +
	"\rlibrary_count\x18\x06 \x01(\x05R\flibraryCount\x12\x1d\n" +
	"\n" +
	"hand_count\x18\a \x01(\x05R\thandCount\x12%\n" +
	"\x04hand\x18\b \x03(\v2\x11.mage.v1.CardViewR\x04hand\x12/\n" +
	"\tgraveyard\x18\t \x03(\v2\x11.mage.v1.CardViewR\tgraveyard\x122\n" +
	"\tmana_pool\x18\n" +
	" \x01(\v2\x15.mage.v1.ManaPoolViewR\bmanaPool\x12!\n" +
	"\fhas_priority\x18\v \x01(\bR\vhasPriority\x12\x16\n" +
	"\x06passed\x18\f \x01(\bR\x06passed\x12#\n" +
	"\rstate_ordinal\x18\r \x01(\x05R\fstateOrdinal\x12\x12\n" +
	"\x04lost\x18\x0e \x01(\bR\x04lost\x12\x12\n" +
	"\x04left\x18\x0f \x01(\bR\x04left\x12\x12\n" +
	"\x04wins\x18\x10 \x01(\x05R\x04wins\"\xf6\x05\n" +
	"\bCardView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tmana_cost\x18\x04 \x01(\tR\bmanaCost\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1b\n" +
	"\tsub_types\x18\x06 \x01(\tR\bsubTypes\x12\x1f\n" +
	"\vsuper_types\x18\a \x01(\tR\n" +
	"superTypes\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x14\n" +
	"\x05power\x18\t \x01(\tR\x05power\x12\x1c\n" +
	"\ttoughness\x18\n" +
	" \x01(\tR\ttoughness\x12\x18\n" +
	"\aloyalty\x18\v \x01(\tR\aloyalty\x12\x1f\n" +
	"\vcard_number\x18\f \x01(\x05R\n" +
	"cardNumber\x12,\n" +
	"\x12expansion_set_code\x18\r \x01(\tR\x10expansionSetCode\x12\x16\n" +
	"\x06rarity\x18\x0e \x01(\tR\x06rarity\x12\x1d\n" +
	"\n" +
	"rules_text\x18\x0f \x01(\tR\trulesText\x122\n" +
	"\tabilities\x18\x10 \x03(\v2\x14.mage.v1.AbilityViewR\tabilities\x12\x16\n" +
	"\x06tapped\x18\x11 \x01(\bR\x06tapped\x12\x18\n" +
	"\aflipped\x18\x12 \x01(\bR\aflipped\x12 \n" +
	"\vtransformed\x18\x13 \x01(\bR\vtransformed\x12\x1b\n" +
	"\tface_down\x18\x14 \x01(\bR\bfaceDown\x12\x12\n" +
	"\x04zone\x18\x15 \x01(\x05R\x04zone\x12#\n" +
	"\rcontroller_id\x18\x16 \x01(\tR\fcontrollerId\x12\x19\n" +
	"\bowner_id\x18\x17 \x01(\tR\aownerId\x120\n" +
	"\bcounters\x18\x18 \x03(\v2\x14.mage.v1.CounterViewR\bcounters\x12\x1f\n" +
	"\vattached_to\x18\x19 \x03(\tR\n" +
	"attachedTo\"E\n" +
	"\vAbilityView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\"7\n" +
	"\vCounterView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x94\x01\n" +
	"\fManaPoolView\x12\x14\n" +
	"\x05white\x18\x01 \x01(\x05R\x05white\x12\x12\n" +
	"\x04blue\x18\x02 \x01(\x05R\x04blue\x12\x14\n" +
	"\x05black\x18\x03 \x01(\x05R\x05black\x12\x10\n" +
	"\x03red\x18\x04 \x01(\x05R\x03red\x12\x14\n" +
	"\x05green\x18\x05 \x01(\x05R\x05green\x12\x1c\n" +
	"\tcolorless\x18\x06 \x01(\x05R\tcolorless\"w\n" +
	"\vGameMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"n\n" +
	"\n" +
	"CombatView\x12.\n" +
	"\x13attacking_player_id\x18\x01 \x01(\tR\x11attackingPlayerId\x120\n" +
	"\x06groups\x18\x02 \x03(\v2\x18.mage.v1.CombatGroupViewR\x06groups\"{\n" +
	"\x0fCombatGroupView\x12\x1c\n" +
	"\tattackers\x18\x01 \x03(\tR\tattackers\x12\x1a\n" +
	"\bblockers\x18\x02 \x03(\tR\bblockers\x12.\n" +
	"\x13defending_player_id\x18\x03 \x01(\tR\x11defendingPlayerId\"K\n" +
	"\fRevealedView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x05cards\x18\x02 \x03(\v2\x11.mage.v1.CardViewR\x05cards\"K\n" +
	"\fLookedAtView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x05cards\x18\x02 \x03(\v2\x11.mage.v1.CardViewR\x05cards\"\xd9\x03\n" +
	"\x0eTournamentView\x12#\n" +
	"\rtournament_id\x18\x01 \x01(\tR\ftournamentId\x12'\n" +
	"\x0ftournament_name\x18\x02 \x01(\tR\x0etournamentName\x12'\n" +
	"\x0ftournament_type\x18\x03 \x01(\tR\x0etournamentType\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1f\n" +
	"\vnum_players\x18\x05 \x01(\x05R\n" +
	"numPlayers\x12\x1d\n" +
	"\n" +
	"num_rounds\x18\x06 \x01(\x05R\tnumRounds\x12#\n" +
	"\rcurrent_round\x18\a \x01(\x05R\fcurrentRound\x127\n" +
	"\aplayers\x18\b \x03(\v2\x1d.mage.v1.TournamentPlayerViewR\aplayers\x12*\n" +
	"\x06rounds\x18\t \x03(\v2\x12.mage.v1.RoundViewR\x06rounds\x129\n" +
	"\n" +
	"start_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xdb\x01\n" +
	"\x14TournamentPlayerView\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x05R\x06points\x12\x12\n" +
	"\x04wins\x18\x03 \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\x04 \x01(\x05R\x06losses\x12\x14\n" +
	"\x05draws\x18\x05 \x01(\x05R\x05draws\x12\x1e\n" +
	"\n" +
	"eliminated\x18\x06 \x01(\bR\n" +
	"eliminated\x12\x12\n" +
	"\x04quit\x18\a \x01(\bR\x04quit\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\"v\n" +
	"\tRoundView\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x120\n" +
	"\bpairings\x18\x02 \x03(\v2\x14.mage.v1.PairingViewR\bpairings\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"\xa2\x01\n" +
	"\vPairingView\x12\x18\n" +
	"\aplayer1\x18\x01 \x01(\tR\aplayer1\x12\x18\n" +
	"\aplayer2\x18\x02 \x01(\tR\aplayer2\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\x12!\n" +
	"\fplayer1_wins\x18\x04 \x01(\x05R\vplayer1Wins\x12!\n" +
	"\fplayer2_wins\x18\x05 \x01(\x05R\vplayer2Wins\"\xe2\x01\n" +
	"\rDraftPickView\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\tR\adraftId\x12+\n" +
	"\abooster\x18\x02 \x03(\v2\x11.mage.v1.CardViewR\abooster\x12'\n" +
	"\x05picks\x18\x03 \x03(\v2\x11.mage.v1.CardViewR\x05picks\x12\x1f\n" +
	"\vpick_number\x18\x04 \x01(\x05R\n" +
	"pickNumber\x12%\n" +
	"\x0ebooster_number\x18\x05 \x01(\x05R\rboosterNumber\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x94\x02\n" +
	"\bUserView\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12#\n" +
	"\rmatch_history\x18\x03 \x01(\tR\fmatchHistory\x12-\n" +
	"\x12tournament_history\x18\x04 \x01(\tR\x11tournamentHistory\x12,\n" +
	"\x05stats\x18\x05 \x01(\v2\x16.mage.v1.UserStatsViewR\x05stats\x12=\n" +
	"\fconnected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12\x14\n" +
	"\x05admin\x18\a \x01(\bR\x05admin\"\xfa\x01\n" +
	"\rUserStatsView\x12\x18\n" +
	"\amatches\x18\x01 \x01(\x05R\amatches\x12 \n" +
	"\vtournaments\x18\x02 \x01(\x05R\vtournaments\x12\x12\n" +
	"\x04wins\x18\x03 \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\x04 \x01(\x05R\x06losses\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\x12!\n" +
	"\ftourneys_won\x18\x06 \x01(\x05R\vtourneysWon\x12'\n" +
	"\x0ftourneys_second\x18\a \x01(\x05R\x0etourneysSecond\x12\x1d\n" +
	"\n" +
	"quit_ratio\x18\b \x01(\x01R\tquitRatio\"\xda\x01\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12+\n" +
	"\x05color\x18\x04 \x01(\x0e2\x15.mage.v1.MessageColorR\x05color\x127\n" +
	"\fmessage_type\x18\x05 \x01(\x0e2\x14.mage.v1.MessageTypeR\vmessageType\"\xbb\x02\n" +
	"\vServerState\x12%\n" +
	"\x0eactive_players\x18\x01 \x01(\x05R\ractivePlayers\x12!\n" +
	"\factive_games\x18\x02 \x01(\x05R\vactiveGames\x12-\n" +
	"\x12active_tournaments\x18\x03 \x01(\x05R\x11activeTournaments\x12#\n" +
	"\ractive_tables\x18\x04 \x01(\x05R\factiveTables\x12*\n" +
	"\x11number_of_threads\x18\x05 \x01(\x05R\x0fnumberOfThreads\x12%\n" +
	"\x0eserver_version\x18\x06 \x01(\tR\rserverVersion\x12;\n" +
	"\vserver_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\x94\x01\n" +
	"\x0eMatchQueueView\x12\x1d\n" +
	"\n" +
	"match_name\x18\x01 \x01(\tR\tmatchName\x12:\n" +
	"\rmatch_options\x18\x02 \x01(\v2\x15.mage.v1.MatchOptionsR\fmatchOptions\x12'\n" +
	"\x0fplayers_waiting\x18\x03 \x01(\x05R\x0eplayersWaiting*n\n" +
	"\fMessageColor\x12\x1d\n" +
	"\x19MESSAGE_COLOR_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BLACK\x10\x01\x12\t\n" +
	"\x05GREEN\x10\x02\x12\n" +
	"\n" +
	"\x06ORANGE\x10\x03\x12\b\n" +
	"\x04BLUE\x10\x04\x12\a\n" +
	"\x03RED\x10\x05\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x06*]\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TALK\x10\x01\x12\v\n" +
	"\aWHISPER\x10\x02\x12\n" +
	"\n" +
	"\x06STATUS\x10\x03\x12\r\n" +
	"\tUSER_INFO\x10\x04B6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var (
	file_mage_v1_models_proto_rawDescOnce sync.Once
	file_mage_v1_models_proto_rawDescData []byte
)

func file_mage_v1_models_proto_rawDescGZIP() []byte {
	file_mage_v1_models_proto_rawDescOnce.Do(func() {
		file_mage_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_v1_models_proto_rawDesc), len(file_mage_v1_models_proto_rawDesc)))
	})
	return file_mage_v1_models_proto_rawDescData
}

var file_mage_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mage_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_mage_v1_models_proto_goTypes = []any{
	(MessageColor)(0),             // 0: mage.v1.MessageColor
	(MessageType)(0),              // 1: mage.v1.MessageType
	(*TableView)(nil),             // 2: mage.v1.TableView
	(*SeatView)(nil),              // 3: mage.v1.SeatView
	(*MatchOptions)(nil),          // 4: mage.v1.MatchOptions
	(*MatchTimeLimit)(nil),        // 5: mage.v1.MatchTimeLimit
	(*DeckValidator)(nil),         // 6: mage.v1.DeckValidator
	(*GameView)(nil),              // 7: mage.v1.GameView
	(*PlayerView)(nil),            // 8: mage.v1.PlayerView
	(*CardView)(nil),              // 9: mage.v1.CardView
	(*AbilityView)(nil),           // 10: mage.v1.AbilityView
	(*CounterView)(nil),           // 11: mage.v1.CounterView
	(*ManaPoolView)(nil),          // 12: mage.v1.ManaPoolView
	(*GameMessage)(nil),           // 13: mage.v1.GameMessage
	(*CombatView)(nil),            // 14: mage.v1.CombatView
	(*CombatGroupView)(nil),       // 15: mage.v1.CombatGroupView
	(*RevealedView)(nil),          // 16: mage.v1.RevealedView
	(*LookedAtView)(nil),          // 17: mage.v1.LookedAtView
	(*TournamentView)(nil),        // 18: mage.v1.TournamentView
	(*TournamentPlayerView)(nil),  // 19: mage.v1.TournamentPlayerView
	(*RoundView)(nil),             // 20: mage.v1.RoundView
	(*PairingView)(nil),           // 21: mage.v1.PairingView
	(*DraftPickView)(nil),         // 22: mage.v1.DraftPickView
	(*UserView)(nil),              // 23: mage.v1.UserView
	(*UserStatsView)(nil),         // 24: mage.v1.UserStatsView
	(*ChatMessage)(nil),           // 25: mage.v1.ChatMessage
	(*ServerState)(nil),           // 26: mage.v1.ServerState
	(*MatchQueueView)(nil),        // 27: mage.v1.MatchQueueView
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
}
var file_mage_v1_models_proto_depIdxs = []int32{
	3,  // 0: mage.v1.TableView.seats:type_name -> mage.v1.SeatView
	4,  // 1: mage.v1.TableView.match_options:type_name -> mage.v1.MatchOptions
	28, // 2: mage.v1.TableView.create_time:type_name -> google.protobuf.Timestamp
	6,  // 3: mage.v1.TableView.deck_validator:type_name -> mage.v1.DeckValidator
	5,  // 4: mage.v1.MatchOptions.time_limit:type_name -> mage.v1.MatchTimeLimit
	8,  // 5: mage.v1.GameView.players:type_name -> mage.v1.PlayerView
	13, // 6: mage.v1.GameView.messages:type_name -> mage.v1.GameMessage
	9,  // 7: mage.v1.GameView.battlefield:type_name -> mage.v1.CardView
	9,  // 8: mage.v1.GameView.stack:type_name -> mage.v1.CardView
	9,  // 9: mage.v1.GameView.exile:type_name -> mage.v1.CardView
	9,  // 10: mage.v1.GameView.command:type_name -> mage.v1.CardView
	16, // 11: mage.v1.GameView.revealed:type_name -> mage.v1.RevealedView
	17, // 12: mage.v1.GameView.looked_at:type_name -> mage.v1.LookedAtView
	14, // 13: mage.v1.GameView.combat:type_name -> mage.v1.CombatView
	28, // 14: mage.v1.GameView.start_time:type_name -> google.protobuf.Timestamp
	9,  // 15: mage.v1.PlayerView.hand:type_name -> mage.v1.CardView
	9,  // 16: mage.v1.PlayerView.graveyard:type_name -> mage.v1.CardView
	12, // 17: mage.v1.PlayerView.mana_pool:type_name -> mage.v1.ManaPoolView
	10, // 18: mage.v1.CardView.abilities:type_name -> mage.v1.AbilityView
	11, // 19: mage.v1.CardView.counters:type_name -> mage.v1.CounterView
	28, // 20: mage.v1.GameMessage.time:type_name -> google.protobuf.Timestamp
	15, // 21: mage.v1.CombatView.groups:type_name -> mage.v1.CombatGroupView
	9,  // 22: mage.v1.RevealedView.cards:type_name -> mage.v1.CardView
	9,  // 23: mage.v1.LookedAtView.cards:type_name -> mage.v1.CardView
	19, // 24: mage.v1.TournamentView.players:type_name -> mage.v1.TournamentPlayerView
	20, // 25: mage.v1.TournamentView.rounds:type_name -> mage.v1.RoundView
	28, // 26: mage.v1.TournamentView.start_time:type_name -> google.protobuf.Timestamp
	28, // 27: mage.v1.TournamentView.end_time:type_name -> google.protobuf.Timestamp
	21, // 28: mage.v1.RoundView.pairings:type_name -> mage.v1.PairingView
	9,  // 29: mage.v1.DraftPickView.booster:type_name -> mage.v1.CardView
	9,  // 30: mage.v1.DraftPickView.picks:type_name -> mage.v1.CardView
	24, // 31: mage.v1.UserView.stats:type_name -> mage.v1.UserStatsView
	28, // 32: mage.v1.UserView.connected_at:type_name -> google.protobuf.Timestamp
	28, // 33: mage.v1.ChatMessage.time:type_name -> google.protobuf.Timestamp
	0,  // 34: mage.v1.ChatMessage.color:type_name -> mage.v1.MessageColor
	1,  // 35: mage.v1.ChatMessage.message_type:type_name -> mage.v1.MessageType
	28, // 36: mage.v1.ServerState.server_time:type_name -> google.protobuf.Timestamp
	4,  // 37: mage.v1.MatchQueueView.match_options:type_name -> mage.v1.MatchOptions
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_mage_v1_models_proto_init() }
func file_mage_v1_models_proto_init() {
	if File_mage_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_models_proto_rawDesc), len(file_mage_v1_models_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_v1_models_proto_goTypes,
		DependencyIndexes: file_mage_v1_models_proto_depIdxs,
		EnumInfos:         file_mage_v1_models_proto_enumTypes,
		MessageInfos:      file_mage_v1_models_proto_msgTypes,
	}.Build()
	File_mage_v1_models_proto = out.File
	file_mage_v1_models_proto_goTypes = nil
	file_mage_v1_models_proto_depIdxs = nil
}
