// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/room.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerGetMainRoomIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetMainRoomIdRequest) Reset() {
	*x = ServerGetMainRoomIdRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetMainRoomIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetMainRoomIdRequest) ProtoMessage() {}

func (x *ServerGetMainRoomIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetMainRoomIdRequest.ProtoReflect.Descriptor instead.
func (*ServerGetMainRoomIdRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *ServerGetMainRoomIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ServerGetMainRoomIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetMainRoomIdResponse) Reset() {
	*x = ServerGetMainRoomIdResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetMainRoomIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetMainRoomIdResponse) ProtoMessage() {}

func (x *ServerGetMainRoomIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetMainRoomIdResponse.ProtoReflect.Descriptor instead.
func (*ServerGetMainRoomIdResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *ServerGetMainRoomIdResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomGetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetUsersRequest) Reset() {
	*x = RoomGetUsersRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetUsersRequest) ProtoMessage() {}

func (x *RoomGetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetUsersRequest.ProtoReflect.Descriptor instead.
func (*RoomGetUsersRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomGetUsersRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomGetUsersRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomGetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserView            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetUsersResponse) Reset() {
	*x = RoomGetUsersResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetUsersResponse) ProtoMessage() {}

func (x *RoomGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetUsersResponse.ProtoReflect.Descriptor instead.
func (*RoomGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *RoomGetUsersResponse) GetUsers() []*UserView {
	if x != nil {
		return x.Users
	}
	return nil
}

type RoomGetFinishedMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetFinishedMatchesRequest) Reset() {
	*x = RoomGetFinishedMatchesRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetFinishedMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetFinishedMatchesRequest) ProtoMessage() {}

func (x *RoomGetFinishedMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetFinishedMatchesRequest.ProtoReflect.Descriptor instead.
func (*RoomGetFinishedMatchesRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *RoomGetFinishedMatchesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomGetFinishedMatchesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomGetFinishedMatchesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FinishedMatches []*MatchView           `protobuf:"bytes,1,rep,name=finished_matches,json=finishedMatches,proto3" json:"finished_matches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomGetFinishedMatchesResponse) Reset() {
	*x = RoomGetFinishedMatchesResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetFinishedMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetFinishedMatchesResponse) ProtoMessage() {}

func (x *RoomGetFinishedMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetFinishedMatchesResponse.ProtoReflect.Descriptor instead.
func (*RoomGetFinishedMatchesResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *RoomGetFinishedMatchesResponse) GetFinishedMatches() []*MatchView {
	if x != nil {
		return x.FinishedMatches
	}
	return nil
}

type MatchView struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameType        string                 `protobuf:"bytes,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	DeckType        string                 `protobuf:"bytes,2,opt,name=deck_type,json=deckType,proto3" json:"deck_type,omitempty"`
	Players         []string               `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Winner          string                 `protobuf:"bytes,4,opt,name=winner,proto3" json:"winner,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsTournament    bool                   `protobuf:"varint,7,opt,name=is_tournament,json=isTournament,proto3" json:"is_tournament,omitempty"`
	TableName       string                 `protobuf:"bytes,8,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchView) Reset() {
	*x = MatchView{}
	mi := &file_mage_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchView) ProtoMessage() {}

func (x *MatchView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchView.ProtoReflect.Descriptor instead.
func (*MatchView) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *MatchView) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *MatchView) GetDeckType() string {
	if x != nil {
		return x.DeckType
	}
	return ""
}

func (x *MatchView) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchView) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *MatchView) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *MatchView) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *MatchView) GetIsTournament() bool {
	if x != nil {
		return x.IsTournament
	}
	return false
}

func (x *MatchView) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type RoomGetAllTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetAllTablesRequest) Reset() {
	*x = RoomGetAllTablesRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetAllTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetAllTablesRequest) ProtoMessage() {}

func (x *RoomGetAllTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetAllTablesRequest.ProtoReflect.Descriptor instead.
func (*RoomGetAllTablesRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *RoomGetAllTablesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomGetAllTablesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomGetAllTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*TableView           `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetAllTablesResponse) Reset() {
	*x = RoomGetAllTablesResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetAllTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetAllTablesResponse) ProtoMessage() {}

func (x *RoomGetAllTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetAllTablesResponse.ProtoReflect.Descriptor instead.
func (*RoomGetAllTablesResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *RoomGetAllTablesResponse) GetTables() []*TableView {
	if x != nil {
		return x.Tables
	}
	return nil
}

type RoomGetTableByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetTableByIdRequest) Reset() {
	*x = RoomGetTableByIdRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetTableByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetTableByIdRequest) ProtoMessage() {}

func (x *RoomGetTableByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetTableByIdRequest.ProtoReflect.Descriptor instead.
func (*RoomGetTableByIdRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *RoomGetTableByIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomGetTableByIdRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomGetTableByIdRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type RoomGetTableByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableView             `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetTableByIdResponse) Reset() {
	*x = RoomGetTableByIdResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetTableByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetTableByIdResponse) ProtoMessage() {}

func (x *RoomGetTableByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetTableByIdResponse.ProtoReflect.Descriptor instead.
func (*RoomGetTableByIdResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{10}
}

func (x *RoomGetTableByIdResponse) GetTable() *TableView {
	if x != nil {
		return x.Table
	}
	return nil
}

type GetMatchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // Default 50, max 100
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // For pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchHistoryRequest) Reset() {
	*x = GetMatchHistoryRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchHistoryRequest) ProtoMessage() {}

func (x *GetMatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetMatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{11}
}

func (x *GetMatchHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMatchHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMatchHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MatchPlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Deck          string                 `protobuf:"bytes,3,opt,name=deck,proto3" json:"deck,omitempty"`     // Deck name or summary
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"` // "win", "loss", "draw", "concede"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPlayerInfo) Reset() {
	*x = MatchPlayerInfo{}
	mi := &file_mage_v1_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPlayerInfo) ProtoMessage() {}

func (x *MatchPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPlayerInfo.ProtoReflect.Descriptor instead.
func (*MatchPlayerInfo) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{12}
}

func (x *MatchPlayerInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MatchPlayerInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MatchPlayerInfo) GetDeck() string {
	if x != nil {
		return x.Deck
	}
	return ""
}

func (x *MatchPlayerInfo) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type MatchHistoryEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId          string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	TableId         string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	TournamentId    string                 `protobuf:"bytes,4,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	Players         []*MatchPlayerInfo     `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	GameType        string                 `protobuf:"bytes,6,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	WinnerId        int64                  `protobuf:"varint,10,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	WinnerName      string                 `protobuf:"bytes,11,opt,name=winner_name,json=winnerName,proto3" json:"winner_name,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchHistoryEntry) Reset() {
	*x = MatchHistoryEntry{}
	mi := &file_mage_v1_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchHistoryEntry) ProtoMessage() {}

func (x *MatchHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchHistoryEntry.ProtoReflect.Descriptor instead.
func (*MatchHistoryEntry) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{13}
}

func (x *MatchHistoryEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MatchHistoryEntry) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MatchHistoryEntry) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *MatchHistoryEntry) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *MatchHistoryEntry) GetPlayers() []*MatchPlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchHistoryEntry) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *MatchHistoryEntry) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *MatchHistoryEntry) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *MatchHistoryEntry) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *MatchHistoryEntry) GetWinnerId() int64 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *MatchHistoryEntry) GetWinnerName() string {
	if x != nil {
		return x.WinnerName
	}
	return ""
}

func (x *MatchHistoryEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetMatchHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Matches       []*MatchHistoryEntry   `protobuf:"bytes,3,rep,name=matches,proto3" json:"matches,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total matches for this user (for pagination)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchHistoryResponse) Reset() {
	*x = GetMatchHistoryResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchHistoryResponse) ProtoMessage() {}

func (x *GetMatchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetMatchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{14}
}

func (x *GetMatchHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMatchHistoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetMatchHistoryResponse) GetMatches() []*MatchHistoryEntry {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *GetMatchHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetMatchByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MatchId       int64                  `protobuf:"varint,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchByIdRequest) Reset() {
	*x = GetMatchByIdRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchByIdRequest) ProtoMessage() {}

func (x *GetMatchByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMatchByIdRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{15}
}

func (x *GetMatchByIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMatchByIdRequest) GetMatchId() int64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

type GetMatchByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Match         *MatchHistoryEntry     `protobuf:"bytes,3,opt,name=match,proto3" json:"match,omitempty"`
	ReplayData    string                 `protobuf:"bytes,4,opt,name=replay_data,json=replayData,proto3" json:"replay_data,omitempty"` // Optional: game log for replay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchByIdResponse) Reset() {
	*x = GetMatchByIdResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchByIdResponse) ProtoMessage() {}

func (x *GetMatchByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchByIdResponse.ProtoReflect.Descriptor instead.
func (*GetMatchByIdResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{16}
}

func (x *GetMatchByIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMatchByIdResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetMatchByIdResponse) GetMatch() *MatchHistoryEntry {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *GetMatchByIdResponse) GetReplayData() string {
	if x != nil {
		return x.ReplayData
	}
	return ""
}

var File_mage_v1_room_proto protoreflect.FileDescriptor

const file_mage_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12mage/v1/room.proto\x12\amage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14mage/v1/models.proto\";\n" +
	"\x1aServerGetMainRoomIdRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"6\n" +
	"\x1bServerGetMainRoomIdResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"M\n" +
	"\x13RoomGetUsersRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"?\n" +
	"\x14RoomGetUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.mage.v1.UserViewR\x05users\"W\n" +
	"\x1dRoomGetFinishedMatchesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"_\n" +
	"\x1eRoomGetFinishedMatchesResponse\x12=\n" +
	"\x10finished_matches\x18\x01 \x03(\v2\x12.mage.v1.MatchViewR\x0ffinishedMatches\"\x9d\x02\n" +
	"\tMatchView\x12\x1b\n" +
	"\tgame_type\x18\x01 \x01(\tR\bgameType\x12\x1b\n" +
	"\tdeck_type\x18\x02 \x01(\tR\bdeckType\x12\x18\n" +
	"\aplayers\x18\x03 \x03(\tR\aplayers\x12\x16\n" +
	"\x06winner\x18\x04 \x01(\tR\x06winner\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutes\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\ris_tournament\x18\a \x01(\bR\fisTournament\x12\x1d\n" +
	"\n" +
	"table_name\x18\b \x01(\tR\ttableName\"Q\n" +
	"\x17RoomGetAllTablesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"F\n" +
	"\x18RoomGetAllTablesResponse\x12*\n" +
	"\x06tables\x18\x01 \x03(\v2\x12.mage.v1.TableViewR\x06tables\"l\n" +
	"\x17RoomGetTableByIdRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\"D\n" +
	"\x18RoomGetTableByIdResponse\x12(\n" +
	"\x05table\x18\x01 \x01(\v2\x12.mage.v1.TableViewR\x05table\"e\n" +
	"\x16GetMatchHistoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"r\n" +
	"\x0fMatchPlayerInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04deck\x18\x03 \x01(\tR\x04deck\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\"\xe3\x03\n" +
	"\x11MatchHistoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\x12#\n" +
	"\rtournament_id\x18\x04 \x01(\tR\ftournamentId\x122\n" +
	"\aplayers\x18\x05 \x03(\v2\x18.mage.v1.MatchPlayerInfoR\aplayers\x12\x1b\n" +
	"\tgame_type\x18\x06 \x01(\tR\bgameType\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12)\n" +
	"\x10duration_seconds\x18\t \x01(\x05R\x0fdurationSeconds\x12\x1b\n" +
	"\twinner_id\x18\n" +
	" \x01(\x03R\bwinnerId\x12\x1f\n" +
	"\vwinner_name\x18\v \x01(\tR\n" +
	"winnerName\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa0\x01\n" +
	"\x17GetMatchHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x124\n" +
	"\amatches\x18\x03 \x03(\v2\x1a.mage.v1.MatchHistoryEntryR\amatches\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"O\n" +
	"\x13GetMatchByIdRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\x03R\amatchId\"\x99\x01\n" +
	"\x14GetMatchByIdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\x05match\x18\x03 \x01(\v2\x1a.mage.v1.MatchHistoryEntryR\x05match\x12\x1f\n" +
	"\vreplay_data\x18\x04 \x01(\tR\n" +
	"replayDataB6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var (
	file_mage_v1_room_proto_rawDescOnce sync.Once
	file_mage_v1_room_proto_rawDescData []byte
)

func file_mage_v1_room_proto_rawDescGZIP() []byte {
	file_mage_v1_room_proto_rawDescOnce.Do(func() {
		file_mage_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_v1_room_proto_rawDesc), len(file_mage_v1_room_proto_rawDesc)))
	})
	return file_mage_v1_room_proto_rawDescData
}

var file_mage_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_mage_v1_room_proto_goTypes = []any{
	(*ServerGetMainRoomIdRequest)(nil),     // 0: mage.v1.ServerGetMainRoomIdRequest
	(*ServerGetMainRoomIdResponse)(nil),    // 1: mage.v1.ServerGetMainRoomIdResponse
	(*RoomGetUsersRequest)(nil),            // 2: mage.v1.RoomGetUsersRequest
	(*RoomGetUsersResponse)(nil),           // 3: mage.v1.RoomGetUsersResponse
	(*RoomGetFinishedMatchesRequest)(nil),  // 4: mage.v1.RoomGetFinishedMatchesRequest
	(*RoomGetFinishedMatchesResponse)(nil), // 5: mage.v1.RoomGetFinishedMatchesResponse
	(*MatchView)(nil),                      // 6: mage.v1.MatchView
	(*RoomGetAllTablesRequest)(nil),        // 7: mage.v1.RoomGetAllTablesRequest
	(*RoomGetAllTablesResponse)(nil),       // 8: mage.v1.RoomGetAllTablesResponse
	(*RoomGetTableByIdRequest)(nil),        // 9: mage.v1.RoomGetTableByIdRequest
	(*RoomGetTableByIdResponse)(nil),       // 10: mage.v1.RoomGetTableByIdResponse
	(*GetMatchHistoryRequest)(nil),         // 11: mage.v1.GetMatchHistoryRequest
	(*MatchPlayerInfo)(nil),                // 12: mage.v1.MatchPlayerInfo
	(*MatchHistoryEntry)(nil),              // 13: mage.v1.MatchHistoryEntry
	(*GetMatchHistoryResponse)(nil),        // 14: mage.v1.GetMatchHistoryResponse
	(*GetMatchByIdRequest)(nil),            // 15: mage.v1.GetMatchByIdRequest
	(*GetMatchByIdResponse)(nil),           // 16: mage.v1.GetMatchByIdResponse
	(*UserView)(nil),                       // 17: mage.v1.UserView
	(*timestamppb.Timestamp)(nil),          // 18: google.protobuf.Timestamp
	(*TableView)(nil),                      // 19: mage.v1.TableView
}
var file_mage_v1_room_proto_depIdxs = []int32{
	17, // 0: mage.v1.RoomGetUsersResponse.users:type_name -> mage.v1.UserView
	6,  // 1: mage.v1.RoomGetFinishedMatchesResponse.finished_matches:type_name -> mage.v1.MatchView
	18, // 2: mage.v1.MatchView.end_time:type_name -> google.protobuf.Timestamp
	19, // 3: mage.v1.RoomGetAllTablesResponse.tables:type_name -> mage.v1.TableView
	19, // 4: mage.v1.RoomGetTableByIdResponse.table:type_name -> mage.v1.TableView
	12, // 5: mage.v1.MatchHistoryEntry.players:type_name -> mage.v1.MatchPlayerInfo
	18, // 6: mage.v1.MatchHistoryEntry.start_time:type_name -> google.protobuf.Timestamp
	18, // 7: mage.v1.MatchHistoryEntry.end_time:type_name -> google.protobuf.Timestamp
	18, // 8: mage.v1.MatchHistoryEntry.created_at:type_name -> google.protobuf.Timestamp
	13, // 9: mage.v1.GetMatchHistoryResponse.matches:type_name -> mage.v1.MatchHistoryEntry
	13, // 10: mage.v1.GetMatchByIdResponse.match:type_name -> mage.v1.MatchHistoryEntry
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_mage_v1_room_proto_init() }
func file_mage_v1_room_proto_init() {
	if File_mage_v1_room_proto != nil {
		return
	}
	file_mage_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_room_proto_rawDesc), len(file_mage_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_v1_room_proto_goTypes,
		DependencyIndexes: file_mage_v1_room_proto_depIdxs,
		MessageInfos:      file_mage_v1_room_proto_msgTypes,
	}.Build()
	File_mage_v1_room_proto = out.File
	file_mage_v1_room_proto_goTypes = nil
	file_mage_v1_room_proto_depIdxs = nil
}
