// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/room.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerGetMainRoomIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetMainRoomIdRequest) Reset() {
	*x = ServerGetMainRoomIdRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetMainRoomIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetMainRoomIdRequest) ProtoMessage() {}

func (x *ServerGetMainRoomIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetMainRoomIdRequest.ProtoReflect.Descriptor instead.
func (*ServerGetMainRoomIdRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *ServerGetMainRoomIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ServerGetMainRoomIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetMainRoomIdResponse) Reset() {
	*x = ServerGetMainRoomIdResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetMainRoomIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetMainRoomIdResponse) ProtoMessage() {}

func (x *ServerGetMainRoomIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetMainRoomIdResponse.ProtoReflect.Descriptor instead.
func (*ServerGetMainRoomIdResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *ServerGetMainRoomIdResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomGetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetUsersRequest) Reset() {
	*x = RoomGetUsersRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetUsersRequest) ProtoMessage() {}

func (x *RoomGetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetUsersRequest.ProtoReflect.Descriptor instead.
func (*RoomGetUsersRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomGetUsersRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomGetUsersRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomGetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserView            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetUsersResponse) Reset() {
	*x = RoomGetUsersResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetUsersResponse) ProtoMessage() {}

func (x *RoomGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetUsersResponse.ProtoReflect.Descriptor instead.
func (*RoomGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *RoomGetUsersResponse) GetUsers() []*UserView {
	if x != nil {
		return x.Users
	}
	return nil
}

type RoomGetFinishedMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetFinishedMatchesRequest) Reset() {
	*x = RoomGetFinishedMatchesRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetFinishedMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetFinishedMatchesRequest) ProtoMessage() {}

func (x *RoomGetFinishedMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetFinishedMatchesRequest.ProtoReflect.Descriptor instead.
func (*RoomGetFinishedMatchesRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *RoomGetFinishedMatchesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomGetFinishedMatchesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomGetFinishedMatchesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FinishedMatches []*MatchView           `protobuf:"bytes,1,rep,name=finished_matches,json=finishedMatches,proto3" json:"finished_matches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomGetFinishedMatchesResponse) Reset() {
	*x = RoomGetFinishedMatchesResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetFinishedMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetFinishedMatchesResponse) ProtoMessage() {}

func (x *RoomGetFinishedMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetFinishedMatchesResponse.ProtoReflect.Descriptor instead.
func (*RoomGetFinishedMatchesResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *RoomGetFinishedMatchesResponse) GetFinishedMatches() []*MatchView {
	if x != nil {
		return x.FinishedMatches
	}
	return nil
}

type MatchView struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameType        string                 `protobuf:"bytes,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	DeckType        string                 `protobuf:"bytes,2,opt,name=deck_type,json=deckType,proto3" json:"deck_type,omitempty"`
	Players         []string               `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Winner          string                 `protobuf:"bytes,4,opt,name=winner,proto3" json:"winner,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsTournament    bool                   `protobuf:"varint,7,opt,name=is_tournament,json=isTournament,proto3" json:"is_tournament,omitempty"`
	TableName       string                 `protobuf:"bytes,8,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchView) Reset() {
	*x = MatchView{}
	mi := &file_mage_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchView) ProtoMessage() {}

func (x *MatchView) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchView.ProtoReflect.Descriptor instead.
func (*MatchView) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *MatchView) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *MatchView) GetDeckType() string {
	if x != nil {
		return x.DeckType
	}
	return ""
}

func (x *MatchView) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchView) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *MatchView) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *MatchView) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *MatchView) GetIsTournament() bool {
	if x != nil {
		return x.IsTournament
	}
	return false
}

func (x *MatchView) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type RoomGetAllTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetAllTablesRequest) Reset() {
	*x = RoomGetAllTablesRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetAllTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetAllTablesRequest) ProtoMessage() {}

func (x *RoomGetAllTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetAllTablesRequest.ProtoReflect.Descriptor instead.
func (*RoomGetAllTablesRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *RoomGetAllTablesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomGetAllTablesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomGetAllTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*TableView           `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetAllTablesResponse) Reset() {
	*x = RoomGetAllTablesResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetAllTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetAllTablesResponse) ProtoMessage() {}

func (x *RoomGetAllTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetAllTablesResponse.ProtoReflect.Descriptor instead.
func (*RoomGetAllTablesResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *RoomGetAllTablesResponse) GetTables() []*TableView {
	if x != nil {
		return x.Tables
	}
	return nil
}

type RoomGetTableByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetTableByIdRequest) Reset() {
	*x = RoomGetTableByIdRequest{}
	mi := &file_mage_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetTableByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetTableByIdRequest) ProtoMessage() {}

func (x *RoomGetTableByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetTableByIdRequest.ProtoReflect.Descriptor instead.
func (*RoomGetTableByIdRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *RoomGetTableByIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomGetTableByIdRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomGetTableByIdRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type RoomGetTableByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableView             `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGetTableByIdResponse) Reset() {
	*x = RoomGetTableByIdResponse{}
	mi := &file_mage_v1_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGetTableByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetTableByIdResponse) ProtoMessage() {}

func (x *RoomGetTableByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetTableByIdResponse.ProtoReflect.Descriptor instead.
func (*RoomGetTableByIdResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_room_proto_rawDescGZIP(), []int{10}
}

func (x *RoomGetTableByIdResponse) GetTable() *TableView {
	if x != nil {
		return x.Table
	}
	return nil
}

var File_mage_v1_room_proto protoreflect.FileDescriptor

const file_mage_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12mage/v1/room.proto\x12\amage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14mage/v1/models.proto\";\n" +
	"\x1aServerGetMainRoomIdRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"6\n" +
	"\x1bServerGetMainRoomIdResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"M\n" +
	"\x13RoomGetUsersRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"?\n" +
	"\x14RoomGetUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.mage.v1.UserViewR\x05users\"W\n" +
	"\x1dRoomGetFinishedMatchesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"_\n" +
	"\x1eRoomGetFinishedMatchesResponse\x12=\n" +
	"\x10finished_matches\x18\x01 \x03(\v2\x12.mage.v1.MatchViewR\x0ffinishedMatches\"\x9d\x02\n" +
	"\tMatchView\x12\x1b\n" +
	"\tgame_type\x18\x01 \x01(\tR\bgameType\x12\x1b\n" +
	"\tdeck_type\x18\x02 \x01(\tR\bdeckType\x12\x18\n" +
	"\aplayers\x18\x03 \x03(\tR\aplayers\x12\x16\n" +
	"\x06winner\x18\x04 \x01(\tR\x06winner\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutes\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\ris_tournament\x18\a \x01(\bR\fisTournament\x12\x1d\n" +
	"\n" +
	"table_name\x18\b \x01(\tR\ttableName\"Q\n" +
	"\x17RoomGetAllTablesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"F\n" +
	"\x18RoomGetAllTablesResponse\x12*\n" +
	"\x06tables\x18\x01 \x03(\v2\x12.mage.v1.TableViewR\x06tables\"l\n" +
	"\x17RoomGetTableByIdRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\"D\n" +
	"\x18RoomGetTableByIdResponse\x12(\n" +
	"\x05table\x18\x01 \x01(\v2\x12.mage.v1.TableViewR\x05tableB6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var (
	file_mage_v1_room_proto_rawDescOnce sync.Once
	file_mage_v1_room_proto_rawDescData []byte
)

func file_mage_v1_room_proto_rawDescGZIP() []byte {
	file_mage_v1_room_proto_rawDescOnce.Do(func() {
		file_mage_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_v1_room_proto_rawDesc), len(file_mage_v1_room_proto_rawDesc)))
	})
	return file_mage_v1_room_proto_rawDescData
}

var file_mage_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mage_v1_room_proto_goTypes = []any{
	(*ServerGetMainRoomIdRequest)(nil),     // 0: mage.v1.ServerGetMainRoomIdRequest
	(*ServerGetMainRoomIdResponse)(nil),    // 1: mage.v1.ServerGetMainRoomIdResponse
	(*RoomGetUsersRequest)(nil),            // 2: mage.v1.RoomGetUsersRequest
	(*RoomGetUsersResponse)(nil),           // 3: mage.v1.RoomGetUsersResponse
	(*RoomGetFinishedMatchesRequest)(nil),  // 4: mage.v1.RoomGetFinishedMatchesRequest
	(*RoomGetFinishedMatchesResponse)(nil), // 5: mage.v1.RoomGetFinishedMatchesResponse
	(*MatchView)(nil),                      // 6: mage.v1.MatchView
	(*RoomGetAllTablesRequest)(nil),        // 7: mage.v1.RoomGetAllTablesRequest
	(*RoomGetAllTablesResponse)(nil),       // 8: mage.v1.RoomGetAllTablesResponse
	(*RoomGetTableByIdRequest)(nil),        // 9: mage.v1.RoomGetTableByIdRequest
	(*RoomGetTableByIdResponse)(nil),       // 10: mage.v1.RoomGetTableByIdResponse
	(*UserView)(nil),                       // 11: mage.v1.UserView
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
	(*TableView)(nil),                      // 13: mage.v1.TableView
}
var file_mage_v1_room_proto_depIdxs = []int32{
	11, // 0: mage.v1.RoomGetUsersResponse.users:type_name -> mage.v1.UserView
	6,  // 1: mage.v1.RoomGetFinishedMatchesResponse.finished_matches:type_name -> mage.v1.MatchView
	12, // 2: mage.v1.MatchView.end_time:type_name -> google.protobuf.Timestamp
	13, // 3: mage.v1.RoomGetAllTablesResponse.tables:type_name -> mage.v1.TableView
	13, // 4: mage.v1.RoomGetTableByIdResponse.table:type_name -> mage.v1.TableView
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_mage_v1_room_proto_init() }
func file_mage_v1_room_proto_init() {
	if File_mage_v1_room_proto != nil {
		return
	}
	file_mage_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_room_proto_rawDesc), len(file_mage_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_v1_room_proto_goTypes,
		DependencyIndexes: file_mage_v1_room_proto_depIdxs,
		MessageInfos:      file_mage_v1_room_proto_msgTypes,
	}.Build()
	File_mage_v1_room_proto = out.File
	file_mage_v1_room_proto_goTypes = nil
	file_mage_v1_room_proto_depIdxs = nil
}
