// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/server.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_mage_v1_server_proto protoreflect.FileDescriptor

const file_mage_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x14mage/v1/server.proto\x12\amage.v1\x1a\x12mage/v1/auth.proto\x1a\x12mage/v1/room.proto\x1a\x13mage/v1/table.proto\x1a\x12mage/v1/game.proto\x1a\x18mage/v1/tournament.proto\x1a\x13mage/v1/draft.proto\x1a\x12mage/v1/chat.proto\x1a\x13mage/v1/admin.proto2\x81/\n" +
	"\n" +
	"MageServer\x12K\n" +
	"\fAuthRegister\x12\x1c.mage.v1.AuthRegisterRequest\x1a\x1d.mage.v1.AuthRegisterResponse\x12c\n" +
	"\x14AuthSendTokenToEmail\x12$.mage.v1.AuthSendTokenToEmailRequest\x1a%.mage.v1.AuthSendTokenToEmailResponse\x12Z\n" +
	"\x11AuthResetPassword\x12!.mage.v1.AuthResetPasswordRequest\x1a\".mage.v1.AuthResetPasswordResponse\x12H\n" +
	"\vConnectUser\x12\x1b.mage.v1.ConnectUserRequest\x1a\x1c.mage.v1.ConnectUserResponse\x12K\n" +
	"\fConnectAdmin\x12\x1c.mage.v1.ConnectAdminRequest\x1a\x1d.mage.v1.ConnectAdminResponse\x12]\n" +
	"\x12ConnectSetUserData\x12\".mage.v1.ConnectSetUserDataRequest\x1a#.mage.v1.ConnectSetUserDataResponse\x123\n" +
	"\x04Ping\x12\x14.mage.v1.PingRequest\x1a\x15.mage.v1.PingResponse\x12Q\n" +
	"\x0eGetServerState\x12\x1e.mage.v1.GetServerStateRequest\x1a\x1f.mage.v1.GetServerStateResponse\x12u\n" +
	"\x1aServerGetPromotionMessages\x12*.mage.v1.ServerGetPromotionMessagesRequest\x1a+.mage.v1.ServerGetPromotionMessagesResponse\x12o\n" +
	"\x18ServerAddFeedbackMessage\x12(.mage.v1.ServerAddFeedbackMessageRequest\x1a).mage.v1.ServerAddFeedbackMessageResponse\x12`\n" +
	"\x13ServerGetMainRoomId\x12#.mage.v1.ServerGetMainRoomIdRequest\x1a$.mage.v1.ServerGetMainRoomIdResponse\x12K\n" +
	"\fRoomGetUsers\x12\x1c.mage.v1.RoomGetUsersRequest\x1a\x1d.mage.v1.RoomGetUsersResponse\x12i\n" +
	"\x16RoomGetFinishedMatches\x12&.mage.v1.RoomGetFinishedMatchesRequest\x1a'.mage.v1.RoomGetFinishedMatchesResponse\x12W\n" +
	"\x10RoomGetAllTables\x12 .mage.v1.RoomGetAllTablesRequest\x1a!.mage.v1.RoomGetAllTablesResponse\x12W\n" +
	"\x10RoomGetTableById\x12 .mage.v1.RoomGetTableByIdRequest\x1a!.mage.v1.RoomGetTableByIdResponse\x12T\n" +
	"\x0fRoomCreateTable\x12\x1f.mage.v1.RoomCreateTableRequest\x1a .mage.v1.RoomCreateTableResponse\x12c\n" +
	"\x14RoomCreateTournament\x12$.mage.v1.RoomCreateTournamentRequest\x1a%.mage.v1.RoomCreateTournamentResponse\x12N\n" +
	"\rRoomJoinTable\x12\x1d.mage.v1.RoomJoinTableRequest\x1a\x1e.mage.v1.RoomJoinTableResponse\x12]\n" +
	"\x12RoomJoinTournament\x12\".mage.v1.RoomJoinTournamentRequest\x1a#.mage.v1.RoomJoinTournamentResponse\x12u\n" +
	"\x1aRoomLeaveTableOrTournament\x12*.mage.v1.RoomLeaveTableOrTournamentRequest\x1a+.mage.v1.RoomLeaveTableOrTournamentResponse\x12Q\n" +
	"\x0eRoomWatchTable\x12\x1e.mage.v1.RoomWatchTableRequest\x1a\x1f.mage.v1.RoomWatchTableResponse\x12`\n" +
	"\x13RoomWatchTournament\x12#.mage.v1.RoomWatchTournamentRequest\x1a$.mage.v1.RoomWatchTournamentResponse\x12Q\n" +
	"\x0eTableSwapSeats\x12\x1e.mage.v1.TableSwapSeatsRequest\x1a\x1f.mage.v1.TableSwapSeatsResponse\x12H\n" +
	"\vTableRemove\x12\x1b.mage.v1.TableRemoveRequest\x1a\x1c.mage.v1.TableRemoveResponse\x12K\n" +
	"\fTableIsOwner\x12\x1c.mage.v1.TableIsOwnerRequest\x1a\x1d.mage.v1.TableIsOwnerResponse\x12E\n" +
	"\n" +
	"DeckSubmit\x12\x1a.mage.v1.DeckSubmitRequest\x1a\x1b.mage.v1.DeckSubmitResponse\x12?\n" +
	"\bDeckSave\x12\x18.mage.v1.DeckSaveRequest\x1a\x19.mage.v1.DeckSaveResponse\x12?\n" +
	"\bGameJoin\x12\x18.mage.v1.GameJoinRequest\x1a\x19.mage.v1.GameJoinResponse\x12Q\n" +
	"\x0eGameWatchStart\x12\x1e.mage.v1.GameWatchStartRequest\x1a\x1f.mage.v1.GameWatchStartResponse\x12N\n" +
	"\rGameWatchStop\x12\x1d.mage.v1.GameWatchStopRequest\x1a\x1e.mage.v1.GameWatchStopResponse\x12H\n" +
	"\vGameGetView\x12\x1b.mage.v1.GameGetViewRequest\x1a\x1c.mage.v1.GameGetViewResponse\x12Q\n" +
	"\x0eSendPlayerUUID\x12\x1e.mage.v1.SendPlayerUUIDRequest\x1a\x1f.mage.v1.SendPlayerUUIDResponse\x12W\n" +
	"\x10SendPlayerString\x12 .mage.v1.SendPlayerStringRequest\x1a!.mage.v1.SendPlayerStringResponse\x12Z\n" +
	"\x11SendPlayerBoolean\x12!.mage.v1.SendPlayerBooleanRequest\x1a\".mage.v1.SendPlayerBooleanResponse\x12Z\n" +
	"\x11SendPlayerInteger\x12!.mage.v1.SendPlayerIntegerRequest\x1a\".mage.v1.SendPlayerIntegerResponse\x12]\n" +
	"\x12SendPlayerManaType\x12\".mage.v1.SendPlayerManaTypeRequest\x1a#.mage.v1.SendPlayerManaTypeResponse\x12W\n" +
	"\x10SendPlayerAction\x12 .mage.v1.SendPlayerActionRequest\x1a!.mage.v1.SendPlayerActionResponse\x12E\n" +
	"\n" +
	"MatchStart\x12\x1a.mage.v1.MatchStartRequest\x1a\x1b.mage.v1.MatchStartResponse\x12B\n" +
	"\tMatchQuit\x12\x19.mage.v1.MatchQuitRequest\x1a\x1a.mage.v1.MatchQuitResponse\x12B\n" +
	"\tDraftJoin\x12\x19.mage.v1.DraftJoinRequest\x1a\x1a.mage.v1.DraftJoinResponse\x12Z\n" +
	"\x11SendDraftCardPick\x12!.mage.v1.SendDraftCardPickRequest\x1a\".mage.v1.SendDraftCardPickResponse\x12Z\n" +
	"\x11SendDraftCardMark\x12!.mage.v1.SendDraftCardMarkRequest\x1a\".mage.v1.SendDraftCardMarkResponse\x12f\n" +
	"\x15DraftSetBoosterLoaded\x12%.mage.v1.DraftSetBoosterLoadedRequest\x1a&.mage.v1.DraftSetBoosterLoadedResponse\x12B\n" +
	"\tDraftQuit\x12\x19.mage.v1.DraftQuitRequest\x1a\x1a.mage.v1.DraftQuitResponse\x12Q\n" +
	"\x0eTournamentJoin\x12\x1e.mage.v1.TournamentJoinRequest\x1a\x1f.mage.v1.TournamentJoinResponse\x12T\n" +
	"\x0fTournamentStart\x12\x1f.mage.v1.TournamentStartRequest\x1a .mage.v1.TournamentStartResponse\x12Q\n" +
	"\x0eTournamentQuit\x12\x1e.mage.v1.TournamentQuitRequest\x1a\x1f.mage.v1.TournamentQuitResponse\x12]\n" +
	"\x12TournamentFindById\x12\".mage.v1.TournamentFindByIdRequest\x1a#.mage.v1.TournamentFindByIdResponse\x12?\n" +
	"\bChatJoin\x12\x18.mage.v1.ChatJoinRequest\x1a\x19.mage.v1.ChatJoinResponse\x12B\n" +
	"\tChatLeave\x12\x19.mage.v1.ChatLeaveRequest\x1a\x1a.mage.v1.ChatLeaveResponse\x12T\n" +
	"\x0fChatSendMessage\x12\x1f.mage.v1.ChatSendMessageRequest\x1a .mage.v1.ChatSendMessageResponse\x12T\n" +
	"\x0fChatFindByTable\x12\x1f.mage.v1.ChatFindByTableRequest\x1a .mage.v1.ChatFindByTableResponse\x12Q\n" +
	"\x0eChatFindByGame\x12\x1e.mage.v1.ChatFindByGameRequest\x1a\x1f.mage.v1.ChatFindByGameResponse\x12c\n" +
	"\x14ChatFindByTournament\x12$.mage.v1.ChatFindByTournamentRequest\x1a%.mage.v1.ChatFindByTournamentResponse\x12Q\n" +
	"\x0eChatFindByRoom\x12\x1e.mage.v1.ChatFindByRoomRequest\x1a\x1f.mage.v1.ChatFindByRoomResponse\x12E\n" +
	"\n" +
	"ReplayInit\x12\x1a.mage.v1.ReplayInitRequest\x1a\x1b.mage.v1.ReplayInitResponse\x12H\n" +
	"\vReplayStart\x12\x1b.mage.v1.ReplayStartRequest\x1a\x1c.mage.v1.ReplayStartResponse\x12E\n" +
	"\n" +
	"ReplayStop\x12\x1a.mage.v1.ReplayStopRequest\x1a\x1b.mage.v1.ReplayStopResponse\x12E\n" +
	"\n" +
	"ReplayNext\x12\x1a.mage.v1.ReplayNextRequest\x1a\x1b.mage.v1.ReplayNextResponse\x12Q\n" +
	"\x0eReplayPrevious\x12\x1e.mage.v1.ReplayPreviousRequest\x1a\x1f.mage.v1.ReplayPreviousResponse\x12Z\n" +
	"\x11ReplaySkipForward\x12!.mage.v1.ReplaySkipForwardRequest\x1a\".mage.v1.ReplaySkipForwardResponse\x12N\n" +
	"\rAdminGetUsers\x12\x1d.mage.v1.AdminGetUsersRequest\x1a\x1e.mage.v1.AdminGetUsersResponse\x12`\n" +
	"\x13AdminDisconnectUser\x12#.mage.v1.AdminDisconnectUserRequest\x1a$.mage.v1.AdminDisconnectUserResponse\x12N\n" +
	"\rAdminMuteUser\x12\x1d.mage.v1.AdminMuteUserRequest\x1a\x1e.mage.v1.AdminMuteUserResponse\x12N\n" +
	"\rAdminLockUser\x12\x1d.mage.v1.AdminLockUserRequest\x1a\x1e.mage.v1.AdminLockUserResponse\x12Z\n" +
	"\x11AdminActivateUser\x12!.mage.v1.AdminActivateUserRequest\x1a\".mage.v1.AdminActivateUserResponse\x12l\n" +
	"\x17AdminToggleActivateUser\x12'.mage.v1.AdminToggleActivateUserRequest\x1a(.mage.v1.AdminToggleActivateUserResponse\x12`\n" +
	"\x13AdminEndUserSession\x12#.mage.v1.AdminEndUserSessionRequest\x1a$.mage.v1.AdminEndUserSessionResponse\x12W\n" +
	"\x10AdminTableRemove\x12 .mage.v1.AdminTableRemoveRequest\x1a!.mage.v1.AdminTableRemoveResponse\x12r\n" +
	"\x19AdminSendBroadcastMessage\x12).mage.v1.AdminSendBroadcastMessageRequest\x1a*.mage.v1.AdminSendBroadcastMessageResponseB6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var file_mage_v1_server_proto_goTypes = []any{
	(*AuthRegisterRequest)(nil),                // 0: mage.v1.AuthRegisterRequest
	(*AuthSendTokenToEmailRequest)(nil),        // 1: mage.v1.AuthSendTokenToEmailRequest
	(*AuthResetPasswordRequest)(nil),           // 2: mage.v1.AuthResetPasswordRequest
	(*ConnectUserRequest)(nil),                 // 3: mage.v1.ConnectUserRequest
	(*ConnectAdminRequest)(nil),                // 4: mage.v1.ConnectAdminRequest
	(*ConnectSetUserDataRequest)(nil),          // 5: mage.v1.ConnectSetUserDataRequest
	(*PingRequest)(nil),                        // 6: mage.v1.PingRequest
	(*GetServerStateRequest)(nil),              // 7: mage.v1.GetServerStateRequest
	(*ServerGetPromotionMessagesRequest)(nil),  // 8: mage.v1.ServerGetPromotionMessagesRequest
	(*ServerAddFeedbackMessageRequest)(nil),    // 9: mage.v1.ServerAddFeedbackMessageRequest
	(*ServerGetMainRoomIdRequest)(nil),         // 10: mage.v1.ServerGetMainRoomIdRequest
	(*RoomGetUsersRequest)(nil),                // 11: mage.v1.RoomGetUsersRequest
	(*RoomGetFinishedMatchesRequest)(nil),      // 12: mage.v1.RoomGetFinishedMatchesRequest
	(*RoomGetAllTablesRequest)(nil),            // 13: mage.v1.RoomGetAllTablesRequest
	(*RoomGetTableByIdRequest)(nil),            // 14: mage.v1.RoomGetTableByIdRequest
	(*RoomCreateTableRequest)(nil),             // 15: mage.v1.RoomCreateTableRequest
	(*RoomCreateTournamentRequest)(nil),        // 16: mage.v1.RoomCreateTournamentRequest
	(*RoomJoinTableRequest)(nil),               // 17: mage.v1.RoomJoinTableRequest
	(*RoomJoinTournamentRequest)(nil),          // 18: mage.v1.RoomJoinTournamentRequest
	(*RoomLeaveTableOrTournamentRequest)(nil),  // 19: mage.v1.RoomLeaveTableOrTournamentRequest
	(*RoomWatchTableRequest)(nil),              // 20: mage.v1.RoomWatchTableRequest
	(*RoomWatchTournamentRequest)(nil),         // 21: mage.v1.RoomWatchTournamentRequest
	(*TableSwapSeatsRequest)(nil),              // 22: mage.v1.TableSwapSeatsRequest
	(*TableRemoveRequest)(nil),                 // 23: mage.v1.TableRemoveRequest
	(*TableIsOwnerRequest)(nil),                // 24: mage.v1.TableIsOwnerRequest
	(*DeckSubmitRequest)(nil),                  // 25: mage.v1.DeckSubmitRequest
	(*DeckSaveRequest)(nil),                    // 26: mage.v1.DeckSaveRequest
	(*GameJoinRequest)(nil),                    // 27: mage.v1.GameJoinRequest
	(*GameWatchStartRequest)(nil),              // 28: mage.v1.GameWatchStartRequest
	(*GameWatchStopRequest)(nil),               // 29: mage.v1.GameWatchStopRequest
	(*GameGetViewRequest)(nil),                 // 30: mage.v1.GameGetViewRequest
	(*SendPlayerUUIDRequest)(nil),              // 31: mage.v1.SendPlayerUUIDRequest
	(*SendPlayerStringRequest)(nil),            // 32: mage.v1.SendPlayerStringRequest
	(*SendPlayerBooleanRequest)(nil),           // 33: mage.v1.SendPlayerBooleanRequest
	(*SendPlayerIntegerRequest)(nil),           // 34: mage.v1.SendPlayerIntegerRequest
	(*SendPlayerManaTypeRequest)(nil),          // 35: mage.v1.SendPlayerManaTypeRequest
	(*SendPlayerActionRequest)(nil),            // 36: mage.v1.SendPlayerActionRequest
	(*MatchStartRequest)(nil),                  // 37: mage.v1.MatchStartRequest
	(*MatchQuitRequest)(nil),                   // 38: mage.v1.MatchQuitRequest
	(*DraftJoinRequest)(nil),                   // 39: mage.v1.DraftJoinRequest
	(*SendDraftCardPickRequest)(nil),           // 40: mage.v1.SendDraftCardPickRequest
	(*SendDraftCardMarkRequest)(nil),           // 41: mage.v1.SendDraftCardMarkRequest
	(*DraftSetBoosterLoadedRequest)(nil),       // 42: mage.v1.DraftSetBoosterLoadedRequest
	(*DraftQuitRequest)(nil),                   // 43: mage.v1.DraftQuitRequest
	(*TournamentJoinRequest)(nil),              // 44: mage.v1.TournamentJoinRequest
	(*TournamentStartRequest)(nil),             // 45: mage.v1.TournamentStartRequest
	(*TournamentQuitRequest)(nil),              // 46: mage.v1.TournamentQuitRequest
	(*TournamentFindByIdRequest)(nil),          // 47: mage.v1.TournamentFindByIdRequest
	(*ChatJoinRequest)(nil),                    // 48: mage.v1.ChatJoinRequest
	(*ChatLeaveRequest)(nil),                   // 49: mage.v1.ChatLeaveRequest
	(*ChatSendMessageRequest)(nil),             // 50: mage.v1.ChatSendMessageRequest
	(*ChatFindByTableRequest)(nil),             // 51: mage.v1.ChatFindByTableRequest
	(*ChatFindByGameRequest)(nil),              // 52: mage.v1.ChatFindByGameRequest
	(*ChatFindByTournamentRequest)(nil),        // 53: mage.v1.ChatFindByTournamentRequest
	(*ChatFindByRoomRequest)(nil),              // 54: mage.v1.ChatFindByRoomRequest
	(*ReplayInitRequest)(nil),                  // 55: mage.v1.ReplayInitRequest
	(*ReplayStartRequest)(nil),                 // 56: mage.v1.ReplayStartRequest
	(*ReplayStopRequest)(nil),                  // 57: mage.v1.ReplayStopRequest
	(*ReplayNextRequest)(nil),                  // 58: mage.v1.ReplayNextRequest
	(*ReplayPreviousRequest)(nil),              // 59: mage.v1.ReplayPreviousRequest
	(*ReplaySkipForwardRequest)(nil),           // 60: mage.v1.ReplaySkipForwardRequest
	(*AdminGetUsersRequest)(nil),               // 61: mage.v1.AdminGetUsersRequest
	(*AdminDisconnectUserRequest)(nil),         // 62: mage.v1.AdminDisconnectUserRequest
	(*AdminMuteUserRequest)(nil),               // 63: mage.v1.AdminMuteUserRequest
	(*AdminLockUserRequest)(nil),               // 64: mage.v1.AdminLockUserRequest
	(*AdminActivateUserRequest)(nil),           // 65: mage.v1.AdminActivateUserRequest
	(*AdminToggleActivateUserRequest)(nil),     // 66: mage.v1.AdminToggleActivateUserRequest
	(*AdminEndUserSessionRequest)(nil),         // 67: mage.v1.AdminEndUserSessionRequest
	(*AdminTableRemoveRequest)(nil),            // 68: mage.v1.AdminTableRemoveRequest
	(*AdminSendBroadcastMessageRequest)(nil),   // 69: mage.v1.AdminSendBroadcastMessageRequest
	(*AuthRegisterResponse)(nil),               // 70: mage.v1.AuthRegisterResponse
	(*AuthSendTokenToEmailResponse)(nil),       // 71: mage.v1.AuthSendTokenToEmailResponse
	(*AuthResetPasswordResponse)(nil),          // 72: mage.v1.AuthResetPasswordResponse
	(*ConnectUserResponse)(nil),                // 73: mage.v1.ConnectUserResponse
	(*ConnectAdminResponse)(nil),               // 74: mage.v1.ConnectAdminResponse
	(*ConnectSetUserDataResponse)(nil),         // 75: mage.v1.ConnectSetUserDataResponse
	(*PingResponse)(nil),                       // 76: mage.v1.PingResponse
	(*GetServerStateResponse)(nil),             // 77: mage.v1.GetServerStateResponse
	(*ServerGetPromotionMessagesResponse)(nil), // 78: mage.v1.ServerGetPromotionMessagesResponse
	(*ServerAddFeedbackMessageResponse)(nil),   // 79: mage.v1.ServerAddFeedbackMessageResponse
	(*ServerGetMainRoomIdResponse)(nil),        // 80: mage.v1.ServerGetMainRoomIdResponse
	(*RoomGetUsersResponse)(nil),               // 81: mage.v1.RoomGetUsersResponse
	(*RoomGetFinishedMatchesResponse)(nil),     // 82: mage.v1.RoomGetFinishedMatchesResponse
	(*RoomGetAllTablesResponse)(nil),           // 83: mage.v1.RoomGetAllTablesResponse
	(*RoomGetTableByIdResponse)(nil),           // 84: mage.v1.RoomGetTableByIdResponse
	(*RoomCreateTableResponse)(nil),            // 85: mage.v1.RoomCreateTableResponse
	(*RoomCreateTournamentResponse)(nil),       // 86: mage.v1.RoomCreateTournamentResponse
	(*RoomJoinTableResponse)(nil),              // 87: mage.v1.RoomJoinTableResponse
	(*RoomJoinTournamentResponse)(nil),         // 88: mage.v1.RoomJoinTournamentResponse
	(*RoomLeaveTableOrTournamentResponse)(nil), // 89: mage.v1.RoomLeaveTableOrTournamentResponse
	(*RoomWatchTableResponse)(nil),             // 90: mage.v1.RoomWatchTableResponse
	(*RoomWatchTournamentResponse)(nil),        // 91: mage.v1.RoomWatchTournamentResponse
	(*TableSwapSeatsResponse)(nil),             // 92: mage.v1.TableSwapSeatsResponse
	(*TableRemoveResponse)(nil),                // 93: mage.v1.TableRemoveResponse
	(*TableIsOwnerResponse)(nil),               // 94: mage.v1.TableIsOwnerResponse
	(*DeckSubmitResponse)(nil),                 // 95: mage.v1.DeckSubmitResponse
	(*DeckSaveResponse)(nil),                   // 96: mage.v1.DeckSaveResponse
	(*GameJoinResponse)(nil),                   // 97: mage.v1.GameJoinResponse
	(*GameWatchStartResponse)(nil),             // 98: mage.v1.GameWatchStartResponse
	(*GameWatchStopResponse)(nil),              // 99: mage.v1.GameWatchStopResponse
	(*GameGetViewResponse)(nil),                // 100: mage.v1.GameGetViewResponse
	(*SendPlayerUUIDResponse)(nil),             // 101: mage.v1.SendPlayerUUIDResponse
	(*SendPlayerStringResponse)(nil),           // 102: mage.v1.SendPlayerStringResponse
	(*SendPlayerBooleanResponse)(nil),          // 103: mage.v1.SendPlayerBooleanResponse
	(*SendPlayerIntegerResponse)(nil),          // 104: mage.v1.SendPlayerIntegerResponse
	(*SendPlayerManaTypeResponse)(nil),         // 105: mage.v1.SendPlayerManaTypeResponse
	(*SendPlayerActionResponse)(nil),           // 106: mage.v1.SendPlayerActionResponse
	(*MatchStartResponse)(nil),                 // 107: mage.v1.MatchStartResponse
	(*MatchQuitResponse)(nil),                  // 108: mage.v1.MatchQuitResponse
	(*DraftJoinResponse)(nil),                  // 109: mage.v1.DraftJoinResponse
	(*SendDraftCardPickResponse)(nil),          // 110: mage.v1.SendDraftCardPickResponse
	(*SendDraftCardMarkResponse)(nil),          // 111: mage.v1.SendDraftCardMarkResponse
	(*DraftSetBoosterLoadedResponse)(nil),      // 112: mage.v1.DraftSetBoosterLoadedResponse
	(*DraftQuitResponse)(nil),                  // 113: mage.v1.DraftQuitResponse
	(*TournamentJoinResponse)(nil),             // 114: mage.v1.TournamentJoinResponse
	(*TournamentStartResponse)(nil),            // 115: mage.v1.TournamentStartResponse
	(*TournamentQuitResponse)(nil),             // 116: mage.v1.TournamentQuitResponse
	(*TournamentFindByIdResponse)(nil),         // 117: mage.v1.TournamentFindByIdResponse
	(*ChatJoinResponse)(nil),                   // 118: mage.v1.ChatJoinResponse
	(*ChatLeaveResponse)(nil),                  // 119: mage.v1.ChatLeaveResponse
	(*ChatSendMessageResponse)(nil),            // 120: mage.v1.ChatSendMessageResponse
	(*ChatFindByTableResponse)(nil),            // 121: mage.v1.ChatFindByTableResponse
	(*ChatFindByGameResponse)(nil),             // 122: mage.v1.ChatFindByGameResponse
	(*ChatFindByTournamentResponse)(nil),       // 123: mage.v1.ChatFindByTournamentResponse
	(*ChatFindByRoomResponse)(nil),             // 124: mage.v1.ChatFindByRoomResponse
	(*ReplayInitResponse)(nil),                 // 125: mage.v1.ReplayInitResponse
	(*ReplayStartResponse)(nil),                // 126: mage.v1.ReplayStartResponse
	(*ReplayStopResponse)(nil),                 // 127: mage.v1.ReplayStopResponse
	(*ReplayNextResponse)(nil),                 // 128: mage.v1.ReplayNextResponse
	(*ReplayPreviousResponse)(nil),             // 129: mage.v1.ReplayPreviousResponse
	(*ReplaySkipForwardResponse)(nil),          // 130: mage.v1.ReplaySkipForwardResponse
	(*AdminGetUsersResponse)(nil),              // 131: mage.v1.AdminGetUsersResponse
	(*AdminDisconnectUserResponse)(nil),        // 132: mage.v1.AdminDisconnectUserResponse
	(*AdminMuteUserResponse)(nil),              // 133: mage.v1.AdminMuteUserResponse
	(*AdminLockUserResponse)(nil),              // 134: mage.v1.AdminLockUserResponse
	(*AdminActivateUserResponse)(nil),          // 135: mage.v1.AdminActivateUserResponse
	(*AdminToggleActivateUserResponse)(nil),    // 136: mage.v1.AdminToggleActivateUserResponse
	(*AdminEndUserSessionResponse)(nil),        // 137: mage.v1.AdminEndUserSessionResponse
	(*AdminTableRemoveResponse)(nil),           // 138: mage.v1.AdminTableRemoveResponse
	(*AdminSendBroadcastMessageResponse)(nil),  // 139: mage.v1.AdminSendBroadcastMessageResponse
}
var file_mage_v1_server_proto_depIdxs = []int32{
	0,   // 0: mage.v1.MageServer.AuthRegister:input_type -> mage.v1.AuthRegisterRequest
	1,   // 1: mage.v1.MageServer.AuthSendTokenToEmail:input_type -> mage.v1.AuthSendTokenToEmailRequest
	2,   // 2: mage.v1.MageServer.AuthResetPassword:input_type -> mage.v1.AuthResetPasswordRequest
	3,   // 3: mage.v1.MageServer.ConnectUser:input_type -> mage.v1.ConnectUserRequest
	4,   // 4: mage.v1.MageServer.ConnectAdmin:input_type -> mage.v1.ConnectAdminRequest
	5,   // 5: mage.v1.MageServer.ConnectSetUserData:input_type -> mage.v1.ConnectSetUserDataRequest
	6,   // 6: mage.v1.MageServer.Ping:input_type -> mage.v1.PingRequest
	7,   // 7: mage.v1.MageServer.GetServerState:input_type -> mage.v1.GetServerStateRequest
	8,   // 8: mage.v1.MageServer.ServerGetPromotionMessages:input_type -> mage.v1.ServerGetPromotionMessagesRequest
	9,   // 9: mage.v1.MageServer.ServerAddFeedbackMessage:input_type -> mage.v1.ServerAddFeedbackMessageRequest
	10,  // 10: mage.v1.MageServer.ServerGetMainRoomId:input_type -> mage.v1.ServerGetMainRoomIdRequest
	11,  // 11: mage.v1.MageServer.RoomGetUsers:input_type -> mage.v1.RoomGetUsersRequest
	12,  // 12: mage.v1.MageServer.RoomGetFinishedMatches:input_type -> mage.v1.RoomGetFinishedMatchesRequest
	13,  // 13: mage.v1.MageServer.RoomGetAllTables:input_type -> mage.v1.RoomGetAllTablesRequest
	14,  // 14: mage.v1.MageServer.RoomGetTableById:input_type -> mage.v1.RoomGetTableByIdRequest
	15,  // 15: mage.v1.MageServer.RoomCreateTable:input_type -> mage.v1.RoomCreateTableRequest
	16,  // 16: mage.v1.MageServer.RoomCreateTournament:input_type -> mage.v1.RoomCreateTournamentRequest
	17,  // 17: mage.v1.MageServer.RoomJoinTable:input_type -> mage.v1.RoomJoinTableRequest
	18,  // 18: mage.v1.MageServer.RoomJoinTournament:input_type -> mage.v1.RoomJoinTournamentRequest
	19,  // 19: mage.v1.MageServer.RoomLeaveTableOrTournament:input_type -> mage.v1.RoomLeaveTableOrTournamentRequest
	20,  // 20: mage.v1.MageServer.RoomWatchTable:input_type -> mage.v1.RoomWatchTableRequest
	21,  // 21: mage.v1.MageServer.RoomWatchTournament:input_type -> mage.v1.RoomWatchTournamentRequest
	22,  // 22: mage.v1.MageServer.TableSwapSeats:input_type -> mage.v1.TableSwapSeatsRequest
	23,  // 23: mage.v1.MageServer.TableRemove:input_type -> mage.v1.TableRemoveRequest
	24,  // 24: mage.v1.MageServer.TableIsOwner:input_type -> mage.v1.TableIsOwnerRequest
	25,  // 25: mage.v1.MageServer.DeckSubmit:input_type -> mage.v1.DeckSubmitRequest
	26,  // 26: mage.v1.MageServer.DeckSave:input_type -> mage.v1.DeckSaveRequest
	27,  // 27: mage.v1.MageServer.GameJoin:input_type -> mage.v1.GameJoinRequest
	28,  // 28: mage.v1.MageServer.GameWatchStart:input_type -> mage.v1.GameWatchStartRequest
	29,  // 29: mage.v1.MageServer.GameWatchStop:input_type -> mage.v1.GameWatchStopRequest
	30,  // 30: mage.v1.MageServer.GameGetView:input_type -> mage.v1.GameGetViewRequest
	31,  // 31: mage.v1.MageServer.SendPlayerUUID:input_type -> mage.v1.SendPlayerUUIDRequest
	32,  // 32: mage.v1.MageServer.SendPlayerString:input_type -> mage.v1.SendPlayerStringRequest
	33,  // 33: mage.v1.MageServer.SendPlayerBoolean:input_type -> mage.v1.SendPlayerBooleanRequest
	34,  // 34: mage.v1.MageServer.SendPlayerInteger:input_type -> mage.v1.SendPlayerIntegerRequest
	35,  // 35: mage.v1.MageServer.SendPlayerManaType:input_type -> mage.v1.SendPlayerManaTypeRequest
	36,  // 36: mage.v1.MageServer.SendPlayerAction:input_type -> mage.v1.SendPlayerActionRequest
	37,  // 37: mage.v1.MageServer.MatchStart:input_type -> mage.v1.MatchStartRequest
	38,  // 38: mage.v1.MageServer.MatchQuit:input_type -> mage.v1.MatchQuitRequest
	39,  // 39: mage.v1.MageServer.DraftJoin:input_type -> mage.v1.DraftJoinRequest
	40,  // 40: mage.v1.MageServer.SendDraftCardPick:input_type -> mage.v1.SendDraftCardPickRequest
	41,  // 41: mage.v1.MageServer.SendDraftCardMark:input_type -> mage.v1.SendDraftCardMarkRequest
	42,  // 42: mage.v1.MageServer.DraftSetBoosterLoaded:input_type -> mage.v1.DraftSetBoosterLoadedRequest
	43,  // 43: mage.v1.MageServer.DraftQuit:input_type -> mage.v1.DraftQuitRequest
	44,  // 44: mage.v1.MageServer.TournamentJoin:input_type -> mage.v1.TournamentJoinRequest
	45,  // 45: mage.v1.MageServer.TournamentStart:input_type -> mage.v1.TournamentStartRequest
	46,  // 46: mage.v1.MageServer.TournamentQuit:input_type -> mage.v1.TournamentQuitRequest
	47,  // 47: mage.v1.MageServer.TournamentFindById:input_type -> mage.v1.TournamentFindByIdRequest
	48,  // 48: mage.v1.MageServer.ChatJoin:input_type -> mage.v1.ChatJoinRequest
	49,  // 49: mage.v1.MageServer.ChatLeave:input_type -> mage.v1.ChatLeaveRequest
	50,  // 50: mage.v1.MageServer.ChatSendMessage:input_type -> mage.v1.ChatSendMessageRequest
	51,  // 51: mage.v1.MageServer.ChatFindByTable:input_type -> mage.v1.ChatFindByTableRequest
	52,  // 52: mage.v1.MageServer.ChatFindByGame:input_type -> mage.v1.ChatFindByGameRequest
	53,  // 53: mage.v1.MageServer.ChatFindByTournament:input_type -> mage.v1.ChatFindByTournamentRequest
	54,  // 54: mage.v1.MageServer.ChatFindByRoom:input_type -> mage.v1.ChatFindByRoomRequest
	55,  // 55: mage.v1.MageServer.ReplayInit:input_type -> mage.v1.ReplayInitRequest
	56,  // 56: mage.v1.MageServer.ReplayStart:input_type -> mage.v1.ReplayStartRequest
	57,  // 57: mage.v1.MageServer.ReplayStop:input_type -> mage.v1.ReplayStopRequest
	58,  // 58: mage.v1.MageServer.ReplayNext:input_type -> mage.v1.ReplayNextRequest
	59,  // 59: mage.v1.MageServer.ReplayPrevious:input_type -> mage.v1.ReplayPreviousRequest
	60,  // 60: mage.v1.MageServer.ReplaySkipForward:input_type -> mage.v1.ReplaySkipForwardRequest
	61,  // 61: mage.v1.MageServer.AdminGetUsers:input_type -> mage.v1.AdminGetUsersRequest
	62,  // 62: mage.v1.MageServer.AdminDisconnectUser:input_type -> mage.v1.AdminDisconnectUserRequest
	63,  // 63: mage.v1.MageServer.AdminMuteUser:input_type -> mage.v1.AdminMuteUserRequest
	64,  // 64: mage.v1.MageServer.AdminLockUser:input_type -> mage.v1.AdminLockUserRequest
	65,  // 65: mage.v1.MageServer.AdminActivateUser:input_type -> mage.v1.AdminActivateUserRequest
	66,  // 66: mage.v1.MageServer.AdminToggleActivateUser:input_type -> mage.v1.AdminToggleActivateUserRequest
	67,  // 67: mage.v1.MageServer.AdminEndUserSession:input_type -> mage.v1.AdminEndUserSessionRequest
	68,  // 68: mage.v1.MageServer.AdminTableRemove:input_type -> mage.v1.AdminTableRemoveRequest
	69,  // 69: mage.v1.MageServer.AdminSendBroadcastMessage:input_type -> mage.v1.AdminSendBroadcastMessageRequest
	70,  // 70: mage.v1.MageServer.AuthRegister:output_type -> mage.v1.AuthRegisterResponse
	71,  // 71: mage.v1.MageServer.AuthSendTokenToEmail:output_type -> mage.v1.AuthSendTokenToEmailResponse
	72,  // 72: mage.v1.MageServer.AuthResetPassword:output_type -> mage.v1.AuthResetPasswordResponse
	73,  // 73: mage.v1.MageServer.ConnectUser:output_type -> mage.v1.ConnectUserResponse
	74,  // 74: mage.v1.MageServer.ConnectAdmin:output_type -> mage.v1.ConnectAdminResponse
	75,  // 75: mage.v1.MageServer.ConnectSetUserData:output_type -> mage.v1.ConnectSetUserDataResponse
	76,  // 76: mage.v1.MageServer.Ping:output_type -> mage.v1.PingResponse
	77,  // 77: mage.v1.MageServer.GetServerState:output_type -> mage.v1.GetServerStateResponse
	78,  // 78: mage.v1.MageServer.ServerGetPromotionMessages:output_type -> mage.v1.ServerGetPromotionMessagesResponse
	79,  // 79: mage.v1.MageServer.ServerAddFeedbackMessage:output_type -> mage.v1.ServerAddFeedbackMessageResponse
	80,  // 80: mage.v1.MageServer.ServerGetMainRoomId:output_type -> mage.v1.ServerGetMainRoomIdResponse
	81,  // 81: mage.v1.MageServer.RoomGetUsers:output_type -> mage.v1.RoomGetUsersResponse
	82,  // 82: mage.v1.MageServer.RoomGetFinishedMatches:output_type -> mage.v1.RoomGetFinishedMatchesResponse
	83,  // 83: mage.v1.MageServer.RoomGetAllTables:output_type -> mage.v1.RoomGetAllTablesResponse
	84,  // 84: mage.v1.MageServer.RoomGetTableById:output_type -> mage.v1.RoomGetTableByIdResponse
	85,  // 85: mage.v1.MageServer.RoomCreateTable:output_type -> mage.v1.RoomCreateTableResponse
	86,  // 86: mage.v1.MageServer.RoomCreateTournament:output_type -> mage.v1.RoomCreateTournamentResponse
	87,  // 87: mage.v1.MageServer.RoomJoinTable:output_type -> mage.v1.RoomJoinTableResponse
	88,  // 88: mage.v1.MageServer.RoomJoinTournament:output_type -> mage.v1.RoomJoinTournamentResponse
	89,  // 89: mage.v1.MageServer.RoomLeaveTableOrTournament:output_type -> mage.v1.RoomLeaveTableOrTournamentResponse
	90,  // 90: mage.v1.MageServer.RoomWatchTable:output_type -> mage.v1.RoomWatchTableResponse
	91,  // 91: mage.v1.MageServer.RoomWatchTournament:output_type -> mage.v1.RoomWatchTournamentResponse
	92,  // 92: mage.v1.MageServer.TableSwapSeats:output_type -> mage.v1.TableSwapSeatsResponse
	93,  // 93: mage.v1.MageServer.TableRemove:output_type -> mage.v1.TableRemoveResponse
	94,  // 94: mage.v1.MageServer.TableIsOwner:output_type -> mage.v1.TableIsOwnerResponse
	95,  // 95: mage.v1.MageServer.DeckSubmit:output_type -> mage.v1.DeckSubmitResponse
	96,  // 96: mage.v1.MageServer.DeckSave:output_type -> mage.v1.DeckSaveResponse
	97,  // 97: mage.v1.MageServer.GameJoin:output_type -> mage.v1.GameJoinResponse
	98,  // 98: mage.v1.MageServer.GameWatchStart:output_type -> mage.v1.GameWatchStartResponse
	99,  // 99: mage.v1.MageServer.GameWatchStop:output_type -> mage.v1.GameWatchStopResponse
	100, // 100: mage.v1.MageServer.GameGetView:output_type -> mage.v1.GameGetViewResponse
	101, // 101: mage.v1.MageServer.SendPlayerUUID:output_type -> mage.v1.SendPlayerUUIDResponse
	102, // 102: mage.v1.MageServer.SendPlayerString:output_type -> mage.v1.SendPlayerStringResponse
	103, // 103: mage.v1.MageServer.SendPlayerBoolean:output_type -> mage.v1.SendPlayerBooleanResponse
	104, // 104: mage.v1.MageServer.SendPlayerInteger:output_type -> mage.v1.SendPlayerIntegerResponse
	105, // 105: mage.v1.MageServer.SendPlayerManaType:output_type -> mage.v1.SendPlayerManaTypeResponse
	106, // 106: mage.v1.MageServer.SendPlayerAction:output_type -> mage.v1.SendPlayerActionResponse
	107, // 107: mage.v1.MageServer.MatchStart:output_type -> mage.v1.MatchStartResponse
	108, // 108: mage.v1.MageServer.MatchQuit:output_type -> mage.v1.MatchQuitResponse
	109, // 109: mage.v1.MageServer.DraftJoin:output_type -> mage.v1.DraftJoinResponse
	110, // 110: mage.v1.MageServer.SendDraftCardPick:output_type -> mage.v1.SendDraftCardPickResponse
	111, // 111: mage.v1.MageServer.SendDraftCardMark:output_type -> mage.v1.SendDraftCardMarkResponse
	112, // 112: mage.v1.MageServer.DraftSetBoosterLoaded:output_type -> mage.v1.DraftSetBoosterLoadedResponse
	113, // 113: mage.v1.MageServer.DraftQuit:output_type -> mage.v1.DraftQuitResponse
	114, // 114: mage.v1.MageServer.TournamentJoin:output_type -> mage.v1.TournamentJoinResponse
	115, // 115: mage.v1.MageServer.TournamentStart:output_type -> mage.v1.TournamentStartResponse
	116, // 116: mage.v1.MageServer.TournamentQuit:output_type -> mage.v1.TournamentQuitResponse
	117, // 117: mage.v1.MageServer.TournamentFindById:output_type -> mage.v1.TournamentFindByIdResponse
	118, // 118: mage.v1.MageServer.ChatJoin:output_type -> mage.v1.ChatJoinResponse
	119, // 119: mage.v1.MageServer.ChatLeave:output_type -> mage.v1.ChatLeaveResponse
	120, // 120: mage.v1.MageServer.ChatSendMessage:output_type -> mage.v1.ChatSendMessageResponse
	121, // 121: mage.v1.MageServer.ChatFindByTable:output_type -> mage.v1.ChatFindByTableResponse
	122, // 122: mage.v1.MageServer.ChatFindByGame:output_type -> mage.v1.ChatFindByGameResponse
	123, // 123: mage.v1.MageServer.ChatFindByTournament:output_type -> mage.v1.ChatFindByTournamentResponse
	124, // 124: mage.v1.MageServer.ChatFindByRoom:output_type -> mage.v1.ChatFindByRoomResponse
	125, // 125: mage.v1.MageServer.ReplayInit:output_type -> mage.v1.ReplayInitResponse
	126, // 126: mage.v1.MageServer.ReplayStart:output_type -> mage.v1.ReplayStartResponse
	127, // 127: mage.v1.MageServer.ReplayStop:output_type -> mage.v1.ReplayStopResponse
	128, // 128: mage.v1.MageServer.ReplayNext:output_type -> mage.v1.ReplayNextResponse
	129, // 129: mage.v1.MageServer.ReplayPrevious:output_type -> mage.v1.ReplayPreviousResponse
	130, // 130: mage.v1.MageServer.ReplaySkipForward:output_type -> mage.v1.ReplaySkipForwardResponse
	131, // 131: mage.v1.MageServer.AdminGetUsers:output_type -> mage.v1.AdminGetUsersResponse
	132, // 132: mage.v1.MageServer.AdminDisconnectUser:output_type -> mage.v1.AdminDisconnectUserResponse
	133, // 133: mage.v1.MageServer.AdminMuteUser:output_type -> mage.v1.AdminMuteUserResponse
	134, // 134: mage.v1.MageServer.AdminLockUser:output_type -> mage.v1.AdminLockUserResponse
	135, // 135: mage.v1.MageServer.AdminActivateUser:output_type -> mage.v1.AdminActivateUserResponse
	136, // 136: mage.v1.MageServer.AdminToggleActivateUser:output_type -> mage.v1.AdminToggleActivateUserResponse
	137, // 137: mage.v1.MageServer.AdminEndUserSession:output_type -> mage.v1.AdminEndUserSessionResponse
	138, // 138: mage.v1.MageServer.AdminTableRemove:output_type -> mage.v1.AdminTableRemoveResponse
	139, // 139: mage.v1.MageServer.AdminSendBroadcastMessage:output_type -> mage.v1.AdminSendBroadcastMessageResponse
	70,  // [70:140] is the sub-list for method output_type
	0,   // [0:70] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_mage_v1_server_proto_init() }
func file_mage_v1_server_proto_init() {
	if File_mage_v1_server_proto != nil {
		return
	}
	file_mage_v1_auth_proto_init()
	file_mage_v1_room_proto_init()
	file_mage_v1_table_proto_init()
	file_mage_v1_game_proto_init()
	file_mage_v1_tournament_proto_init()
	file_mage_v1_draft_proto_init()
	file_mage_v1_chat_proto_init()
	file_mage_v1_admin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_server_proto_rawDesc), len(file_mage_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mage_v1_server_proto_goTypes,
		DependencyIndexes: file_mage_v1_server_proto_depIdxs,
	}.Build()
	File_mage_v1_server_proto = out.File
	file_mage_v1_server_proto_goTypes = nil
	file_mage_v1_server_proto_depIdxs = nil
}
