// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/table.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomCreateTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MatchOptions  *MatchOptions          `protobuf:"bytes,3,opt,name=match_options,json=matchOptions,proto3" json:"match_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreateTableRequest) Reset() {
	*x = RoomCreateTableRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateTableRequest) ProtoMessage() {}

func (x *RoomCreateTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateTableRequest.ProtoReflect.Descriptor instead.
func (*RoomCreateTableRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{0}
}

func (x *RoomCreateTableRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomCreateTableRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomCreateTableRequest) GetMatchOptions() *MatchOptions {
	if x != nil {
		return x.MatchOptions
	}
	return nil
}

type RoomCreateTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreateTableResponse) Reset() {
	*x = RoomCreateTableResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateTableResponse) ProtoMessage() {}

func (x *RoomCreateTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateTableResponse.ProtoReflect.Descriptor instead.
func (*RoomCreateTableResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{1}
}

func (x *RoomCreateTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomCreateTableResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RoomCreateTableResponse) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type RoomCreateTournamentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId            string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TournamentOptions *TournamentOptions     `protobuf:"bytes,3,opt,name=tournament_options,json=tournamentOptions,proto3" json:"tournament_options,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoomCreateTournamentRequest) Reset() {
	*x = RoomCreateTournamentRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateTournamentRequest) ProtoMessage() {}

func (x *RoomCreateTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateTournamentRequest.ProtoReflect.Descriptor instead.
func (*RoomCreateTournamentRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{2}
}

func (x *RoomCreateTournamentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomCreateTournamentRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomCreateTournamentRequest) GetTournamentOptions() *TournamentOptions {
	if x != nil {
		return x.TournamentOptions
	}
	return nil
}

type TournamentOptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TournamentType      string                 `protobuf:"bytes,2,opt,name=tournament_type,json=tournamentType,proto3" json:"tournament_type,omitempty"`
	NumWins             int32                  `protobuf:"varint,3,opt,name=num_wins,json=numWins,proto3" json:"num_wins,omitempty"`
	ConstructedDeckSize int32                  `protobuf:"varint,4,opt,name=constructed_deck_size,json=constructedDeckSize,proto3" json:"constructed_deck_size,omitempty"`
	DraftCubeId         int32                  `protobuf:"varint,5,opt,name=draft_cube_id,json=draftCubeId,proto3" json:"draft_cube_id,omitempty"`
	LimitedPacks        int32                  `protobuf:"varint,6,opt,name=limited_packs,json=limitedPacks,proto3" json:"limited_packs,omitempty"`
	NumRounds           int32                  `protobuf:"varint,7,opt,name=num_rounds,json=numRounds,proto3" json:"num_rounds,omitempty"`
	FreeMulligans       int32                  `protobuf:"varint,8,opt,name=free_mulligans,json=freeMulligans,proto3" json:"free_mulligans,omitempty"`
	DraftTiming         string                 `protobuf:"bytes,9,opt,name=draft_timing,json=draftTiming,proto3" json:"draft_timing,omitempty"`
	Rated               bool                   `protobuf:"varint,10,opt,name=rated,proto3" json:"rated,omitempty"`
	QuitRatio           int32                  `protobuf:"varint,11,opt,name=quit_ratio,json=quitRatio,proto3" json:"quit_ratio,omitempty"`
	MinimumRating       int32                  `protobuf:"varint,12,opt,name=minimum_rating,json=minimumRating,proto3" json:"minimum_rating,omitempty"`
	Sets                []string               `protobuf:"bytes,13,rep,name=sets,proto3" json:"sets,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TournamentOptions) Reset() {
	*x = TournamentOptions{}
	mi := &file_mage_v1_table_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentOptions) ProtoMessage() {}

func (x *TournamentOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentOptions.ProtoReflect.Descriptor instead.
func (*TournamentOptions) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{3}
}

func (x *TournamentOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TournamentOptions) GetTournamentType() string {
	if x != nil {
		return x.TournamentType
	}
	return ""
}

func (x *TournamentOptions) GetNumWins() int32 {
	if x != nil {
		return x.NumWins
	}
	return 0
}

func (x *TournamentOptions) GetConstructedDeckSize() int32 {
	if x != nil {
		return x.ConstructedDeckSize
	}
	return 0
}

func (x *TournamentOptions) GetDraftCubeId() int32 {
	if x != nil {
		return x.DraftCubeId
	}
	return 0
}

func (x *TournamentOptions) GetLimitedPacks() int32 {
	if x != nil {
		return x.LimitedPacks
	}
	return 0
}

func (x *TournamentOptions) GetNumRounds() int32 {
	if x != nil {
		return x.NumRounds
	}
	return 0
}

func (x *TournamentOptions) GetFreeMulligans() int32 {
	if x != nil {
		return x.FreeMulligans
	}
	return 0
}

func (x *TournamentOptions) GetDraftTiming() string {
	if x != nil {
		return x.DraftTiming
	}
	return ""
}

func (x *TournamentOptions) GetRated() bool {
	if x != nil {
		return x.Rated
	}
	return false
}

func (x *TournamentOptions) GetQuitRatio() int32 {
	if x != nil {
		return x.QuitRatio
	}
	return 0
}

func (x *TournamentOptions) GetMinimumRating() int32 {
	if x != nil {
		return x.MinimumRating
	}
	return 0
}

func (x *TournamentOptions) GetSets() []string {
	if x != nil {
		return x.Sets
	}
	return nil
}

type RoomCreateTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TournamentId  string                 `protobuf:"bytes,3,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreateTournamentResponse) Reset() {
	*x = RoomCreateTournamentResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateTournamentResponse) ProtoMessage() {}

func (x *RoomCreateTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateTournamentResponse.ProtoReflect.Descriptor instead.
func (*RoomCreateTournamentResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{4}
}

func (x *RoomCreateTournamentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomCreateTournamentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RoomCreateTournamentResponse) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type RoomJoinTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,4,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PlayerType    string                 `protobuf:"bytes,5,opt,name=player_type,json=playerType,proto3" json:"player_type,omitempty"`
	SkillLevel    int32                  `protobuf:"varint,6,opt,name=skill_level,json=skillLevel,proto3" json:"skill_level,omitempty"`
	DeckList      string                 `protobuf:"bytes,7,opt,name=deck_list,json=deckList,proto3" json:"deck_list,omitempty"`
	Password      string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinTableRequest) Reset() {
	*x = RoomJoinTableRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinTableRequest) ProtoMessage() {}

func (x *RoomJoinTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinTableRequest.ProtoReflect.Descriptor instead.
func (*RoomJoinTableRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{5}
}

func (x *RoomJoinTableRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomJoinTableRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomJoinTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *RoomJoinTableRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *RoomJoinTableRequest) GetPlayerType() string {
	if x != nil {
		return x.PlayerType
	}
	return ""
}

func (x *RoomJoinTableRequest) GetSkillLevel() int32 {
	if x != nil {
		return x.SkillLevel
	}
	return 0
}

func (x *RoomJoinTableRequest) GetDeckList() string {
	if x != nil {
		return x.DeckList
	}
	return ""
}

func (x *RoomJoinTableRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RoomJoinTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinTableResponse) Reset() {
	*x = RoomJoinTableResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinTableResponse) ProtoMessage() {}

func (x *RoomJoinTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinTableResponse.ProtoReflect.Descriptor instead.
func (*RoomJoinTableResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{6}
}

func (x *RoomJoinTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomJoinTableResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoomJoinTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TournamentId  string                 `protobuf:"bytes,3,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,4,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PlayerType    string                 `protobuf:"bytes,5,opt,name=player_type,json=playerType,proto3" json:"player_type,omitempty"`
	SkillLevel    int32                  `protobuf:"varint,6,opt,name=skill_level,json=skillLevel,proto3" json:"skill_level,omitempty"`
	DeckList      string                 `protobuf:"bytes,7,opt,name=deck_list,json=deckList,proto3" json:"deck_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinTournamentRequest) Reset() {
	*x = RoomJoinTournamentRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinTournamentRequest) ProtoMessage() {}

func (x *RoomJoinTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinTournamentRequest.ProtoReflect.Descriptor instead.
func (*RoomJoinTournamentRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{7}
}

func (x *RoomJoinTournamentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomJoinTournamentRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomJoinTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *RoomJoinTournamentRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *RoomJoinTournamentRequest) GetPlayerType() string {
	if x != nil {
		return x.PlayerType
	}
	return ""
}

func (x *RoomJoinTournamentRequest) GetSkillLevel() int32 {
	if x != nil {
		return x.SkillLevel
	}
	return 0
}

func (x *RoomJoinTournamentRequest) GetDeckList() string {
	if x != nil {
		return x.DeckList
	}
	return ""
}

type RoomJoinTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinTournamentResponse) Reset() {
	*x = RoomJoinTournamentResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinTournamentResponse) ProtoMessage() {}

func (x *RoomJoinTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinTournamentResponse.ProtoReflect.Descriptor instead.
func (*RoomJoinTournamentResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{8}
}

func (x *RoomJoinTournamentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomJoinTournamentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoomLeaveTableOrTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeaveTableOrTournamentRequest) Reset() {
	*x = RoomLeaveTableOrTournamentRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeaveTableOrTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeaveTableOrTournamentRequest) ProtoMessage() {}

func (x *RoomLeaveTableOrTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeaveTableOrTournamentRequest.ProtoReflect.Descriptor instead.
func (*RoomLeaveTableOrTournamentRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{9}
}

func (x *RoomLeaveTableOrTournamentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomLeaveTableOrTournamentRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomLeaveTableOrTournamentRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type RoomLeaveTableOrTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeaveTableOrTournamentResponse) Reset() {
	*x = RoomLeaveTableOrTournamentResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeaveTableOrTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeaveTableOrTournamentResponse) ProtoMessage() {}

func (x *RoomLeaveTableOrTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeaveTableOrTournamentResponse.ProtoReflect.Descriptor instead.
func (*RoomLeaveTableOrTournamentResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{10}
}

func (x *RoomLeaveTableOrTournamentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomLeaveTableOrTournamentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoomWatchTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomWatchTableRequest) Reset() {
	*x = RoomWatchTableRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomWatchTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomWatchTableRequest) ProtoMessage() {}

func (x *RoomWatchTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomWatchTableRequest.ProtoReflect.Descriptor instead.
func (*RoomWatchTableRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{11}
}

func (x *RoomWatchTableRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomWatchTableRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomWatchTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type RoomWatchTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomWatchTableResponse) Reset() {
	*x = RoomWatchTableResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomWatchTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomWatchTableResponse) ProtoMessage() {}

func (x *RoomWatchTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomWatchTableResponse.ProtoReflect.Descriptor instead.
func (*RoomWatchTableResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{12}
}

func (x *RoomWatchTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomWatchTableResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoomWatchTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TournamentId  string                 `protobuf:"bytes,3,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomWatchTournamentRequest) Reset() {
	*x = RoomWatchTournamentRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomWatchTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomWatchTournamentRequest) ProtoMessage() {}

func (x *RoomWatchTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomWatchTournamentRequest.ProtoReflect.Descriptor instead.
func (*RoomWatchTournamentRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{13}
}

func (x *RoomWatchTournamentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomWatchTournamentRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomWatchTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type RoomWatchTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomWatchTournamentResponse) Reset() {
	*x = RoomWatchTournamentResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomWatchTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomWatchTournamentResponse) ProtoMessage() {}

func (x *RoomWatchTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomWatchTournamentResponse.ProtoReflect.Descriptor instead.
func (*RoomWatchTournamentResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{14}
}

func (x *RoomWatchTournamentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoomWatchTournamentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TableSwapSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	SeatNum1      int32                  `protobuf:"varint,4,opt,name=seat_num1,json=seatNum1,proto3" json:"seat_num1,omitempty"`
	SeatNum2      int32                  `protobuf:"varint,5,opt,name=seat_num2,json=seatNum2,proto3" json:"seat_num2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSwapSeatsRequest) Reset() {
	*x = TableSwapSeatsRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSwapSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSwapSeatsRequest) ProtoMessage() {}

func (x *TableSwapSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSwapSeatsRequest.ProtoReflect.Descriptor instead.
func (*TableSwapSeatsRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{15}
}

func (x *TableSwapSeatsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TableSwapSeatsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TableSwapSeatsRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *TableSwapSeatsRequest) GetSeatNum1() int32 {
	if x != nil {
		return x.SeatNum1
	}
	return 0
}

func (x *TableSwapSeatsRequest) GetSeatNum2() int32 {
	if x != nil {
		return x.SeatNum2
	}
	return 0
}

type TableSwapSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSwapSeatsResponse) Reset() {
	*x = TableSwapSeatsResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSwapSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSwapSeatsResponse) ProtoMessage() {}

func (x *TableSwapSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSwapSeatsResponse.ProtoReflect.Descriptor instead.
func (*TableSwapSeatsResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{16}
}

func (x *TableSwapSeatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TableSwapSeatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TableRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRemoveRequest) Reset() {
	*x = TableRemoveRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRemoveRequest) ProtoMessage() {}

func (x *TableRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRemoveRequest.ProtoReflect.Descriptor instead.
func (*TableRemoveRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{17}
}

func (x *TableRemoveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TableRemoveRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TableRemoveRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type TableRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRemoveResponse) Reset() {
	*x = TableRemoveResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRemoveResponse) ProtoMessage() {}

func (x *TableRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRemoveResponse.ProtoReflect.Descriptor instead.
func (*TableRemoveResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{18}
}

func (x *TableRemoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TableRemoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TableIsOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableIsOwnerRequest) Reset() {
	*x = TableIsOwnerRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableIsOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableIsOwnerRequest) ProtoMessage() {}

func (x *TableIsOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableIsOwnerRequest.ProtoReflect.Descriptor instead.
func (*TableIsOwnerRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{19}
}

func (x *TableIsOwnerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TableIsOwnerRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TableIsOwnerRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type TableIsOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOwner       bool                   `protobuf:"varint,1,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableIsOwnerResponse) Reset() {
	*x = TableIsOwnerResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableIsOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableIsOwnerResponse) ProtoMessage() {}

func (x *TableIsOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableIsOwnerResponse.ProtoReflect.Descriptor instead.
func (*TableIsOwnerResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{20}
}

func (x *TableIsOwnerResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type DeckSubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TableId       string                 `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Deck          *DeckCardLists         `protobuf:"bytes,3,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckSubmitRequest) Reset() {
	*x = DeckSubmitRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckSubmitRequest) ProtoMessage() {}

func (x *DeckSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckSubmitRequest.ProtoReflect.Descriptor instead.
func (*DeckSubmitRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{21}
}

func (x *DeckSubmitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeckSubmitRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *DeckSubmitRequest) GetDeck() *DeckCardLists {
	if x != nil {
		return x.Deck
	}
	return nil
}

type DeckCardLists struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainDeck      []string               `protobuf:"bytes,1,rep,name=main_deck,json=mainDeck,proto3" json:"main_deck,omitempty"`
	Sideboard     []string               `protobuf:"bytes,2,rep,name=sideboard,proto3" json:"sideboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckCardLists) Reset() {
	*x = DeckCardLists{}
	mi := &file_mage_v1_table_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckCardLists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckCardLists) ProtoMessage() {}

func (x *DeckCardLists) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckCardLists.ProtoReflect.Descriptor instead.
func (*DeckCardLists) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{22}
}

func (x *DeckCardLists) GetMainDeck() []string {
	if x != nil {
		return x.MainDeck
	}
	return nil
}

func (x *DeckCardLists) GetSideboard() []string {
	if x != nil {
		return x.Sideboard
	}
	return nil
}

type DeckSubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckSubmitResponse) Reset() {
	*x = DeckSubmitResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckSubmitResponse) ProtoMessage() {}

func (x *DeckSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckSubmitResponse.ProtoReflect.Descriptor instead.
func (*DeckSubmitResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{23}
}

func (x *DeckSubmitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeckSubmitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeckSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeckName      string                 `protobuf:"bytes,2,opt,name=deck_name,json=deckName,proto3" json:"deck_name,omitempty"`
	Deck          *DeckCardLists         `protobuf:"bytes,3,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckSaveRequest) Reset() {
	*x = DeckSaveRequest{}
	mi := &file_mage_v1_table_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckSaveRequest) ProtoMessage() {}

func (x *DeckSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckSaveRequest.ProtoReflect.Descriptor instead.
func (*DeckSaveRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{24}
}

func (x *DeckSaveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeckSaveRequest) GetDeckName() string {
	if x != nil {
		return x.DeckName
	}
	return ""
}

func (x *DeckSaveRequest) GetDeck() *DeckCardLists {
	if x != nil {
		return x.Deck
	}
	return nil
}

type DeckSaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckSaveResponse) Reset() {
	*x = DeckSaveResponse{}
	mi := &file_mage_v1_table_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckSaveResponse) ProtoMessage() {}

func (x *DeckSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_table_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckSaveResponse.ProtoReflect.Descriptor instead.
func (*DeckSaveResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_table_proto_rawDescGZIP(), []int{25}
}

func (x *DeckSaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeckSaveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mage_v1_table_proto protoreflect.FileDescriptor

const file_mage_v1_table_proto_rawDesc = "" +
	"\n" +
	"\x13mage/v1/table.proto\x12\amage.v1\x1a\x14mage/v1/models.proto\"\x8c\x01\n" +
	"\x16RoomCreateTableRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12:\n" +
	"\rmatch_options\x18\x03 \x01(\v2\x15.mage.v1.MatchOptionsR\fmatchOptions\"d\n" +
	"\x17RoomCreateTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\"\xa0\x01\n" +
	"\x1bRoomCreateTournamentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12I\n" +
	"\x12tournament_options\x18\x03 \x01(\v2\x1a.mage.v1.TournamentOptionsR\x11tournamentOptions\"\xc1\x03\n" +
	"\x11TournamentOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0ftournament_type\x18\x02 \x01(\tR\x0etournamentType\x12\x19\n" +
	"\bnum_wins\x18\x03 \x01(\x05R\anumWins\x122\n" +
	"\x15constructed_deck_size\x18\x04 \x01(\x05R\x13constructedDeckSize\x12\"\n" +
	"\rdraft_cube_id\x18\x05 \x01(\x05R\vdraftCubeId\x12#\n" +
	"\rlimited_packs\x18\x06 \x01(\x05R\flimitedPacks\x12\x1d\n" +
	"\n" +
	"num_rounds\x18\a \x01(\x05R\tnumRounds\x12%\n" +
	"\x0efree_mulligans\x18\b \x01(\x05R\rfreeMulligans\x12!\n" +
	"\fdraft_timing\x18\t \x01(\tR\vdraftTiming\x12\x14\n" +
	"\x05rated\x18\n" +
	" \x01(\bR\x05rated\x12\x1d\n" +
	"\n" +
	"quit_ratio\x18\v \x01(\x05R\tquitRatio\x12%\n" +
	"\x0eminimum_rating\x18\f \x01(\x05R\rminimumRating\x12\x12\n" +
	"\x04sets\x18\r \x03(\tR\x04sets\"s\n" +
	"\x1cRoomCreateTournamentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rtournament_id\x18\x03 \x01(\tR\ftournamentId\"\x85\x02\n" +
	"\x14RoomJoinTableRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\x12\x1f\n" +
	"\vplayer_name\x18\x04 \x01(\tR\n" +
	"playerName\x12\x1f\n" +
	"\vplayer_type\x18\x05 \x01(\tR\n" +
	"playerType\x12\x1f\n" +
	"\vskill_level\x18\x06 \x01(\x05R\n" +
	"skillLevel\x12\x1b\n" +
	"\tdeck_list\x18\a \x01(\tR\bdeckList\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\"G\n" +
	"\x15RoomJoinTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf8\x01\n" +
	"\x19RoomJoinTournamentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12#\n" +
	"\rtournament_id\x18\x03 \x01(\tR\ftournamentId\x12\x1f\n" +
	"\vplayer_name\x18\x04 \x01(\tR\n" +
	"playerName\x12\x1f\n" +
	"\vplayer_type\x18\x05 \x01(\tR\n" +
	"playerType\x12\x1f\n" +
	"\vskill_level\x18\x06 \x01(\x05R\n" +
	"skillLevel\x12\x1b\n" +
	"\tdeck_list\x18\a \x01(\tR\bdeckList\"L\n" +
	"\x1aRoomJoinTournamentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"v\n" +
	"!RoomLeaveTableOrTournamentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\"T\n" +
	"\"RoomLeaveTableOrTournamentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"j\n" +
	"\x15RoomWatchTableRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\"H\n" +
	"\x16RoomWatchTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"y\n" +
	"\x1aRoomWatchTournamentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12#\n" +
	"\rtournament_id\x18\x03 \x01(\tR\ftournamentId\"M\n" +
	"\x1bRoomWatchTournamentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa4\x01\n" +
	"\x15TableSwapSeatsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\x12\x1b\n" +
	"\tseat_num1\x18\x04 \x01(\x05R\bseatNum1\x12\x1b\n" +
	"\tseat_num2\x18\x05 \x01(\x05R\bseatNum2\"H\n" +
	"\x16TableSwapSeatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"g\n" +
	"\x12TableRemoveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\"E\n" +
	"\x13TableRemoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"h\n" +
	"\x13TableIsOwnerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\"1\n" +
	"\x14TableIsOwnerResponse\x12\x19\n" +
	"\bis_owner\x18\x01 \x01(\bR\aisOwner\"y\n" +
	"\x11DeckSubmitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\tR\atableId\x12*\n" +
	"\x04deck\x18\x03 \x01(\v2\x16.mage.v1.DeckCardListsR\x04deck\"J\n" +
	"\rDeckCardLists\x12\x1b\n" +
	"\tmain_deck\x18\x01 \x03(\tR\bmainDeck\x12\x1c\n" +
	"\tsideboard\x18\x02 \x03(\tR\tsideboard\"D\n" +
	"\x12DeckSubmitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"y\n" +
	"\x0fDeckSaveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdeck_name\x18\x02 \x01(\tR\bdeckName\x12*\n" +
	"\x04deck\x18\x03 \x01(\v2\x16.mage.v1.DeckCardListsR\x04deck\"B\n" +
	"\x10DeckSaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var (
	file_mage_v1_table_proto_rawDescOnce sync.Once
	file_mage_v1_table_proto_rawDescData []byte
)

func file_mage_v1_table_proto_rawDescGZIP() []byte {
	file_mage_v1_table_proto_rawDescOnce.Do(func() {
		file_mage_v1_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_v1_table_proto_rawDesc), len(file_mage_v1_table_proto_rawDesc)))
	})
	return file_mage_v1_table_proto_rawDescData
}

var file_mage_v1_table_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_mage_v1_table_proto_goTypes = []any{
	(*RoomCreateTableRequest)(nil),             // 0: mage.v1.RoomCreateTableRequest
	(*RoomCreateTableResponse)(nil),            // 1: mage.v1.RoomCreateTableResponse
	(*RoomCreateTournamentRequest)(nil),        // 2: mage.v1.RoomCreateTournamentRequest
	(*TournamentOptions)(nil),                  // 3: mage.v1.TournamentOptions
	(*RoomCreateTournamentResponse)(nil),       // 4: mage.v1.RoomCreateTournamentResponse
	(*RoomJoinTableRequest)(nil),               // 5: mage.v1.RoomJoinTableRequest
	(*RoomJoinTableResponse)(nil),              // 6: mage.v1.RoomJoinTableResponse
	(*RoomJoinTournamentRequest)(nil),          // 7: mage.v1.RoomJoinTournamentRequest
	(*RoomJoinTournamentResponse)(nil),         // 8: mage.v1.RoomJoinTournamentResponse
	(*RoomLeaveTableOrTournamentRequest)(nil),  // 9: mage.v1.RoomLeaveTableOrTournamentRequest
	(*RoomLeaveTableOrTournamentResponse)(nil), // 10: mage.v1.RoomLeaveTableOrTournamentResponse
	(*RoomWatchTableRequest)(nil),              // 11: mage.v1.RoomWatchTableRequest
	(*RoomWatchTableResponse)(nil),             // 12: mage.v1.RoomWatchTableResponse
	(*RoomWatchTournamentRequest)(nil),         // 13: mage.v1.RoomWatchTournamentRequest
	(*RoomWatchTournamentResponse)(nil),        // 14: mage.v1.RoomWatchTournamentResponse
	(*TableSwapSeatsRequest)(nil),              // 15: mage.v1.TableSwapSeatsRequest
	(*TableSwapSeatsResponse)(nil),             // 16: mage.v1.TableSwapSeatsResponse
	(*TableRemoveRequest)(nil),                 // 17: mage.v1.TableRemoveRequest
	(*TableRemoveResponse)(nil),                // 18: mage.v1.TableRemoveResponse
	(*TableIsOwnerRequest)(nil),                // 19: mage.v1.TableIsOwnerRequest
	(*TableIsOwnerResponse)(nil),               // 20: mage.v1.TableIsOwnerResponse
	(*DeckSubmitRequest)(nil),                  // 21: mage.v1.DeckSubmitRequest
	(*DeckCardLists)(nil),                      // 22: mage.v1.DeckCardLists
	(*DeckSubmitResponse)(nil),                 // 23: mage.v1.DeckSubmitResponse
	(*DeckSaveRequest)(nil),                    // 24: mage.v1.DeckSaveRequest
	(*DeckSaveResponse)(nil),                   // 25: mage.v1.DeckSaveResponse
	(*MatchOptions)(nil),                       // 26: mage.v1.MatchOptions
}
var file_mage_v1_table_proto_depIdxs = []int32{
	26, // 0: mage.v1.RoomCreateTableRequest.match_options:type_name -> mage.v1.MatchOptions
	3,  // 1: mage.v1.RoomCreateTournamentRequest.tournament_options:type_name -> mage.v1.TournamentOptions
	22, // 2: mage.v1.DeckSubmitRequest.deck:type_name -> mage.v1.DeckCardLists
	22, // 3: mage.v1.DeckSaveRequest.deck:type_name -> mage.v1.DeckCardLists
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_mage_v1_table_proto_init() }
func file_mage_v1_table_proto_init() {
	if File_mage_v1_table_proto != nil {
		return
	}
	file_mage_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_table_proto_rawDesc), len(file_mage_v1_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_v1_table_proto_goTypes,
		DependencyIndexes: file_mage_v1_table_proto_depIdxs,
		MessageInfos:      file_mage_v1_table_proto_msgTypes,
	}.Build()
	File_mage_v1_table_proto = out.File
	file_mage_v1_table_proto_goTypes = nil
	file_mage_v1_table_proto_depIdxs = nil
}
