// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mage/v1/tournament.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TournamentJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentJoinRequest) Reset() {
	*x = TournamentJoinRequest{}
	mi := &file_mage_v1_tournament_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentJoinRequest) ProtoMessage() {}

func (x *TournamentJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_tournament_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentJoinRequest.ProtoReflect.Descriptor instead.
func (*TournamentJoinRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_tournament_proto_rawDescGZIP(), []int{0}
}

func (x *TournamentJoinRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TournamentJoinRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type TournamentJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentJoinResponse) Reset() {
	*x = TournamentJoinResponse{}
	mi := &file_mage_v1_tournament_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentJoinResponse) ProtoMessage() {}

func (x *TournamentJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_tournament_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentJoinResponse.ProtoReflect.Descriptor instead.
func (*TournamentJoinResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_tournament_proto_rawDescGZIP(), []int{1}
}

func (x *TournamentJoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TournamentJoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TournamentStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TournamentId  string                 `protobuf:"bytes,3,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentStartRequest) Reset() {
	*x = TournamentStartRequest{}
	mi := &file_mage_v1_tournament_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentStartRequest) ProtoMessage() {}

func (x *TournamentStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_tournament_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentStartRequest.ProtoReflect.Descriptor instead.
func (*TournamentStartRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_tournament_proto_rawDescGZIP(), []int{2}
}

func (x *TournamentStartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TournamentStartRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TournamentStartRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type TournamentStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentStartResponse) Reset() {
	*x = TournamentStartResponse{}
	mi := &file_mage_v1_tournament_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentStartResponse) ProtoMessage() {}

func (x *TournamentStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_tournament_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentStartResponse.ProtoReflect.Descriptor instead.
func (*TournamentStartResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_tournament_proto_rawDescGZIP(), []int{3}
}

func (x *TournamentStartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TournamentStartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TournamentQuitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentQuitRequest) Reset() {
	*x = TournamentQuitRequest{}
	mi := &file_mage_v1_tournament_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentQuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentQuitRequest) ProtoMessage() {}

func (x *TournamentQuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_tournament_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentQuitRequest.ProtoReflect.Descriptor instead.
func (*TournamentQuitRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_tournament_proto_rawDescGZIP(), []int{4}
}

func (x *TournamentQuitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TournamentQuitRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type TournamentQuitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentQuitResponse) Reset() {
	*x = TournamentQuitResponse{}
	mi := &file_mage_v1_tournament_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentQuitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentQuitResponse) ProtoMessage() {}

func (x *TournamentQuitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_tournament_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentQuitResponse.ProtoReflect.Descriptor instead.
func (*TournamentQuitResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_tournament_proto_rawDescGZIP(), []int{5}
}

func (x *TournamentQuitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TournamentQuitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TournamentFindByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentFindByIdRequest) Reset() {
	*x = TournamentFindByIdRequest{}
	mi := &file_mage_v1_tournament_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentFindByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentFindByIdRequest) ProtoMessage() {}

func (x *TournamentFindByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_tournament_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentFindByIdRequest.ProtoReflect.Descriptor instead.
func (*TournamentFindByIdRequest) Descriptor() ([]byte, []int) {
	return file_mage_v1_tournament_proto_rawDescGZIP(), []int{6}
}

func (x *TournamentFindByIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TournamentFindByIdRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type TournamentFindByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *TournamentView        `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentFindByIdResponse) Reset() {
	*x = TournamentFindByIdResponse{}
	mi := &file_mage_v1_tournament_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentFindByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentFindByIdResponse) ProtoMessage() {}

func (x *TournamentFindByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mage_v1_tournament_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentFindByIdResponse.ProtoReflect.Descriptor instead.
func (*TournamentFindByIdResponse) Descriptor() ([]byte, []int) {
	return file_mage_v1_tournament_proto_rawDescGZIP(), []int{7}
}

func (x *TournamentFindByIdResponse) GetTournament() *TournamentView {
	if x != nil {
		return x.Tournament
	}
	return nil
}

var File_mage_v1_tournament_proto protoreflect.FileDescriptor

const file_mage_v1_tournament_proto_rawDesc = "" +
	"\n" +
	"\x18mage/v1/tournament.proto\x12\amage.v1\x1a\x14mage/v1/models.proto\"[\n" +
	"\x15TournamentJoinRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"H\n" +
	"\x16TournamentJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"u\n" +
	"\x16TournamentStartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12#\n" +
	"\rtournament_id\x18\x03 \x01(\tR\ftournamentId\"I\n" +
	"\x17TournamentStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"[\n" +
	"\x15TournamentQuitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"H\n" +
	"\x16TournamentQuitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"_\n" +
	"\x19TournamentFindByIdRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"U\n" +
	"\x1aTournamentFindByIdResponse\x127\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x17.mage.v1.TournamentViewR\n" +
	"tournamentB6Z4github.com/magefree/mage-server-go/pkg/proto/mage/v1b\x06proto3"

var (
	file_mage_v1_tournament_proto_rawDescOnce sync.Once
	file_mage_v1_tournament_proto_rawDescData []byte
)

func file_mage_v1_tournament_proto_rawDescGZIP() []byte {
	file_mage_v1_tournament_proto_rawDescOnce.Do(func() {
		file_mage_v1_tournament_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_v1_tournament_proto_rawDesc), len(file_mage_v1_tournament_proto_rawDesc)))
	})
	return file_mage_v1_tournament_proto_rawDescData
}

var file_mage_v1_tournament_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mage_v1_tournament_proto_goTypes = []any{
	(*TournamentJoinRequest)(nil),      // 0: mage.v1.TournamentJoinRequest
	(*TournamentJoinResponse)(nil),     // 1: mage.v1.TournamentJoinResponse
	(*TournamentStartRequest)(nil),     // 2: mage.v1.TournamentStartRequest
	(*TournamentStartResponse)(nil),    // 3: mage.v1.TournamentStartResponse
	(*TournamentQuitRequest)(nil),      // 4: mage.v1.TournamentQuitRequest
	(*TournamentQuitResponse)(nil),     // 5: mage.v1.TournamentQuitResponse
	(*TournamentFindByIdRequest)(nil),  // 6: mage.v1.TournamentFindByIdRequest
	(*TournamentFindByIdResponse)(nil), // 7: mage.v1.TournamentFindByIdResponse
	(*TournamentView)(nil),             // 8: mage.v1.TournamentView
}
var file_mage_v1_tournament_proto_depIdxs = []int32{
	8, // 0: mage.v1.TournamentFindByIdResponse.tournament:type_name -> mage.v1.TournamentView
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mage_v1_tournament_proto_init() }
func file_mage_v1_tournament_proto_init() {
	if File_mage_v1_tournament_proto != nil {
		return
	}
	file_mage_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_v1_tournament_proto_rawDesc), len(file_mage_v1_tournament_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_v1_tournament_proto_goTypes,
		DependencyIndexes: file_mage_v1_tournament_proto_depIdxs,
		MessageInfos:      file_mage_v1_tournament_proto_msgTypes,
	}.Build()
	File_mage_v1_tournament_proto = out.File
	file_mage_v1_tournament_proto_goTypes = nil
	file_mage_v1_tournament_proto_depIdxs = nil
}
